# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compare_window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_compare_window(object):
    def setupUi(self, compare_window):
        compare_window.setObjectName("compare_window")
        compare_window.setWindowModality(QtCore.Qt.WindowModal)
        compare_window.resize(920, 680)
        compare_window.setMinimumSize(QtCore.QSize(920, 680))
        compare_window.setMaximumSize(QtCore.QSize(920, 680))
        compare_window.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.compare_widget = QtWidgets.QWidget(compare_window)
        self.compare_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.compare_widget.setObjectName("compare_widget")
        self.close_compare_pbutton = QtWidgets.QPushButton(self.compare_widget)
        self.close_compare_pbutton.setGeometry(QtCore.QRect(840, 640, 71, 31))
        self.close_compare_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_compare_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.close_compare_pbutton.setObjectName("close_compare_pbutton")
        self.baseline_dose_widget = QtWidgets.QWidget(self.compare_widget)
        self.baseline_dose_widget.setGeometry(QtCore.QRect(0, 25, 314, 256))
        self.baseline_dose_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.baseline_dose_widget.setObjectName("baseline_dose_widget")
        self.baseline_meta_layout = QtWidgets.QVBoxLayout(self.baseline_dose_widget)
        self.baseline_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.baseline_meta_layout.setSpacing(0)
        self.baseline_meta_layout.setObjectName("baseline_meta_layout")
        self.baseline_dose_layout = QtWidgets.QVBoxLayout()
        self.baseline_dose_layout.setSpacing(0)
        self.baseline_dose_layout.setObjectName("baseline_dose_layout")
        self.baseline_meta_layout.addLayout(self.baseline_dose_layout)
        self.slice_selection_sbar = QtWidgets.QScrollBar(self.compare_widget)
        self.slice_selection_sbar.setGeometry(QtCore.QRect(230, 570, 376, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slice_selection_sbar.sizePolicy().hasHeightForWidth())
        self.slice_selection_sbar.setSizePolicy(sizePolicy)
        self.slice_selection_sbar.setMinimumSize(QtCore.QSize(239, 31))
        self.slice_selection_sbar.setMaximumSize(QtCore.QSize(16777215, 31))
        self.slice_selection_sbar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.slice_selection_sbar.setProperty("value", 49)
        self.slice_selection_sbar.setOrientation(QtCore.Qt.Horizontal)
        self.slice_selection_sbar.setObjectName("slice_selection_sbar")
        self.reference_dose_widget = QtWidgets.QWidget(self.compare_widget)
        self.reference_dose_widget.setGeometry(QtCore.QRect(303, 25, 314, 256))
        self.reference_dose_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.reference_dose_widget.setObjectName("reference_dose_widget")
        self.reference_meta_layout = QtWidgets.QVBoxLayout(self.reference_dose_widget)
        self.reference_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.reference_meta_layout.setSpacing(0)
        self.reference_meta_layout.setObjectName("reference_meta_layout")
        self.reference_dose_layout = QtWidgets.QVBoxLayout()
        self.reference_dose_layout.setSpacing(0)
        self.reference_dose_layout.setObjectName("reference_dose_layout")
        self.reference_meta_layout.addLayout(self.reference_dose_layout)
        self.baseline_label = QtWidgets.QLabel(self.compare_widget)
        self.baseline_label.setGeometry(QtCore.QRect(10, 5, 291, 25))
        self.baseline_label.setMinimumSize(QtCore.QSize(0, 25))
        self.baseline_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.baseline_label.setFont(font)
        self.baseline_label.setStyleSheet("border: 0px;")
        self.baseline_label.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_label.setObjectName("baseline_label")
        self.reference_label = QtWidgets.QLabel(self.compare_widget)
        self.reference_label.setGeometry(QtCore.QRect(315, 5, 291, 25))
        self.reference_label.setMinimumSize(QtCore.QSize(0, 25))
        self.reference_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.reference_label.setFont(font)
        self.reference_label.setStyleSheet("border: 0px;")
        self.reference_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reference_label.setObjectName("reference_label")
        self.slice_selection_label = QtWidgets.QLabel(self.compare_widget)
        self.slice_selection_label.setGeometry(QtCore.QRect(230, 540, 121, 25))
        self.slice_selection_label.setMinimumSize(QtCore.QSize(0, 25))
        self.slice_selection_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slice_selection_label.setFont(font)
        self.slice_selection_label.setStyleSheet("border: 0px;")
        self.slice_selection_label.setObjectName("slice_selection_label")
        self.opacity_label = QtWidgets.QLabel(self.compare_widget)
        self.opacity_label.setGeometry(QtCore.QRect(120, 540, 101, 25))
        self.opacity_label.setMinimumSize(QtCore.QSize(101, 25))
        self.opacity_label.setMaximumSize(QtCore.QSize(101, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.opacity_label.setFont(font)
        self.opacity_label.setStyleSheet("border: 0px;")
        self.opacity_label.setObjectName("opacity_label")
        self.opacity_sbox = QtWidgets.QSpinBox(self.compare_widget)
        self.opacity_sbox.setGeometry(QtCore.QRect(120, 570, 96, 31))
        self.opacity_sbox.setMinimumSize(QtCore.QSize(96, 31))
        self.opacity_sbox.setMaximumSize(QtCore.QSize(96, 31))
        self.opacity_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.opacity_sbox.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);\n"
"margin-right: 6px;")
        self.opacity_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.opacity_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.opacity_sbox.setMaximum(100)
        self.opacity_sbox.setProperty("value", 70)
        self.opacity_sbox.setObjectName("opacity_sbox")
        self.slice_selection_pos = QtWidgets.QLabel(self.compare_widget)
        self.slice_selection_pos.setGeometry(QtCore.QRect(495, 540, 111, 25))
        self.slice_selection_pos.setMinimumSize(QtCore.QSize(0, 25))
        self.slice_selection_pos.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slice_selection_pos.setFont(font)
        self.slice_selection_pos.setStyleSheet("border: 0px;")
        self.slice_selection_pos.setText("")
        self.slice_selection_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slice_selection_pos.setObjectName("slice_selection_pos")
        self.difference_dose_widget = QtWidgets.QWidget(self.compare_widget)
        self.difference_dose_widget.setGeometry(QtCore.QRect(606, 25, 314, 256))
        self.difference_dose_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.difference_dose_widget.setObjectName("difference_dose_widget")
        self.baseline_meta_layout_2 = QtWidgets.QVBoxLayout(self.difference_dose_widget)
        self.baseline_meta_layout_2.setContentsMargins(0, 0, 0, 0)
        self.baseline_meta_layout_2.setSpacing(0)
        self.baseline_meta_layout_2.setObjectName("baseline_meta_layout_2")
        self.difference_dose_layout = QtWidgets.QVBoxLayout()
        self.difference_dose_layout.setSpacing(0)
        self.difference_dose_layout.setObjectName("difference_dose_layout")
        self.baseline_meta_layout_2.addLayout(self.difference_dose_layout)
        self.difference_label = QtWidgets.QLabel(self.compare_widget)
        self.difference_label.setGeometry(QtCore.QRect(620, 5, 291, 25))
        self.difference_label.setMinimumSize(QtCore.QSize(0, 25))
        self.difference_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.difference_label.setFont(font)
        self.difference_label.setStyleSheet("border: 0px;")
        self.difference_label.setAlignment(QtCore.Qt.AlignCenter)
        self.difference_label.setObjectName("difference_label")
        self.baseline_dvh_widget = QtWidgets.QWidget(self.compare_widget)
        self.baseline_dvh_widget.setGeometry(QtCore.QRect(0, 270, 314, 256))
        self.baseline_dvh_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.baseline_dvh_widget.setObjectName("baseline_dvh_widget")
        self.dvh_meta_layout = QtWidgets.QVBoxLayout(self.baseline_dvh_widget)
        self.dvh_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.dvh_meta_layout.setSpacing(0)
        self.dvh_meta_layout.setObjectName("dvh_meta_layout")
        self.baseline_dvh_layout = QtWidgets.QVBoxLayout()
        self.baseline_dvh_layout.setSpacing(0)
        self.baseline_dvh_layout.setObjectName("baseline_dvh_layout")
        self.dvh_meta_layout.addLayout(self.baseline_dvh_layout)
        self.reference_dvh_widget = QtWidgets.QWidget(self.compare_widget)
        self.reference_dvh_widget.setGeometry(QtCore.QRect(303, 270, 314, 256))
        self.reference_dvh_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.reference_dvh_widget.setObjectName("reference_dvh_widget")
        self.dvh_meta_layout_2 = QtWidgets.QVBoxLayout(self.reference_dvh_widget)
        self.dvh_meta_layout_2.setContentsMargins(0, 0, 0, 0)
        self.dvh_meta_layout_2.setSpacing(0)
        self.dvh_meta_layout_2.setObjectName("dvh_meta_layout_2")
        self.reference_dvh_layout = QtWidgets.QVBoxLayout()
        self.reference_dvh_layout.setSpacing(0)
        self.reference_dvh_layout.setObjectName("reference_dvh_layout")
        self.dvh_meta_layout_2.addLayout(self.reference_dvh_layout)
        self.difference_dvh_widget = QtWidgets.QWidget(self.compare_widget)
        self.difference_dvh_widget.setGeometry(QtCore.QRect(606, 270, 314, 256))
        self.difference_dvh_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.difference_dvh_widget.setObjectName("difference_dvh_widget")
        self.dvh_meta_layout_3 = QtWidgets.QVBoxLayout(self.difference_dvh_widget)
        self.dvh_meta_layout_3.setContentsMargins(0, 0, 0, 0)
        self.dvh_meta_layout_3.setSpacing(0)
        self.dvh_meta_layout_3.setObjectName("dvh_meta_layout_3")
        self.difference_dvh_layout = QtWidgets.QVBoxLayout()
        self.difference_dvh_layout.setSpacing(0)
        self.difference_dvh_layout.setObjectName("difference_dvh_layout")
        self.dvh_meta_layout_3.addLayout(self.difference_dvh_layout)
        self.dvh_options_widget = QtWidgets.QWidget(self.compare_widget)
        self.dvh_options_widget.setGeometry(QtCore.QRect(0, 610, 616, 61))
        self.dvh_options_widget.setMaximumSize(QtCore.QSize(16777215, 70))
        self.dvh_options_widget.setStyleSheet("border: 0px solid;")
        self.dvh_options_widget.setObjectName("dvh_options_widget")
        self.dvh_options_layout = QtWidgets.QGridLayout(self.dvh_options_widget)
        self.dvh_options_layout.setContentsMargins(10, 0, 10, 16)
        self.dvh_options_layout.setHorizontalSpacing(4)
        self.dvh_options_layout.setVerticalSpacing(14)
        self.dvh_options_layout.setObjectName("dvh_options_layout")
        self.minimum_ledit = QtWidgets.QLineEdit(self.dvh_options_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimum_ledit.sizePolicy().hasHeightForWidth())
        self.minimum_ledit.setSizePolicy(sizePolicy)
        self.minimum_ledit.setMinimumSize(QtCore.QSize(50, 31))
        self.minimum_ledit.setMaximumSize(QtCore.QSize(180, 31))
        self.minimum_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.minimum_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.minimum_ledit.setReadOnly(True)
        self.minimum_ledit.setObjectName("minimum_ledit")
        self.dvh_options_layout.addWidget(self.minimum_ledit, 1, 5, 1, 1)
        self.std_ledit = QtWidgets.QLineEdit(self.dvh_options_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.std_ledit.sizePolicy().hasHeightForWidth())
        self.std_ledit.setSizePolicy(sizePolicy)
        self.std_ledit.setMinimumSize(QtCore.QSize(50, 31))
        self.std_ledit.setMaximumSize(QtCore.QSize(180, 31))
        self.std_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.std_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.std_ledit.setReadOnly(True)
        self.std_ledit.setObjectName("std_ledit")
        self.dvh_options_layout.addWidget(self.std_ledit, 1, 3, 1, 1)
        self.maximum_ledit = QtWidgets.QLineEdit(self.dvh_options_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximum_ledit.sizePolicy().hasHeightForWidth())
        self.maximum_ledit.setSizePolicy(sizePolicy)
        self.maximum_ledit.setMinimumSize(QtCore.QSize(50, 31))
        self.maximum_ledit.setMaximumSize(QtCore.QSize(180, 31))
        self.maximum_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.maximum_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.maximum_ledit.setReadOnly(True)
        self.maximum_ledit.setObjectName("maximum_ledit")
        self.dvh_options_layout.addWidget(self.maximum_ledit, 1, 4, 1, 1)
        self.maximum_label = QtWidgets.QLabel(self.dvh_options_widget)
        self.maximum_label.setMinimumSize(QtCore.QSize(50, 25))
        self.maximum_label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maximum_label.setFont(font)
        self.maximum_label.setAlignment(QtCore.Qt.AlignCenter)
        self.maximum_label.setObjectName("maximum_label")
        self.dvh_options_layout.addWidget(self.maximum_label, 0, 4, 1, 1)
        self.mean_label = QtWidgets.QLabel(self.dvh_options_widget)
        self.mean_label.setMinimumSize(QtCore.QSize(50, 25))
        self.mean_label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mean_label.setFont(font)
        self.mean_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mean_label.setObjectName("mean_label")
        self.dvh_options_layout.addWidget(self.mean_label, 0, 2, 1, 1)
        self.segment_label = QtWidgets.QLabel(self.dvh_options_widget)
        self.segment_label.setMinimumSize(QtCore.QSize(80, 25))
        self.segment_label.setMaximumSize(QtCore.QSize(400, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.segment_label.setFont(font)
        self.segment_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.segment_label.setObjectName("segment_label")
        self.dvh_options_layout.addWidget(self.segment_label, 0, 1, 1, 1)
        self.mean_ledit = QtWidgets.QLineEdit(self.dvh_options_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mean_ledit.sizePolicy().hasHeightForWidth())
        self.mean_ledit.setSizePolicy(sizePolicy)
        self.mean_ledit.setMinimumSize(QtCore.QSize(50, 31))
        self.mean_ledit.setMaximumSize(QtCore.QSize(180, 31))
        self.mean_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.mean_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.mean_ledit.setReadOnly(True)
        self.mean_ledit.setObjectName("mean_ledit")
        self.dvh_options_layout.addWidget(self.mean_ledit, 1, 2, 1, 1)
        self.std_label = QtWidgets.QLabel(self.dvh_options_widget)
        self.std_label.setMinimumSize(QtCore.QSize(50, 25))
        self.std_label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.std_label.setFont(font)
        self.std_label.setAlignment(QtCore.Qt.AlignCenter)
        self.std_label.setObjectName("std_label")
        self.dvh_options_layout.addWidget(self.std_label, 0, 3, 1, 1)
        self.minimum_label = QtWidgets.QLabel(self.dvh_options_widget)
        self.minimum_label.setMinimumSize(QtCore.QSize(50, 25))
        self.minimum_label.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minimum_label.setFont(font)
        self.minimum_label.setAlignment(QtCore.Qt.AlignCenter)
        self.minimum_label.setObjectName("minimum_label")
        self.dvh_options_layout.addWidget(self.minimum_label, 0, 5, 1, 1)
        self.segment_ledit = QtWidgets.QLineEdit(self.dvh_options_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segment_ledit.sizePolicy().hasHeightForWidth())
        self.segment_ledit.setSizePolicy(sizePolicy)
        self.segment_ledit.setMinimumSize(QtCore.QSize(200, 31))
        self.segment_ledit.setMaximumSize(QtCore.QSize(400, 31))
        self.segment_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.segment_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.segment_ledit.setReadOnly(True)
        self.segment_ledit.setObjectName("segment_ledit")
        self.dvh_options_layout.addWidget(self.segment_ledit, 1, 1, 1, 1)
        self.joint_dvh_pbutton = QtWidgets.QPushButton(self.compare_widget)
        self.joint_dvh_pbutton.setGeometry(QtCore.QRect(620, 640, 121, 31))
        self.joint_dvh_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_dvh_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.joint_dvh_pbutton.setObjectName("joint_dvh_pbutton")
        self.disCT_cbox = QtWidgets.QCheckBox(self.compare_widget)
        self.disCT_cbox.setGeometry(QtCore.QRect(620, 556, 100, 30))
        self.disCT_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 0px solid")
        self.disCT_cbox.setObjectName("disCT_cbox")
        self.disSegm_cbox = QtWidgets.QCheckBox(self.compare_widget)
        self.disSegm_cbox.setGeometry(QtCore.QRect(740, 556, 181, 30))
        self.disSegm_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 0px solid")
        self.disSegm_cbox.setObjectName("disSegm_cbox")
        self.disDose_cbox = QtWidgets.QCheckBox(self.compare_widget)
        self.disDose_cbox.setGeometry(QtCore.QRect(620, 584, 110, 30))
        self.disDose_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 0px solid")
        self.disDose_cbox.setObjectName("disDose_cbox")
        self.disDoseCon_cbox = QtWidgets.QCheckBox(self.compare_widget)
        self.disDoseCon_cbox.setGeometry(QtCore.QRect(740, 584, 181, 30))
        self.disDoseCon_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 0px solid")
        self.disDoseCon_cbox.setObjectName("disDoseCon_cbox")
        self.plane_label = QtWidgets.QLabel(self.compare_widget)
        self.plane_label.setGeometry(QtCore.QRect(10, 540, 101, 25))
        self.plane_label.setMinimumSize(QtCore.QSize(101, 25))
        self.plane_label.setMaximumSize(QtCore.QSize(101, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plane_label.setFont(font)
        self.plane_label.setStyleSheet("border: 0px;")
        self.plane_label.setObjectName("plane_label")
        self.plane_cbox = QtWidgets.QComboBox(self.compare_widget)
        self.plane_cbox.setGeometry(QtCore.QRect(10, 570, 96, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plane_cbox.sizePolicy().hasHeightForWidth())
        self.plane_cbox.setSizePolicy(sizePolicy)
        self.plane_cbox.setMinimumSize(QtCore.QSize(96, 31))
        self.plane_cbox.setMaximumSize(QtCore.QSize(96, 31))
        self.plane_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plane_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.plane_cbox.setObjectName("plane_cbox")
        self.plane_cbox.addItem("")
        self.plane_cbox.addItem("")
        self.plane_cbox.addItem("")
        compare_window.setCentralWidget(self.compare_widget)

        self.retranslateUi(compare_window)
        self.plane_cbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(compare_window)

    def retranslateUi(self, compare_window):
        _translate = QtCore.QCoreApplication.translate
        compare_window.setWindowTitle(_translate("compare_window", "Plan Comparison Tool"))
        self.close_compare_pbutton.setText(_translate("compare_window", "Close"))
        self.slice_selection_label.setText(_translate("compare_window", "Slice"))
        self.opacity_label.setText(_translate("compare_window", "Dose opacity"))
        self.maximum_label.setText(_translate("compare_window", "Max"))
        self.mean_label.setText(_translate("compare_window", "Mean"))
        self.segment_label.setText(_translate("compare_window", "Segment"))
        self.std_label.setText(_translate("compare_window", "Std"))
        self.minimum_label.setText(_translate("compare_window", "Min"))
        self.joint_dvh_pbutton.setText(_translate("compare_window", "Show joint DVH"))
        self.disCT_cbox.setText(_translate("compare_window", "Disable CT"))
        self.disSegm_cbox.setText(_translate("compare_window", "Disable segmentation"))
        self.disDose_cbox.setText(_translate("compare_window", "Disable dose"))
        self.disDoseCon_cbox.setText(_translate("compare_window", "Disable dose contours"))
        self.plane_label.setText(_translate("compare_window", "Plane"))
        self.plane_cbox.setCurrentText(_translate("compare_window", "axial"))
        self.plane_cbox.setItemText(0, _translate("compare_window", "axial"))
        self.plane_cbox.setItemText(1, _translate("compare_window", "coronal"))
        self.plane_cbox.setItemText(2, _translate("compare_window", "sagittal"))
