# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compare_window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_compare_window(object):
    def setupUi(self, compare_window):
        compare_window.setObjectName("compare_window")
        compare_window.setWindowModality(QtCore.Qt.WindowModal)
        compare_window.resize(920, 680)
        compare_window.setMinimumSize(QtCore.QSize(920, 680))
        compare_window.setMaximumSize(QtCore.QSize(2560, 1440))
        compare_window.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.compare_widget = QtWidgets.QWidget(compare_window)
        self.compare_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.compare_widget.setObjectName("compare_widget")
        self.compare_widget_layout = QtWidgets.QVBoxLayout(self.compare_widget)
        self.compare_widget_layout.setContentsMargins(10, 10, 10, 0)
        self.compare_widget_layout.setSpacing(10)
        self.compare_widget_layout.setObjectName("compare_widget_layout")
        self.dose_dvh_layout = QtWidgets.QGridLayout()
        self.dose_dvh_layout.setSpacing(0)
        self.dose_dvh_layout.setObjectName("dose_dvh_layout")
        self.baseline_dose_widget = QtWidgets.QWidget(self.compare_widget)
        self.baseline_dose_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.baseline_dose_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.baseline_dose_widget.setObjectName("baseline_dose_widget")
        self.baseline_meta_layout = QtWidgets.QVBoxLayout(self.baseline_dose_widget)
        self.baseline_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.baseline_meta_layout.setSpacing(0)
        self.baseline_meta_layout.setObjectName("baseline_meta_layout")
        self.baseline_dose_layout = QtWidgets.QVBoxLayout()
        self.baseline_dose_layout.setSpacing(0)
        self.baseline_dose_layout.setObjectName("baseline_dose_layout")
        self.baseline_meta_layout.addLayout(self.baseline_dose_layout)
        self.dose_dvh_layout.addWidget(self.baseline_dose_widget, 1, 0, 1, 1)
        self.baseline_label = QtWidgets.QLabel(self.compare_widget)
        self.baseline_label.setMinimumSize(QtCore.QSize(0, 25))
        self.baseline_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.baseline_label.setFont(font)
        self.baseline_label.setStyleSheet("border: 0px;")
        self.baseline_label.setAlignment(QtCore.Qt.AlignCenter)
        self.baseline_label.setObjectName("baseline_label")
        self.dose_dvh_layout.addWidget(self.baseline_label, 0, 0, 1, 1)
        self.difference_label = QtWidgets.QLabel(self.compare_widget)
        self.difference_label.setMinimumSize(QtCore.QSize(0, 25))
        self.difference_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.difference_label.setFont(font)
        self.difference_label.setStyleSheet("border: 0px;")
        self.difference_label.setAlignment(QtCore.Qt.AlignCenter)
        self.difference_label.setObjectName("difference_label")
        self.dose_dvh_layout.addWidget(self.difference_label, 0, 2, 1, 1)
        self.reference_dose_widget = QtWidgets.QWidget(self.compare_widget)
        self.reference_dose_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.reference_dose_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.reference_dose_widget.setObjectName("reference_dose_widget")
        self.reference_meta_layout = QtWidgets.QVBoxLayout(self.reference_dose_widget)
        self.reference_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.reference_meta_layout.setSpacing(0)
        self.reference_meta_layout.setObjectName("reference_meta_layout")
        self.reference_dose_layout = QtWidgets.QVBoxLayout()
        self.reference_dose_layout.setSpacing(0)
        self.reference_dose_layout.setObjectName("reference_dose_layout")
        self.reference_meta_layout.addLayout(self.reference_dose_layout)
        self.dose_dvh_layout.addWidget(self.reference_dose_widget, 1, 1, 1, 1)
        self.reference_label = QtWidgets.QLabel(self.compare_widget)
        self.reference_label.setMinimumSize(QtCore.QSize(0, 25))
        self.reference_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.reference_label.setFont(font)
        self.reference_label.setStyleSheet("border: 0px;")
        self.reference_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reference_label.setObjectName("reference_label")
        self.dose_dvh_layout.addWidget(self.reference_label, 0, 1, 1, 1)
        self.difference_dose_widget = QtWidgets.QWidget(self.compare_widget)
        self.difference_dose_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.difference_dose_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.difference_dose_widget.setObjectName("difference_dose_widget")
        self.baseline_meta_layout_2 = QtWidgets.QVBoxLayout(self.difference_dose_widget)
        self.baseline_meta_layout_2.setContentsMargins(0, 0, 0, 0)
        self.baseline_meta_layout_2.setSpacing(0)
        self.baseline_meta_layout_2.setObjectName("baseline_meta_layout_2")
        self.difference_dose_layout = QtWidgets.QVBoxLayout()
        self.difference_dose_layout.setSpacing(0)
        self.difference_dose_layout.setObjectName("difference_dose_layout")
        self.baseline_meta_layout_2.addLayout(self.difference_dose_layout)
        self.dose_dvh_layout.addWidget(self.difference_dose_widget, 1, 2, 1, 1)
        self.baseline_dvh_widget = QtWidgets.QWidget(self.compare_widget)
        self.baseline_dvh_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.baseline_dvh_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.baseline_dvh_widget.setObjectName("baseline_dvh_widget")
        self.dvh_meta_layout = QtWidgets.QVBoxLayout(self.baseline_dvh_widget)
        self.dvh_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.dvh_meta_layout.setSpacing(0)
        self.dvh_meta_layout.setObjectName("dvh_meta_layout")
        self.baseline_dvh_layout = QtWidgets.QVBoxLayout()
        self.baseline_dvh_layout.setSpacing(0)
        self.baseline_dvh_layout.setObjectName("baseline_dvh_layout")
        self.dvh_meta_layout.addLayout(self.baseline_dvh_layout)
        self.dose_dvh_layout.addWidget(self.baseline_dvh_widget, 2, 0, 1, 1)
        self.reference_dvh_widget = QtWidgets.QWidget(self.compare_widget)
        self.reference_dvh_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.reference_dvh_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.reference_dvh_widget.setObjectName("reference_dvh_widget")
        self.dvh_meta_layout_2 = QtWidgets.QVBoxLayout(self.reference_dvh_widget)
        self.dvh_meta_layout_2.setContentsMargins(0, 0, 0, 0)
        self.dvh_meta_layout_2.setSpacing(0)
        self.dvh_meta_layout_2.setObjectName("dvh_meta_layout_2")
        self.reference_dvh_layout = QtWidgets.QVBoxLayout()
        self.reference_dvh_layout.setSpacing(0)
        self.reference_dvh_layout.setObjectName("reference_dvh_layout")
        self.dvh_meta_layout_2.addLayout(self.reference_dvh_layout)
        self.dose_dvh_layout.addWidget(self.reference_dvh_widget, 2, 1, 1, 1)
        self.difference_dvh_widget = QtWidgets.QWidget(self.compare_widget)
        self.difference_dvh_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.difference_dvh_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.difference_dvh_widget.setObjectName("difference_dvh_widget")
        self.dvh_meta_layout_3 = QtWidgets.QVBoxLayout(self.difference_dvh_widget)
        self.dvh_meta_layout_3.setContentsMargins(0, 0, 0, 0)
        self.dvh_meta_layout_3.setSpacing(0)
        self.dvh_meta_layout_3.setObjectName("dvh_meta_layout_3")
        self.difference_dvh_layout = QtWidgets.QVBoxLayout()
        self.difference_dvh_layout.setSpacing(0)
        self.difference_dvh_layout.setObjectName("difference_dvh_layout")
        self.dvh_meta_layout_3.addLayout(self.difference_dvh_layout)
        self.dose_dvh_layout.addWidget(self.difference_dvh_widget, 2, 2, 1, 1)
        self.compare_widget_layout.addLayout(self.dose_dvh_layout)
        self.fields_layout = QtWidgets.QGridLayout()
        self.fields_layout.setContentsMargins(10, -1, 10, -1)
        self.fields_layout.setObjectName("fields_layout")
        self.display_options_layout = QtWidgets.QGridLayout()
        self.display_options_layout.setContentsMargins(-1, -1, -1, 0)
        self.display_options_layout.setHorizontalSpacing(6)
        self.display_options_layout.setVerticalSpacing(10)
        self.display_options_layout.setObjectName("display_options_layout")
        self.disSegm_cbox = QtWidgets.QCheckBox(self.compare_widget)
        self.disSegm_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 0px solid")
        self.disSegm_cbox.setChecked(True)
        self.disSegm_cbox.setObjectName("disSegm_cbox")
        self.display_options_layout.addWidget(self.disSegm_cbox, 1, 1, 1, 1)
        self.disCT_cbox = QtWidgets.QCheckBox(self.compare_widget)
        self.disCT_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 0px solid")
        self.disCT_cbox.setObjectName("disCT_cbox")
        self.display_options_layout.addWidget(self.disCT_cbox, 1, 0, 1, 1)
        self.disDose_cbox = QtWidgets.QCheckBox(self.compare_widget)
        self.disDose_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 0px solid")
        self.disDose_cbox.setObjectName("disDose_cbox")
        self.display_options_layout.addWidget(self.disDose_cbox, 2, 0, 1, 1)
        self.disDoseCon_cbox = QtWidgets.QCheckBox(self.compare_widget)
        self.disDoseCon_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 0px solid")
        self.disDoseCon_cbox.setChecked(True)
        self.disDoseCon_cbox.setObjectName("disDoseCon_cbox")
        self.display_options_layout.addWidget(self.disDoseCon_cbox, 2, 1, 1, 1)
        self.display_options_label = QtWidgets.QLabel(self.compare_widget)
        self.display_options_label.setMinimumSize(QtCore.QSize(0, 25))
        self.display_options_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.display_options_label.setFont(font)
        self.display_options_label.setStyleSheet("border: 0px;")
        self.display_options_label.setText("")
        self.display_options_label.setObjectName("display_options_label")
        self.display_options_layout.addWidget(self.display_options_label, 0, 0, 1, 1)
        self.fields_layout.addLayout(self.display_options_layout, 0, 1, 1, 1)
        self.dose_options_layout = QtWidgets.QHBoxLayout()
        self.dose_options_layout.setObjectName("dose_options_layout")
        self.plane_layout = QtWidgets.QVBoxLayout()
        self.plane_layout.setContentsMargins(-1, -1, -1, 2)
        self.plane_layout.setObjectName("plane_layout")
        self.plane_label = QtWidgets.QLabel(self.compare_widget)
        self.plane_label.setMinimumSize(QtCore.QSize(0, 25))
        self.plane_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plane_label.setFont(font)
        self.plane_label.setStyleSheet("border: 0px;")
        self.plane_label.setObjectName("plane_label")
        self.plane_layout.addWidget(self.plane_label)
        self.plane_cbox = QtWidgets.QComboBox(self.compare_widget)
        self.plane_cbox.setMinimumSize(QtCore.QSize(101, 31))
        self.plane_cbox.setMaximumSize(QtCore.QSize(16777215, 31))
        self.plane_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plane_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.plane_cbox.setObjectName("plane_cbox")
        self.plane_cbox.addItem("")
        self.plane_cbox.addItem("")
        self.plane_cbox.addItem("")
        self.plane_layout.addWidget(self.plane_cbox)
        self.dose_options_layout.addLayout(self.plane_layout)
        self.opacity_layout = QtWidgets.QVBoxLayout()
        self.opacity_layout.setContentsMargins(-1, -1, -1, 2)
        self.opacity_layout.setObjectName("opacity_layout")
        self.opacity_label = QtWidgets.QLabel(self.compare_widget)
        self.opacity_label.setMinimumSize(QtCore.QSize(0, 25))
        self.opacity_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.opacity_label.setFont(font)
        self.opacity_label.setStyleSheet("border: 0px;")
        self.opacity_label.setObjectName("opacity_label")
        self.opacity_layout.addWidget(self.opacity_label)
        self.opacity_sbox = QtWidgets.QSpinBox(self.compare_widget)
        self.opacity_sbox.setMinimumSize(QtCore.QSize(101, 31))
        self.opacity_sbox.setMaximumSize(QtCore.QSize(16777215, 31))
        self.opacity_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.opacity_sbox.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.opacity_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.opacity_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.opacity_sbox.setMaximum(100)
        self.opacity_sbox.setProperty("value", 70)
        self.opacity_sbox.setObjectName("opacity_sbox")
        self.opacity_layout.addWidget(self.opacity_sbox)
        self.dose_options_layout.addLayout(self.opacity_layout)
        self.slice_layout = QtWidgets.QVBoxLayout()
        self.slice_layout.setContentsMargins(-1, -1, -1, 2)
        self.slice_layout.setObjectName("slice_layout")
        self.slice_label_layout = QtWidgets.QHBoxLayout()
        self.slice_label_layout.setObjectName("slice_label_layout")
        self.slice_selection_label = QtWidgets.QLabel(self.compare_widget)
        self.slice_selection_label.setMinimumSize(QtCore.QSize(0, 25))
        self.slice_selection_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slice_selection_label.setFont(font)
        self.slice_selection_label.setStyleSheet("border: 0px;")
        self.slice_selection_label.setObjectName("slice_selection_label")
        self.slice_label_layout.addWidget(self.slice_selection_label)
        self.slice_selection_pos = QtWidgets.QLabel(self.compare_widget)
        self.slice_selection_pos.setMinimumSize(QtCore.QSize(0, 25))
        self.slice_selection_pos.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slice_selection_pos.setFont(font)
        self.slice_selection_pos.setStyleSheet("border: 0px;")
        self.slice_selection_pos.setText("")
        self.slice_selection_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slice_selection_pos.setObjectName("slice_selection_pos")
        self.slice_label_layout.addWidget(self.slice_selection_pos)
        self.slice_layout.addLayout(self.slice_label_layout)
        self.slice_selection_sbar = QtWidgets.QScrollBar(self.compare_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slice_selection_sbar.sizePolicy().hasHeightForWidth())
        self.slice_selection_sbar.setSizePolicy(sizePolicy)
        self.slice_selection_sbar.setMinimumSize(QtCore.QSize(0, 31))
        self.slice_selection_sbar.setMaximumSize(QtCore.QSize(16777215, 31))
        self.slice_selection_sbar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.slice_selection_sbar.setProperty("value", 49)
        self.slice_selection_sbar.setOrientation(QtCore.Qt.Horizontal)
        self.slice_selection_sbar.setObjectName("slice_selection_sbar")
        self.slice_layout.addWidget(self.slice_selection_sbar)
        self.dose_options_layout.addLayout(self.slice_layout)
        self.fields_layout.addLayout(self.dose_options_layout, 0, 0, 1, 1)
        self.stats_layout = QtWidgets.QGridLayout()
        self.stats_layout.setVerticalSpacing(15)
        self.stats_layout.setObjectName("stats_layout")
        self.segment_label = QtWidgets.QLabel(self.compare_widget)
        self.segment_label.setMinimumSize(QtCore.QSize(212, 25))
        self.segment_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.segment_label.setFont(font)
        self.segment_label.setStyleSheet("border: 0px solid;")
        self.segment_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.segment_label.setObjectName("segment_label")
        self.stats_layout.addWidget(self.segment_label, 0, 0, 1, 1)
        self.maximum_label = QtWidgets.QLabel(self.compare_widget)
        self.maximum_label.setMinimumSize(QtCore.QSize(0, 25))
        self.maximum_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maximum_label.setFont(font)
        self.maximum_label.setStyleSheet("border: 0px solid;")
        self.maximum_label.setAlignment(QtCore.Qt.AlignCenter)
        self.maximum_label.setObjectName("maximum_label")
        self.stats_layout.addWidget(self.maximum_label, 0, 3, 1, 1)
        self.minimum_label = QtWidgets.QLabel(self.compare_widget)
        self.minimum_label.setMinimumSize(QtCore.QSize(0, 25))
        self.minimum_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minimum_label.setFont(font)
        self.minimum_label.setStyleSheet("border: 0px solid;")
        self.minimum_label.setAlignment(QtCore.Qt.AlignCenter)
        self.minimum_label.setObjectName("minimum_label")
        self.stats_layout.addWidget(self.minimum_label, 0, 4, 1, 1)
        self.std_label = QtWidgets.QLabel(self.compare_widget)
        self.std_label.setMinimumSize(QtCore.QSize(0, 25))
        self.std_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.std_label.setFont(font)
        self.std_label.setStyleSheet("border: 0px solid;")
        self.std_label.setAlignment(QtCore.Qt.AlignCenter)
        self.std_label.setObjectName("std_label")
        self.stats_layout.addWidget(self.std_label, 0, 2, 1, 1)
        self.mean_label = QtWidgets.QLabel(self.compare_widget)
        self.mean_label.setMinimumSize(QtCore.QSize(0, 25))
        self.mean_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mean_label.setFont(font)
        self.mean_label.setStyleSheet("border: 0px solid;")
        self.mean_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mean_label.setObjectName("mean_label")
        self.stats_layout.addWidget(self.mean_label, 0, 1, 1, 1)
        self.segment_ledit = QtWidgets.QLineEdit(self.compare_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segment_ledit.sizePolicy().hasHeightForWidth())
        self.segment_ledit.setSizePolicy(sizePolicy)
        self.segment_ledit.setMinimumSize(QtCore.QSize(212, 31))
        self.segment_ledit.setMaximumSize(QtCore.QSize(212, 31))
        self.segment_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.segment_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.segment_ledit.setReadOnly(True)
        self.segment_ledit.setObjectName("segment_ledit")
        self.stats_layout.addWidget(self.segment_ledit, 1, 0, 1, 1)
        self.mean_ledit = QtWidgets.QLineEdit(self.compare_widget)
        self.mean_ledit.setMinimumSize(QtCore.QSize(0, 31))
        self.mean_ledit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.mean_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.mean_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.mean_ledit.setReadOnly(True)
        self.mean_ledit.setObjectName("mean_ledit")
        self.stats_layout.addWidget(self.mean_ledit, 1, 1, 1, 1)
        self.std_ledit = QtWidgets.QLineEdit(self.compare_widget)
        self.std_ledit.setMinimumSize(QtCore.QSize(0, 31))
        self.std_ledit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.std_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.std_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.std_ledit.setReadOnly(True)
        self.std_ledit.setObjectName("std_ledit")
        self.stats_layout.addWidget(self.std_ledit, 1, 2, 1, 1)
        self.maximum_ledit = QtWidgets.QLineEdit(self.compare_widget)
        self.maximum_ledit.setMinimumSize(QtCore.QSize(0, 31))
        self.maximum_ledit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.maximum_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.maximum_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.maximum_ledit.setReadOnly(True)
        self.maximum_ledit.setObjectName("maximum_ledit")
        self.stats_layout.addWidget(self.maximum_ledit, 1, 3, 1, 1)
        self.minimum_ledit = QtWidgets.QLineEdit(self.compare_widget)
        self.minimum_ledit.setMinimumSize(QtCore.QSize(0, 31))
        self.minimum_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.minimum_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.minimum_ledit.setReadOnly(True)
        self.minimum_ledit.setObjectName("minimum_ledit")
        self.stats_layout.addWidget(self.minimum_ledit, 1, 4, 1, 1)
        self.fields_layout.addLayout(self.stats_layout, 1, 0, 1, 1)
        self.joint_plots_layout = QtWidgets.QGridLayout()
        self.joint_plots_layout.setContentsMargins(-1, 40, -1, -1)
        self.joint_plots_layout.setVerticalSpacing(15)
        self.joint_plots_layout.setObjectName("joint_plots_layout")
        self.joint_buttons_layout = QtWidgets.QHBoxLayout()
        self.joint_buttons_layout.setContentsMargins(-1, -1, 35, -1)
        self.joint_buttons_layout.setSpacing(10)
        self.joint_buttons_layout.setObjectName("joint_buttons_layout")
        self.joint_dvh_pbutton = QtWidgets.QPushButton(self.compare_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint_dvh_pbutton.sizePolicy().hasHeightForWidth())
        self.joint_dvh_pbutton.setSizePolicy(sizePolicy)
        self.joint_dvh_pbutton.setMinimumSize(QtCore.QSize(121, 31))
        self.joint_dvh_pbutton.setMaximumSize(QtCore.QSize(121, 31))
        self.joint_dvh_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_dvh_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.joint_dvh_pbutton.setObjectName("joint_dvh_pbutton")
        self.joint_buttons_layout.addWidget(self.joint_dvh_pbutton)
        self.joint_ntcp_pbutton = QtWidgets.QPushButton(self.compare_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint_ntcp_pbutton.sizePolicy().hasHeightForWidth())
        self.joint_ntcp_pbutton.setSizePolicy(sizePolicy)
        self.joint_ntcp_pbutton.setMinimumSize(QtCore.QSize(121, 31))
        self.joint_ntcp_pbutton.setMaximumSize(QtCore.QSize(121, 31))
        self.joint_ntcp_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joint_ntcp_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.joint_ntcp_pbutton.setObjectName("joint_ntcp_pbutton")
        self.joint_buttons_layout.addWidget(self.joint_ntcp_pbutton)
        self.joint_plots_layout.addLayout(self.joint_buttons_layout, 2, 1, 1, 1)
        self.fields_layout.addLayout(self.joint_plots_layout, 1, 1, 1, 1)
        self.compare_widget_layout.addLayout(self.fields_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.compare_widget_layout.addItem(spacerItem)
        self.bottom_layout = QtWidgets.QHBoxLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_layout.addItem(spacerItem1)
        self.close_compare_pbutton = QtWidgets.QPushButton(self.compare_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_compare_pbutton.sizePolicy().hasHeightForWidth())
        self.close_compare_pbutton.setSizePolicy(sizePolicy)
        self.close_compare_pbutton.setMinimumSize(QtCore.QSize(81, 31))
        self.close_compare_pbutton.setMaximumSize(QtCore.QSize(81, 31))
        self.close_compare_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_compare_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.close_compare_pbutton.setObjectName("close_compare_pbutton")
        self.bottom_layout.addWidget(self.close_compare_pbutton)
        self.compare_widget_layout.addLayout(self.bottom_layout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.compare_widget_layout.addItem(spacerItem2)
        compare_window.setCentralWidget(self.compare_widget)

        self.retranslateUi(compare_window)
        self.plane_cbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(compare_window)

    def retranslateUi(self, compare_window):
        _translate = QtCore.QCoreApplication.translate
        compare_window.setWindowTitle(_translate("compare_window", "Plan Comparison Tool"))
        self.disSegm_cbox.setText(_translate("compare_window", "Disable segmentation"))
        self.disCT_cbox.setText(_translate("compare_window", "Disable CT"))
        self.disDose_cbox.setText(_translate("compare_window", "Disable dose"))
        self.disDoseCon_cbox.setText(_translate("compare_window", "Disable dose contours"))
        self.plane_label.setText(_translate("compare_window", "Plane"))
        self.plane_cbox.setCurrentText(_translate("compare_window", "axial"))
        self.plane_cbox.setItemText(0, _translate("compare_window", "axial"))
        self.plane_cbox.setItemText(1, _translate("compare_window", "coronal"))
        self.plane_cbox.setItemText(2, _translate("compare_window", "sagittal"))
        self.opacity_label.setText(_translate("compare_window", "Dose opacity"))
        self.slice_selection_label.setText(_translate("compare_window", "Slice"))
        self.segment_label.setText(_translate("compare_window", "Segment"))
        self.maximum_label.setText(_translate("compare_window", "Max"))
        self.minimum_label.setText(_translate("compare_window", "Min"))
        self.std_label.setText(_translate("compare_window", "Std"))
        self.mean_label.setText(_translate("compare_window", "Mean"))
        self.joint_dvh_pbutton.setText(_translate("compare_window", "Show joint DVH"))
        self.joint_ntcp_pbutton.setText(_translate("compare_window", "Show joint NTCP"))
        self.close_compare_pbutton.setText(_translate("compare_window", "Close"))
