# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plan_creation_window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plan_creation_window(object):
    def setupUi(self, plan_creation_window):
        plan_creation_window.setObjectName("plan_creation_window")
        plan_creation_window.setWindowModality(QtCore.Qt.ApplicationModal)
        plan_creation_window.resize(920, 680)
        plan_creation_window.setMinimumSize(QtCore.QSize(920, 680))
        plan_creation_window.setMaximumSize(QtCore.QSize(920, 680))
        plan_creation_window.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.body_widget = QtWidgets.QWidget(plan_creation_window)
        self.body_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 0px solid;")
        self.body_widget.setObjectName("body_widget")
        self.close_plan_pbutton = QtWidgets.QPushButton(self.body_widget)
        self.close_plan_pbutton.setGeometry(QtCore.QRect(840, 640, 71, 31))
        self.close_plan_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_plan_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.close_plan_pbutton.setObjectName("close_plan_pbutton")
        self.create_plan_pbutton = QtWidgets.QPushButton(self.body_widget)
        self.create_plan_pbutton.setGeometry(QtCore.QRect(760, 640, 71, 31))
        self.create_plan_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_plan_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.create_plan_pbutton.setObjectName("create_plan_pbutton")
        self.scroll_creator = QtWidgets.QScrollArea(self.body_widget)
        self.scroll_creator.setGeometry(QtCore.QRect(0, 0, 920, 591))
        self.scroll_creator.setWidgetResizable(True)
        self.scroll_creator.setObjectName("scroll_creator")
        self.scroll_creator_content = QtWidgets.QWidget()
        self.scroll_creator_content.setGeometry(QtCore.QRect(0, 0, 906, 813))
        self.scroll_creator_content.setObjectName("scroll_creator_content")
        self.scroll_creator_content_layout = QtWidgets.QVBoxLayout(self.scroll_creator_content)
        self.scroll_creator_content_layout.setContentsMargins(10, 10, 10, 10)
        self.scroll_creator_content_layout.setSpacing(0)
        self.scroll_creator_content_layout.setObjectName("scroll_creator_content_layout")
        self.creator_content_layout = QtWidgets.QVBoxLayout()
        self.creator_content_layout.setObjectName("creator_content_layout")
        self.creator_content_top_labels_layout = QtWidgets.QHBoxLayout()
        self.creator_content_top_labels_layout.setObjectName("creator_content_top_labels_layout")
        self.plan_ledit_vertical_layout = QtWidgets.QVBoxLayout()
        self.plan_ledit_vertical_layout.setSpacing(10)
        self.plan_ledit_vertical_layout.setObjectName("plan_ledit_vertical_layout")
        self.plan_label = QtWidgets.QLabel(self.scroll_creator_content)
        self.plan_label.setMinimumSize(QtCore.QSize(349, 25))
        self.plan_label.setMaximumSize(QtCore.QSize(349, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plan_label.setFont(font)
        self.plan_label.setStyleSheet("border: 0px solid;")
        self.plan_label.setObjectName("plan_label")
        self.plan_ledit_vertical_layout.addWidget(self.plan_label)
        self.plan_ledit_layout = QtWidgets.QHBoxLayout()
        self.plan_ledit_layout.setSpacing(5)
        self.plan_ledit_layout.setObjectName("plan_ledit_layout")
        self.plan_ledit = QtWidgets.QLineEdit(self.scroll_creator_content)
        self.plan_ledit.setMinimumSize(QtCore.QSize(349, 30))
        self.plan_ledit.setMaximumSize(QtCore.QSize(349, 30))
        self.plan_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.plan_ledit.setObjectName("plan_ledit")
        self.plan_ledit_layout.addWidget(self.plan_ledit)
        self.plan_ledit_vertical_layout.addLayout(self.plan_ledit_layout)
        self.creator_content_top_labels_layout.addLayout(self.plan_ledit_vertical_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.creator_content_top_labels_layout.addItem(spacerItem)
        self.ref_plan_vertical_layout = QtWidgets.QVBoxLayout()
        self.ref_plan_vertical_layout.setSpacing(10)
        self.ref_plan_vertical_layout.setObjectName("ref_plan_vertical_layout")
        self.ref_plan_label = QtWidgets.QLabel(self.scroll_creator_content)
        self.ref_plan_label.setMinimumSize(QtCore.QSize(318, 25))
        self.ref_plan_label.setMaximumSize(QtCore.QSize(318, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ref_plan_label.setFont(font)
        self.ref_plan_label.setStyleSheet("border: 0px solid;")
        self.ref_plan_label.setObjectName("ref_plan_label")
        self.ref_plan_vertical_layout.addWidget(self.ref_plan_label)
        self.ref_plan_cbox = QtWidgets.QComboBox(self.scroll_creator_content)
        self.ref_plan_cbox.setMinimumSize(QtCore.QSize(318, 30))
        self.ref_plan_cbox.setMaximumSize(QtCore.QSize(318, 30))
        self.ref_plan_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ref_plan_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.ref_plan_cbox.setObjectName("ref_plan_cbox")
        self.ref_plan_cbox.addItem("")
        self.ref_plan_vertical_layout.addWidget(self.ref_plan_cbox)
        self.creator_content_top_labels_layout.addLayout(self.ref_plan_vertical_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.creator_content_top_labels_layout.addItem(spacerItem1)
        self.modality_vertical_layout = QtWidgets.QVBoxLayout()
        self.modality_vertical_layout.setSpacing(10)
        self.modality_vertical_layout.setObjectName("modality_vertical_layout")
        self.modality_label = QtWidgets.QLabel(self.scroll_creator_content)
        self.modality_label.setMinimumSize(QtCore.QSize(145, 25))
        self.modality_label.setMaximumSize(QtCore.QSize(163, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.modality_label.setFont(font)
        self.modality_label.setStyleSheet("border: 0px solid;")
        self.modality_label.setObjectName("modality_label")
        self.modality_vertical_layout.addWidget(self.modality_label)
        self.modality_cbox = QtWidgets.QComboBox(self.scroll_creator_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modality_cbox.sizePolicy().hasHeightForWidth())
        self.modality_cbox.setSizePolicy(sizePolicy)
        self.modality_cbox.setMinimumSize(QtCore.QSize(163, 30))
        self.modality_cbox.setMaximumSize(QtCore.QSize(163, 30))
        self.modality_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modality_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.modality_cbox.setObjectName("modality_cbox")
        self.modality_cbox.addItem("")
        self.modality_cbox.addItem("")
        self.modality_vertical_layout.addWidget(self.modality_cbox)
        self.creator_content_top_labels_layout.addLayout(self.modality_vertical_layout)
        self.creator_content_layout.addLayout(self.creator_content_top_labels_layout)
        self.creator_content_top_fields_layout = QtWidgets.QHBoxLayout()
        self.creator_content_top_fields_layout.setObjectName("creator_content_top_fields_layout")
        self.creator_content_layout.addLayout(self.creator_content_top_fields_layout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.creator_content_layout.addItem(spacerItem2)
        self.img_path_label = QtWidgets.QLabel(self.scroll_creator_content)
        self.img_path_label.setMinimumSize(QtCore.QSize(0, 25))
        self.img_path_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.img_path_label.setFont(font)
        self.img_path_label.setStyleSheet("border: 0px solid;")
        self.img_path_label.setObjectName("img_path_label")
        self.creator_content_layout.addWidget(self.img_path_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.creator_content_layout.addItem(spacerItem3)
        self.img_path_layout = QtWidgets.QHBoxLayout()
        self.img_path_layout.setObjectName("img_path_layout")
        self.img_path_ledit = QtWidgets.QLineEdit(self.scroll_creator_content)
        self.img_path_ledit.setMinimumSize(QtCore.QSize(0, 30))
        self.img_path_ledit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.img_path_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.img_path_ledit.setObjectName("img_path_ledit")
        self.img_path_layout.addWidget(self.img_path_ledit)
        spacerItem4 = QtWidgets.QSpacerItem(5, 30, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.img_path_layout.addItem(spacerItem4)
        self.img_path_tbutton = QtWidgets.QToolButton(self.scroll_creator_content)
        self.img_path_tbutton.setMinimumSize(QtCore.QSize(30, 30))
        self.img_path_tbutton.setMaximumSize(QtCore.QSize(30, 30))
        self.img_path_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.img_path_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/black_icons/icons_black/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.img_path_tbutton.setIcon(icon)
        self.img_path_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.img_path_tbutton.setObjectName("img_path_tbutton")
        self.img_path_layout.addWidget(self.img_path_tbutton)
        self.creator_content_layout.addLayout(self.img_path_layout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.creator_content_layout.addItem(spacerItem5)
        self.dose_path_label = QtWidgets.QLabel(self.scroll_creator_content)
        self.dose_path_label.setMinimumSize(QtCore.QSize(0, 25))
        self.dose_path_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dose_path_label.setFont(font)
        self.dose_path_label.setStyleSheet("border: 0px solid;")
        self.dose_path_label.setObjectName("dose_path_label")
        self.creator_content_layout.addWidget(self.dose_path_label)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.creator_content_layout.addItem(spacerItem6)
        self.dose_path_layout = QtWidgets.QHBoxLayout()
        self.dose_path_layout.setObjectName("dose_path_layout")
        self.dose_path_ledit = QtWidgets.QLineEdit(self.scroll_creator_content)
        self.dose_path_ledit.setMinimumSize(QtCore.QSize(0, 30))
        self.dose_path_ledit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dose_path_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.dose_path_ledit.setObjectName("dose_path_ledit")
        self.dose_path_layout.addWidget(self.dose_path_ledit)
        spacerItem7 = QtWidgets.QSpacerItem(5, 30, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.dose_path_layout.addItem(spacerItem7)
        self.dose_path_tbutton = QtWidgets.QToolButton(self.scroll_creator_content)
        self.dose_path_tbutton.setMinimumSize(QtCore.QSize(30, 30))
        self.dose_path_tbutton.setMaximumSize(QtCore.QSize(30, 30))
        self.dose_path_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dose_path_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.dose_path_tbutton.setIcon(icon)
        self.dose_path_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.dose_path_tbutton.setObjectName("dose_path_tbutton")
        self.dose_path_layout.addWidget(self.dose_path_tbutton)
        self.creator_content_layout.addLayout(self.dose_path_layout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.creator_content_layout.addItem(spacerItem8)
        self.dose_res_label = QtWidgets.QLabel(self.scroll_creator_content)
        self.dose_res_label.setMinimumSize(QtCore.QSize(0, 25))
        self.dose_res_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dose_res_label.setFont(font)
        self.dose_res_label.setStyleSheet("border: 0px solid;")
        self.dose_res_label.setObjectName("dose_res_label")
        self.creator_content_layout.addWidget(self.dose_res_label)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.creator_content_layout.addItem(spacerItem9)
        self.dose_res_layout = QtWidgets.QHBoxLayout()
        self.dose_res_layout.setObjectName("dose_res_layout")
        self.dose_res_sublabel_xyz = QtWidgets.QLabel(self.scroll_creator_content)
        self.dose_res_sublabel_xyz.setMinimumSize(QtCore.QSize(0, 30))
        self.dose_res_sublabel_xyz.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dose_res_sublabel_xyz.setStyleSheet("border: 0px solid;")
        self.dose_res_sublabel_xyz.setObjectName("dose_res_sublabel_xyz")
        self.dose_res_layout.addWidget(self.dose_res_sublabel_xyz)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.dose_res_layout.addItem(spacerItem10)
        self.dose_res_bracket_left = QtWidgets.QLabel(self.scroll_creator_content)
        self.dose_res_bracket_left.setMinimumSize(QtCore.QSize(0, 30))
        self.dose_res_bracket_left.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dose_res_bracket_left.setStyleSheet("border: 0px solid;")
        self.dose_res_bracket_left.setObjectName("dose_res_bracket_left")
        self.dose_res_layout.addWidget(self.dose_res_bracket_left)
        spacerItem11 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.dose_res_layout.addItem(spacerItem11)
        self.dose_res_ledit_x = QtWidgets.QLineEdit(self.scroll_creator_content)
        self.dose_res_ledit_x.setMinimumSize(QtCore.QSize(45, 30))
        self.dose_res_ledit_x.setMaximumSize(QtCore.QSize(45, 30))
        self.dose_res_ledit_x.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.dose_res_ledit_x.setAlignment(QtCore.Qt.AlignCenter)
        self.dose_res_ledit_x.setObjectName("dose_res_ledit_x")
        self.dose_res_layout.addWidget(self.dose_res_ledit_x)
        self.dose_res_comma_left = QtWidgets.QLabel(self.scroll_creator_content)
        self.dose_res_comma_left.setMinimumSize(QtCore.QSize(0, 30))
        self.dose_res_comma_left.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dose_res_comma_left.setStyleSheet("border: 0px solid;")
        self.dose_res_comma_left.setObjectName("dose_res_comma_left")
        self.dose_res_layout.addWidget(self.dose_res_comma_left)
        self.dose_res_ledit_y = QtWidgets.QLineEdit(self.scroll_creator_content)
        self.dose_res_ledit_y.setMinimumSize(QtCore.QSize(45, 30))
        self.dose_res_ledit_y.setMaximumSize(QtCore.QSize(45, 30))
        self.dose_res_ledit_y.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.dose_res_ledit_y.setAlignment(QtCore.Qt.AlignCenter)
        self.dose_res_ledit_y.setObjectName("dose_res_ledit_y")
        self.dose_res_layout.addWidget(self.dose_res_ledit_y)
        self.dose_res_comma_right = QtWidgets.QLabel(self.scroll_creator_content)
        self.dose_res_comma_right.setMinimumSize(QtCore.QSize(0, 30))
        self.dose_res_comma_right.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dose_res_comma_right.setStyleSheet("border: 0px solid;")
        self.dose_res_comma_right.setObjectName("dose_res_comma_right")
        self.dose_res_layout.addWidget(self.dose_res_comma_right)
        self.dose_res_ledit_z = QtWidgets.QLineEdit(self.scroll_creator_content)
        self.dose_res_ledit_z.setMinimumSize(QtCore.QSize(45, 30))
        self.dose_res_ledit_z.setMaximumSize(QtCore.QSize(45, 30))
        self.dose_res_ledit_z.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.dose_res_ledit_z.setAlignment(QtCore.Qt.AlignCenter)
        self.dose_res_ledit_z.setObjectName("dose_res_ledit_z")
        self.dose_res_layout.addWidget(self.dose_res_ledit_z)
        spacerItem12 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.dose_res_layout.addItem(spacerItem12)
        self.dose_res_bracket_right = QtWidgets.QLabel(self.scroll_creator_content)
        self.dose_res_bracket_right.setMinimumSize(QtCore.QSize(0, 30))
        self.dose_res_bracket_right.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dose_res_bracket_right.setStyleSheet("border: 0px solid;")
        self.dose_res_bracket_right.setObjectName("dose_res_bracket_right")
        self.dose_res_layout.addWidget(self.dose_res_bracket_right)
        spacerItem13 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dose_res_layout.addItem(spacerItem13)
        self.creator_content_layout.addLayout(self.dose_res_layout)
        spacerItem14 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.creator_content_layout.addItem(spacerItem14)
        self.components_label = QtWidgets.QLabel(self.scroll_creator_content)
        self.components_label.setMinimumSize(QtCore.QSize(0, 25))
        self.components_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.components_label.setFont(font)
        self.components_label.setObjectName("components_label")
        self.creator_content_layout.addWidget(self.components_label)
        spacerItem15 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.creator_content_layout.addItem(spacerItem15)
        self.components_lwidget = QtWidgets.QListWidget(self.scroll_creator_content)
        self.components_lwidget.setMinimumSize(QtCore.QSize(0, 200))
        self.components_lwidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.components_lwidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.components_lwidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.components_lwidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.components_lwidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.components_lwidget.setObjectName("components_lwidget")
        self.creator_content_layout.addWidget(self.components_lwidget)
        spacerItem16 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.creator_content_layout.addItem(spacerItem16)
        self.components_button_layout = QtWidgets.QHBoxLayout()
        self.components_button_layout.setObjectName("components_button_layout")
        self.components_plus_tbutton = QtWidgets.QToolButton(self.scroll_creator_content)
        self.components_plus_tbutton.setMinimumSize(QtCore.QSize(30, 30))
        self.components_plus_tbutton.setMaximumSize(QtCore.QSize(30, 30))
        self.components_plus_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.components_plus_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/black_icons/icons_black/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.components_plus_tbutton.setIcon(icon1)
        self.components_plus_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.components_plus_tbutton.setObjectName("components_plus_tbutton")
        self.components_button_layout.addWidget(self.components_plus_tbutton)
        spacerItem17 = QtWidgets.QSpacerItem(5, 30, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.components_button_layout.addItem(spacerItem17)
        self.components_minus_tbutton = QtWidgets.QToolButton(self.scroll_creator_content)
        self.components_minus_tbutton.setMinimumSize(QtCore.QSize(30, 30))
        self.components_minus_tbutton.setMaximumSize(QtCore.QSize(30, 30))
        self.components_minus_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.components_minus_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/black_icons/icons_black/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.components_minus_tbutton.setIcon(icon2)
        self.components_minus_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.components_minus_tbutton.setObjectName("components_minus_tbutton")
        self.components_button_layout.addWidget(self.components_minus_tbutton)
        spacerItem18 = QtWidgets.QSpacerItem(5, 30, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.components_button_layout.addItem(spacerItem18)
        self.components_edit_tbutton = QtWidgets.QToolButton(self.scroll_creator_content)
        self.components_edit_tbutton.setMinimumSize(QtCore.QSize(30, 30))
        self.components_edit_tbutton.setMaximumSize(QtCore.QSize(30, 30))
        self.components_edit_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.components_edit_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/black_icons/icons_black/edit-3.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.components_edit_tbutton.setIcon(icon3)
        self.components_edit_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.components_edit_tbutton.setObjectName("components_edit_tbutton")
        self.components_button_layout.addWidget(self.components_edit_tbutton)
        spacerItem19 = QtWidgets.QSpacerItem(0, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.components_button_layout.addItem(spacerItem19)
        self.creator_content_layout.addLayout(self.components_button_layout)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.creator_content_layout.addItem(spacerItem20)
        self.scroll_creator_content_layout.addLayout(self.creator_content_layout)
        self.scroll_creator.setWidget(self.scroll_creator_content)
        plan_creation_window.setCentralWidget(self.body_widget)

        self.retranslateUi(plan_creation_window)
        self.ref_plan_cbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(plan_creation_window)

    def retranslateUi(self, plan_creation_window):
        _translate = QtCore.QCoreApplication.translate
        plan_creation_window.setWindowTitle(_translate("plan_creation_window", "Plan Creator"))
        self.close_plan_pbutton.setText(_translate("plan_creation_window", "Close"))
        self.create_plan_pbutton.setText(_translate("plan_creation_window", "Create"))
        self.plan_label.setText(_translate("plan_creation_window", "Treatment plan label"))
        self.ref_plan_label.setText(_translate("plan_creation_window", "Reference plan"))
        self.ref_plan_cbox.setItemText(0, _translate("plan_creation_window", "None"))
        self.modality_label.setText(_translate("plan_creation_window", "Modality"))
        self.modality_cbox.setItemText(0, _translate("plan_creation_window", "photon"))
        self.modality_cbox.setItemText(1, _translate("plan_creation_window", "proton"))
        self.img_path_label.setText(_translate("plan_creation_window", "Imaging path"))
        self.img_path_tbutton.setToolTip(_translate("plan_creation_window", "Add the CT and segmentation data from a folder"))
        self.dose_path_label.setText(_translate("plan_creation_window", "Dose matrix path"))
        self.dose_path_tbutton.setToolTip(_translate("plan_creation_window", "Add the dose-influence matrix from a folder"))
        self.dose_res_label.setToolTip(_translate("plan_creation_window", "Size of the dose grid in [mm] per dimension"))
        self.dose_res_label.setText(_translate("plan_creation_window", "Dose grid resolution [mm]"))
        self.dose_res_sublabel_xyz.setText(_translate("plan_creation_window", "[x, y, z] : "))
        self.dose_res_bracket_left.setText(_translate("plan_creation_window", "["))
        self.dose_res_comma_left.setText(_translate("plan_creation_window", ","))
        self.dose_res_comma_right.setText(_translate("plan_creation_window", ","))
        self.dose_res_bracket_right.setText(_translate("plan_creation_window", "]"))
        self.components_label.setText(_translate("plan_creation_window", "Components"))
        self.components_lwidget.setSortingEnabled(True)
        self.components_plus_tbutton.setToolTip(_translate("plan_creation_window", "Add a component"))
        self.components_minus_tbutton.setToolTip(_translate("plan_creation_window", "Remove the selected component"))
        self.components_edit_tbutton.setToolTip(_translate("plan_creation_window", "Edit the selected component"))
