# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.setWindowModality(QtCore.Qt.ApplicationModal)
        settings_window.resize(730, 320)
        settings_window.setMinimumSize(QtCore.QSize(730, 320))
        settings_window.setMaximumSize(QtCore.QSize(730, 320))
        settings_window.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.settings_widget = QtWidgets.QWidget(settings_window)
        self.settings_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.settings_widget.setObjectName("settings_widget")
        self.general_settings_line = QtWidgets.QFrame(self.settings_widget)
        self.general_settings_line.setGeometry(QtCore.QRect(20, 50, 321, 2))
        self.general_settings_line.setMinimumSize(QtCore.QSize(0, 2))
        self.general_settings_line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.general_settings_line.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.general_settings_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.general_settings_line.setObjectName("general_settings_line")
        self.light_mode_cbox = QtWidgets.QComboBox(self.settings_widget)
        self.light_mode_cbox.setGeometry(QtCore.QRect(190, 140, 151, 31))
        self.light_mode_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.light_mode_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.light_mode_cbox.setObjectName("light_mode_cbox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/moon-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.light_mode_cbox.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/sun-2-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.light_mode_cbox.addItem(icon1, "")
        self.general_settings_label = QtWidgets.QLabel(self.settings_widget)
        self.general_settings_label.setGeometry(QtCore.QRect(20, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.general_settings_label.setFont(font)
        self.general_settings_label.setStyleSheet("border: 0px solid;")
        self.general_settings_label.setObjectName("general_settings_label")
        self.resolution_label = QtWidgets.QLabel(self.settings_widget)
        self.resolution_label.setGeometry(QtCore.QRect(40, 200, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resolution_label.setFont(font)
        self.resolution_label.setStyleSheet("border: 0px solid;")
        self.resolution_label.setObjectName("resolution_label")
        self.language_label = QtWidgets.QLabel(self.settings_widget)
        self.language_label.setGeometry(QtCore.QRect(40, 80, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.language_label.setFont(font)
        self.language_label.setStyleSheet("border: 0px solid;")
        self.language_label.setObjectName("language_label")
        self.language_cbox = QtWidgets.QComboBox(self.settings_widget)
        self.language_cbox.setGeometry(QtCore.QRect(190, 80, 151, 31))
        self.language_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.language_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.language_cbox.setObjectName("language_cbox")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/flag-for-flag-germany-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.language_cbox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/united-kingdom-uk-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.language_cbox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/flag-for-flag-spain-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.language_cbox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/flag-for-flag-france-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.language_cbox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/flag-for-flag-italy-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.language_cbox.addItem(icon6, "")
        self.incl_dij_check = QtWidgets.QCheckBox(self.settings_widget)
        self.incl_dij_check.setGeometry(QtCore.QRect(410, 110, 231, 23))
        self.incl_dij_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.incl_dij_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.incl_dij_check.setObjectName("incl_dij_check")
        self.reset_settings_pbutton = QtWidgets.QPushButton(self.settings_widget)
        self.reset_settings_pbutton.setGeometry(QtCore.QRect(560, 280, 71, 31))
        self.reset_settings_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_settings_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.reset_settings_pbutton.setObjectName("reset_settings_pbutton")
        self.light_model_label = QtWidgets.QLabel(self.settings_widget)
        self.light_model_label.setGeometry(QtCore.QRect(40, 140, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.light_model_label.setFont(font)
        self.light_model_label.setStyleSheet("border: 0px solid;")
        self.light_model_label.setObjectName("light_model_label")
        self.incl_img_data_check = QtWidgets.QCheckBox(self.settings_widget)
        self.incl_img_data_check.setGeometry(QtCore.QRect(410, 80, 231, 23))
        self.incl_img_data_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.incl_img_data_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.incl_img_data_check.setObjectName("incl_img_data_check")
        self.resolution_cbox = QtWidgets.QComboBox(self.settings_widget)
        self.resolution_cbox.setGeometry(QtCore.QRect(190, 200, 151, 31))
        self.resolution_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resolution_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.resolution_cbox.setObjectName("resolution_cbox")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/green_icons/icons_green/eye.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resolution_cbox.addItem(icon7, "")
        self.resolution_cbox.setItemText(0, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/lightblue_icons/icons_lightblue/eye.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resolution_cbox.addItem(icon8, "")
        self.resolution_cbox.addItem(icon8, "")
        self.resolution_cbox.addItem(icon8, "")
        self.resolution_cbox.addItem(icon8, "")
        self.resolution_cbox.addItem(icon8, "")
        self.resolution_cbox.addItem(icon8, "")
        self.resolution_cbox.addItem(icon8, "")
        self.incl_model_data_check = QtWidgets.QCheckBox(self.settings_widget)
        self.incl_model_data_check.setGeometry(QtCore.QRect(410, 140, 231, 23))
        self.incl_model_data_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.incl_model_data_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.incl_model_data_check.setObjectName("incl_model_data_check")
        self.save_tpi_label = QtWidgets.QLabel(self.settings_widget)
        self.save_tpi_label.setGeometry(QtCore.QRect(390, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.save_tpi_label.setFont(font)
        self.save_tpi_label.setStyleSheet("border: 0px solid;")
        self.save_tpi_label.setObjectName("save_tpi_label")
        self.save_tpi_line = QtWidgets.QFrame(self.settings_widget)
        self.save_tpi_line.setGeometry(QtCore.QRect(390, 50, 321, 2))
        self.save_tpi_line.setMinimumSize(QtCore.QSize(0, 2))
        self.save_tpi_line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.save_tpi_line.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.save_tpi_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.save_tpi_line.setObjectName("save_tpi_line")
        self.save_settings_pbutton = QtWidgets.QPushButton(self.settings_widget)
        self.save_settings_pbutton.setGeometry(QtCore.QRect(640, 280, 71, 31))
        self.save_settings_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_settings_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.save_settings_pbutton.setObjectName("save_settings_pbutton")
        self.light_mode_cbox.raise_()
        self.general_settings_label.raise_()
        self.resolution_label.raise_()
        self.language_label.raise_()
        self.language_cbox.raise_()
        self.incl_dij_check.raise_()
        self.reset_settings_pbutton.raise_()
        self.light_model_label.raise_()
        self.incl_img_data_check.raise_()
        self.resolution_cbox.raise_()
        self.incl_model_data_check.raise_()
        self.save_tpi_label.raise_()
        self.save_tpi_line.raise_()
        self.save_settings_pbutton.raise_()
        self.general_settings_line.raise_()
        settings_window.setCentralWidget(self.settings_widget)

        self.retranslateUi(settings_window)
        self.language_cbox.setCurrentIndex(1)
        self.resolution_cbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "Settings"))
        self.light_mode_cbox.setItemText(0, _translate("settings_window", "Dark"))
        self.light_mode_cbox.setItemText(1, _translate("settings_window", "Light"))
        self.general_settings_label.setText(_translate("settings_window", "General"))
        self.resolution_label.setText(_translate("settings_window", "Display resolution"))
        self.language_label.setText(_translate("settings_window", "Language"))
        self.language_cbox.setItemText(0, _translate("settings_window", "Deutsch"))
        self.language_cbox.setItemText(1, _translate("settings_window", "English"))
        self.language_cbox.setItemText(2, _translate("settings_window", "Español"))
        self.language_cbox.setItemText(3, _translate("settings_window", "Français"))
        self.language_cbox.setItemText(4, _translate("settings_window", "Italiano"))
        self.incl_dij_check.setText(_translate("settings_window", "Include dose-influence matrix"))
        self.reset_settings_pbutton.setText(_translate("settings_window", "Reset"))
        self.light_model_label.setText(_translate("settings_window", "Light mode"))
        self.incl_img_data_check.setText(_translate("settings_window", "Include CT/segmentation data"))
        self.resolution_cbox.setItemText(1, _translate("settings_window", "1024x768"))
        self.resolution_cbox.setItemText(2, _translate("settings_window", "1280x720"))
        self.resolution_cbox.setItemText(3, _translate("settings_window", "1280x1024"))
        self.resolution_cbox.setItemText(4, _translate("settings_window", "1366x768"))
        self.resolution_cbox.setItemText(5, _translate("settings_window", "1440x900"))
        self.resolution_cbox.setItemText(6, _translate("settings_window", "1920x1080"))
        self.resolution_cbox.setItemText(7, _translate("settings_window", "2560x1440"))
        self.incl_model_data_check.setText(_translate("settings_window", "Include model training data"))
        self.save_tpi_label.setText(_translate("settings_window", "Save TPI"))
        self.save_settings_pbutton.setText(_translate("settings_window", "Save"))
