# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualization_window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vis_window(object):
    def setupUi(self, vis_window):
        vis_window.setObjectName("vis_window")
        vis_window.setWindowModality(QtCore.Qt.ApplicationModal)
        vis_window.resize(920, 680)
        vis_window.setMinimumSize(QtCore.QSize(920, 680))
        vis_window.setMaximumSize(QtCore.QSize(2560, 1440))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/logo_white_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        vis_window.setWindowIcon(icon)
        self.central_widget = QtWidgets.QWidget(vis_window)
        self.central_widget.setStyleSheet("color: rgb(211, 215, 207);\n"
"background-color: rgb(0, 0, 0);")
        self.central_widget.setObjectName("central_widget")
        self.central_widget_layout = QtWidgets.QVBoxLayout(self.central_widget)
        self.central_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.central_widget_layout.setSpacing(0)
        self.central_widget_layout.setObjectName("central_widget_layout")
        self.body_layout = QtWidgets.QVBoxLayout()
        self.body_layout.setObjectName("body_layout")
        self.widget_layout = QtWidgets.QGridLayout()
        self.widget_layout.setSpacing(0)
        self.widget_layout.setObjectName("widget_layout")
        self.meta_settings_right_widget = QtWidgets.QWidget(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_settings_right_widget.sizePolicy().hasHeightForWidth())
        self.meta_settings_right_widget.setSizePolicy(sizePolicy)
        self.meta_settings_right_widget.setMinimumSize(QtCore.QSize(333, 0))
        self.meta_settings_right_widget.setObjectName("meta_settings_right_widget")
        self.widget_layout.addWidget(self.meta_settings_right_widget, 0, 2, 1, 1)
        self.meta_settings_left_widget = QtWidgets.QWidget(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_settings_left_widget.sizePolicy().hasHeightForWidth())
        self.meta_settings_left_widget.setSizePolicy(sizePolicy)
        self.meta_settings_left_widget.setMinimumSize(QtCore.QSize(333, 0))
        self.meta_settings_left_widget.setObjectName("meta_settings_left_widget")
        self.widget_layout.addWidget(self.meta_settings_left_widget, 0, 0, 1, 1)
        self.categories_widget = QtWidgets.QTabWidget(self.central_widget)
        self.categories_widget.setMinimumSize(QtCore.QSize(916, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.categories_widget.setFont(font)
        self.categories_widget.setIconSize(QtCore.QSize(50, 50))
        self.categories_widget.setDocumentMode(True)
        self.categories_widget.setObjectName("categories_widget")
        self.tab_problem = QtWidgets.QWidget()
        self.tab_problem.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.tab_problem.setObjectName("tab_problem")
        self.tab_configuration_meta_layout = QtWidgets.QVBoxLayout(self.tab_problem)
        self.tab_configuration_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_configuration_meta_layout.setSpacing(0)
        self.tab_configuration_meta_layout.setObjectName("tab_configuration_meta_layout")
        self.tab_problem_layout = QtWidgets.QVBoxLayout()
        self.tab_problem_layout.setObjectName("tab_problem_layout")
        self.tab_problem_fields = QtWidgets.QTabWidget(self.tab_problem)
        self.tab_problem_fields.setObjectName("tab_problem_fields")
        self.comp_vals_widget = QtWidgets.QWidget()
        self.comp_vals_widget.setObjectName("comp_vals_widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.comp_vals_widget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.comp_vals_layout = QtWidgets.QVBoxLayout()
        self.comp_vals_layout.setObjectName("comp_vals_layout")
        self.comp_vals_top_layout = QtWidgets.QHBoxLayout()
        self.comp_vals_top_layout.setObjectName("comp_vals_top_layout")
        self.comp_vals_top_widget = QtWidgets.QWidget(self.comp_vals_widget)
        self.comp_vals_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.comp_vals_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.comp_vals_top_widget.setObjectName("comp_vals_top_widget")
        self.baseline_meta_layout_5 = QtWidgets.QVBoxLayout(self.comp_vals_top_widget)
        self.baseline_meta_layout_5.setContentsMargins(0, 0, 0, 0)
        self.baseline_meta_layout_5.setSpacing(0)
        self.baseline_meta_layout_5.setObjectName("baseline_meta_layout_5")
        self.comp_vals_top_widget_layout = QtWidgets.QVBoxLayout()
        self.comp_vals_top_widget_layout.setSpacing(0)
        self.comp_vals_top_widget_layout.setObjectName("comp_vals_top_widget_layout")
        self.baseline_meta_layout_5.addLayout(self.comp_vals_top_widget_layout)
        self.comp_vals_top_layout.addWidget(self.comp_vals_top_widget)
        self.comp_vals_layout.addLayout(self.comp_vals_top_layout)
        self.comp_vals_bottom_layout = QtWidgets.QHBoxLayout()
        self.comp_vals_bottom_layout.setObjectName("comp_vals_bottom_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.comp_vals_bottom_layout.addItem(spacerItem)
        self.open_comp_vals_pbutton = QtWidgets.QPushButton(self.comp_vals_widget)
        self.open_comp_vals_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_comp_vals_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_comp_vals_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_comp_vals_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_comp_vals_pbutton.setObjectName("open_comp_vals_pbutton")
        self.comp_vals_bottom_layout.addWidget(self.open_comp_vals_pbutton)
        self.comp_vals_layout.addLayout(self.comp_vals_bottom_layout)
        self.verticalLayout_11.addLayout(self.comp_vals_layout)
        self.tab_problem_fields.addTab(self.comp_vals_widget, "")
        self.outc_vals_widget = QtWidgets.QWidget()
        self.outc_vals_widget.setObjectName("outc_vals_widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.outc_vals_widget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.outc_vals_layout = QtWidgets.QVBoxLayout()
        self.outc_vals_layout.setObjectName("outc_vals_layout")
        self.outc_vals_top_layout = QtWidgets.QHBoxLayout()
        self.outc_vals_top_layout.setObjectName("outc_vals_top_layout")
        self.outc_vals_top_widget = QtWidgets.QWidget(self.outc_vals_widget)
        self.outc_vals_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.outc_vals_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.outc_vals_top_widget.setObjectName("outc_vals_top_widget")
        self.dvh_meta_layout_4 = QtWidgets.QVBoxLayout(self.outc_vals_top_widget)
        self.dvh_meta_layout_4.setContentsMargins(0, 0, 0, 0)
        self.dvh_meta_layout_4.setSpacing(0)
        self.dvh_meta_layout_4.setObjectName("dvh_meta_layout_4")
        self.outc_vals_top_widget_layout = QtWidgets.QVBoxLayout()
        self.outc_vals_top_widget_layout.setSpacing(0)
        self.outc_vals_top_widget_layout.setObjectName("outc_vals_top_widget_layout")
        self.dvh_meta_layout_4.addLayout(self.outc_vals_top_widget_layout)
        self.outc_vals_top_layout.addWidget(self.outc_vals_top_widget)
        self.outc_vals_layout.addLayout(self.outc_vals_top_layout)
        self.outc_vals_bottom_layout = QtWidgets.QHBoxLayout()
        self.outc_vals_bottom_layout.setObjectName("outc_vals_bottom_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.outc_vals_bottom_layout.addItem(spacerItem1)
        self.open_outc_vals_pbutton = QtWidgets.QPushButton(self.outc_vals_widget)
        self.open_outc_vals_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_outc_vals_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_outc_vals_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_outc_vals_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_outc_vals_pbutton.setObjectName("open_outc_vals_pbutton")
        self.outc_vals_bottom_layout.addWidget(self.open_outc_vals_pbutton)
        self.outc_vals_layout.addLayout(self.outc_vals_bottom_layout)
        self.verticalLayout_12.addLayout(self.outc_vals_layout)
        self.tab_problem_fields.addTab(self.outc_vals_widget, "")
        self.feat_vals_widget = QtWidgets.QWidget()
        self.feat_vals_widget.setObjectName("feat_vals_widget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.feat_vals_widget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.feat_vals_layout = QtWidgets.QVBoxLayout()
        self.feat_vals_layout.setObjectName("feat_vals_layout")
        self.feat_vals_top_layout = QtWidgets.QHBoxLayout()
        self.feat_vals_top_layout.setObjectName("feat_vals_top_layout")
        self.feat_vals_top_widget = QtWidgets.QWidget(self.feat_vals_widget)
        self.feat_vals_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.feat_vals_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.feat_vals_top_widget.setObjectName("feat_vals_top_widget")
        self.baseline_meta_layout_6 = QtWidgets.QVBoxLayout(self.feat_vals_top_widget)
        self.baseline_meta_layout_6.setContentsMargins(0, 0, 0, 0)
        self.baseline_meta_layout_6.setSpacing(0)
        self.baseline_meta_layout_6.setObjectName("baseline_meta_layout_6")
        self.feat_vals_top_widget_layout = QtWidgets.QVBoxLayout()
        self.feat_vals_top_widget_layout.setSpacing(0)
        self.feat_vals_top_widget_layout.setObjectName("feat_vals_top_widget_layout")
        self.baseline_meta_layout_6.addLayout(self.feat_vals_top_widget_layout)
        self.feat_vals_top_layout.addWidget(self.feat_vals_top_widget)
        self.feat_vals_layout.addLayout(self.feat_vals_top_layout)
        self.feat_vals_bottom_layout = QtWidgets.QHBoxLayout()
        self.feat_vals_bottom_layout.setObjectName("feat_vals_bottom_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.feat_vals_bottom_layout.addItem(spacerItem2)
        self.open_feat_vals_pbutton = QtWidgets.QPushButton(self.feat_vals_widget)
        self.open_feat_vals_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_feat_vals_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_feat_vals_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_feat_vals_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_feat_vals_pbutton.setObjectName("open_feat_vals_pbutton")
        self.feat_vals_bottom_layout.addWidget(self.open_feat_vals_pbutton)
        self.feat_vals_layout.addLayout(self.feat_vals_bottom_layout)
        self.verticalLayout_13.addLayout(self.feat_vals_layout)
        self.tab_problem_fields.addTab(self.feat_vals_widget, "")
        self.tab_problem_layout.addWidget(self.tab_problem_fields)
        self.tab_configuration_meta_layout.addLayout(self.tab_problem_layout)
        self.categories_widget.addTab(self.tab_problem, "")
        self.tab_model = QtWidgets.QWidget()
        self.tab_model.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.tab_model.setObjectName("tab_model")
        self.tab_optimization_meta_layout = QtWidgets.QVBoxLayout(self.tab_model)
        self.tab_optimization_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_optimization_meta_layout.setSpacing(0)
        self.tab_optimization_meta_layout.setObjectName("tab_optimization_meta_layout")
        self.tab_model_layout = QtWidgets.QVBoxLayout()
        self.tab_model_layout.setObjectName("tab_model_layout")
        self.tab_model_fields = QtWidgets.QTabWidget(self.tab_model)
        self.tab_model_fields.setObjectName("tab_model_fields")
        self.metrics_widget = QtWidgets.QWidget()
        self.metrics_widget.setObjectName("metrics_widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.metrics_widget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.metrics_layout = QtWidgets.QVBoxLayout()
        self.metrics_layout.setObjectName("metrics_layout")
        self.metrics_top_layout = QtWidgets.QHBoxLayout()
        self.metrics_top_layout.setObjectName("metrics_top_layout")
        self.metrics_top_widget = QtWidgets.QWidget(self.metrics_widget)
        self.metrics_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.metrics_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.metrics_top_widget.setObjectName("metrics_top_widget")
        self.baseline_meta_layout_4 = QtWidgets.QVBoxLayout(self.metrics_top_widget)
        self.baseline_meta_layout_4.setContentsMargins(0, 0, 0, 0)
        self.baseline_meta_layout_4.setSpacing(0)
        self.baseline_meta_layout_4.setObjectName("baseline_meta_layout_4")
        self.metrics_top_widget_layout = QtWidgets.QVBoxLayout()
        self.metrics_top_widget_layout.setSpacing(0)
        self.metrics_top_widget_layout.setObjectName("metrics_top_widget_layout")
        self.baseline_meta_layout_4.addLayout(self.metrics_top_widget_layout)
        self.metrics_top_layout.addWidget(self.metrics_top_widget)
        self.metrics_layout.addLayout(self.metrics_top_layout)
        self.metrics_bottom_layout = QtWidgets.QHBoxLayout()
        self.metrics_bottom_layout.setObjectName("metrics_bottom_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.metrics_bottom_layout.addItem(spacerItem3)
        self.open_metrics_graphs_pbutton = QtWidgets.QPushButton(self.metrics_widget)
        self.open_metrics_graphs_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_metrics_graphs_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_metrics_graphs_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_metrics_graphs_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_metrics_graphs_pbutton.setObjectName("open_metrics_graphs_pbutton")
        self.metrics_bottom_layout.addWidget(self.open_metrics_graphs_pbutton)
        self.open_metrics_tables_pbutton = QtWidgets.QPushButton(self.metrics_widget)
        self.open_metrics_tables_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_metrics_tables_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_metrics_tables_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_metrics_tables_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_metrics_tables_pbutton.setObjectName("open_metrics_tables_pbutton")
        self.metrics_bottom_layout.addWidget(self.open_metrics_tables_pbutton)
        self.metrics_layout.addLayout(self.metrics_bottom_layout)
        self.verticalLayout_9.addLayout(self.metrics_layout)
        self.tab_model_fields.addTab(self.metrics_widget, "")
        self.perm_widget = QtWidgets.QWidget()
        self.perm_widget.setObjectName("perm_widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.perm_widget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.perm_layout = QtWidgets.QVBoxLayout()
        self.perm_layout.setObjectName("perm_layout")
        self.perm_top_layout = QtWidgets.QHBoxLayout()
        self.perm_top_layout.setObjectName("perm_top_layout")
        self.perm_top_widget = QtWidgets.QWidget(self.perm_widget)
        self.perm_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.perm_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.perm_top_widget.setObjectName("perm_top_widget")
        self.dvh_meta_layout_3 = QtWidgets.QVBoxLayout(self.perm_top_widget)
        self.dvh_meta_layout_3.setContentsMargins(0, 0, 0, 0)
        self.dvh_meta_layout_3.setSpacing(0)
        self.dvh_meta_layout_3.setObjectName("dvh_meta_layout_3")
        self.perm_top_widget_layout = QtWidgets.QVBoxLayout()
        self.perm_top_widget_layout.setSpacing(0)
        self.perm_top_widget_layout.setObjectName("perm_top_widget_layout")
        self.dvh_meta_layout_3.addLayout(self.perm_top_widget_layout)
        self.perm_top_layout.addWidget(self.perm_top_widget)
        self.perm_layout.addLayout(self.perm_top_layout)
        self.perm_bottom_layout = QtWidgets.QHBoxLayout()
        self.perm_bottom_layout.setObjectName("perm_bottom_layout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.perm_bottom_layout.addItem(spacerItem4)
        self.open_perm_pbutton = QtWidgets.QPushButton(self.perm_widget)
        self.open_perm_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_perm_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_perm_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_perm_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_perm_pbutton.setObjectName("open_perm_pbutton")
        self.perm_bottom_layout.addWidget(self.open_perm_pbutton)
        self.perm_layout.addLayout(self.perm_bottom_layout)
        self.verticalLayout_10.addLayout(self.perm_layout)
        self.tab_model_fields.addTab(self.perm_widget, "")
        self.tab_model_layout.addWidget(self.tab_model_fields)
        self.tab_optimization_meta_layout.addLayout(self.tab_model_layout)
        self.categories_widget.addTab(self.tab_model, "")
        self.tab_plan = QtWidgets.QWidget()
        self.tab_plan.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.tab_plan.setObjectName("tab_plan")
        self.tab_evaluation_meta_layout = QtWidgets.QVBoxLayout(self.tab_plan)
        self.tab_evaluation_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_evaluation_meta_layout.setSpacing(0)
        self.tab_evaluation_meta_layout.setObjectName("tab_evaluation_meta_layout")
        self.tab_plan_layout = QtWidgets.QVBoxLayout()
        self.tab_plan_layout.setObjectName("tab_plan_layout")
        self.tab_plan_fields = QtWidgets.QTabWidget(self.tab_plan)
        self.tab_plan_fields.setObjectName("tab_plan_fields")
        self.image_widget = QtWidgets.QWidget()
        self.image_widget.setObjectName("image_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.image_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_layout = QtWidgets.QVBoxLayout()
        self.image_layout.setObjectName("image_layout")
        self.image_top_layout = QtWidgets.QHBoxLayout()
        self.image_top_layout.setObjectName("image_top_layout")
        self.image_top_widget = QtWidgets.QWidget(self.image_widget)
        self.image_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.image_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.image_top_widget.setObjectName("image_top_widget")
        self.baseline_meta_layout = QtWidgets.QVBoxLayout(self.image_top_widget)
        self.baseline_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.baseline_meta_layout.setSpacing(0)
        self.baseline_meta_layout.setObjectName("baseline_meta_layout")
        self.image_top_widget_layout = QtWidgets.QVBoxLayout()
        self.image_top_widget_layout.setSpacing(0)
        self.image_top_widget_layout.setObjectName("image_top_widget_layout")
        self.baseline_meta_layout.addLayout(self.image_top_widget_layout)
        self.image_top_layout.addWidget(self.image_top_widget)
        self.image_layout.addLayout(self.image_top_layout)
        self.image_bottom_layout = QtWidgets.QHBoxLayout()
        self.image_bottom_layout.setObjectName("image_bottom_layout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.image_bottom_layout.addItem(spacerItem5)
        self.open_image_pbutton = QtWidgets.QPushButton(self.image_widget)
        self.open_image_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_image_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_image_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_image_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_image_pbutton.setObjectName("open_image_pbutton")
        self.image_bottom_layout.addWidget(self.open_image_pbutton)
        self.image_layout.addLayout(self.image_bottom_layout)
        self.verticalLayout_3.addLayout(self.image_layout)
        self.tab_plan_fields.addTab(self.image_widget, "")
        self.dvh_widget = QtWidgets.QWidget()
        self.dvh_widget.setObjectName("dvh_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dvh_widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dvh_layout = QtWidgets.QVBoxLayout()
        self.dvh_layout.setObjectName("dvh_layout")
        self.dvh_top_layout = QtWidgets.QHBoxLayout()
        self.dvh_top_layout.setObjectName("dvh_top_layout")
        self.dvh_top_widget = QtWidgets.QWidget(self.dvh_widget)
        self.dvh_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.dvh_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.dvh_top_widget.setObjectName("dvh_top_widget")
        self.dvh_meta_layout = QtWidgets.QVBoxLayout(self.dvh_top_widget)
        self.dvh_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.dvh_meta_layout.setSpacing(0)
        self.dvh_meta_layout.setObjectName("dvh_meta_layout")
        self.dvh_top_widget_layout = QtWidgets.QVBoxLayout()
        self.dvh_top_widget_layout.setSpacing(0)
        self.dvh_top_widget_layout.setObjectName("dvh_top_widget_layout")
        self.dvh_meta_layout.addLayout(self.dvh_top_widget_layout)
        self.dvh_top_layout.addWidget(self.dvh_top_widget)
        self.dvh_layout.addLayout(self.dvh_top_layout)
        self.dvh_bottom_layout = QtWidgets.QHBoxLayout()
        self.dvh_bottom_layout.setObjectName("dvh_bottom_layout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dvh_bottom_layout.addItem(spacerItem6)
        self.open_dvh_pbutton = QtWidgets.QPushButton(self.dvh_widget)
        self.open_dvh_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_dvh_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_dvh_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_dvh_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_dvh_pbutton.setObjectName("open_dvh_pbutton")
        self.dvh_bottom_layout.addWidget(self.open_dvh_pbutton)
        self.dvh_layout.addLayout(self.dvh_bottom_layout)
        self.verticalLayout_6.addLayout(self.dvh_layout)
        self.tab_plan_fields.addTab(self.dvh_widget, "")
        self.ind_widget = QtWidgets.QWidget()
        self.ind_widget.setObjectName("ind_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ind_widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ind_layout = QtWidgets.QVBoxLayout()
        self.ind_layout.setObjectName("ind_layout")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ind_layout.addItem(spacerItem7)
        self.ind_bottom_layout = QtWidgets.QHBoxLayout()
        self.ind_bottom_layout.setObjectName("ind_bottom_layout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ind_bottom_layout.addItem(spacerItem8)
        self.open_ind_pbutton = QtWidgets.QPushButton(self.ind_widget)
        self.open_ind_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_ind_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_ind_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_ind_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_ind_pbutton.setObjectName("open_ind_pbutton")
        self.ind_bottom_layout.addWidget(self.open_ind_pbutton)
        self.ind_layout.addLayout(self.ind_bottom_layout)
        self.verticalLayout_5.addLayout(self.ind_layout)
        self.tab_plan_fields.addTab(self.ind_widget, "")
        self.tab_plan_layout.addWidget(self.tab_plan_fields)
        self.tab_evaluation_meta_layout.addLayout(self.tab_plan_layout)
        self.categories_widget.addTab(self.tab_plan, "")
        self.widget_layout.addWidget(self.categories_widget, 4, 0, 1, 3)
        self.logo_widget = QtWidgets.QWidget(self.central_widget)
        self.logo_widget.setMinimumSize(QtCore.QSize(250, 210))
        self.logo_widget.setMaximumSize(QtCore.QSize(250, 210))
        self.logo_widget.setObjectName("logo_widget")
        self.logo_widget_layout = QtWidgets.QHBoxLayout(self.logo_widget)
        self.logo_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.logo_widget_layout.setObjectName("logo_widget_layout")
        self.logo_pixmap = QtWidgets.QLabel(self.logo_widget)
        self.logo_pixmap.setMaximumSize(QtCore.QSize(210, 210))
        self.logo_pixmap.setPixmap(QtGui.QPixmap(":/Logo/logo_white_square.png"))
        self.logo_pixmap.setScaledContents(True)
        self.logo_pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_pixmap.setObjectName("logo_pixmap")
        self.logo_widget_layout.addWidget(self.logo_pixmap)
        self.widget_layout.addWidget(self.logo_widget, 0, 1, 1, 1)
        self.widget_layout.setColumnStretch(0, 1)
        self.body_layout.addLayout(self.widget_layout)
        self.bottom_widget = QtWidgets.QWidget(self.central_widget)
        self.bottom_widget.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.bottom_widget.setObjectName("bottom_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bottom_widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bottom_widget_layout = QtWidgets.QHBoxLayout()
        self.bottom_widget_layout.setContentsMargins(10, 10, 10, 10)
        self.bottom_widget_layout.setObjectName("bottom_widget_layout")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_widget_layout.addItem(spacerItem9)
        self.close_visualizer_pbutton = QtWidgets.QPushButton(self.bottom_widget)
        self.close_visualizer_pbutton.setMinimumSize(QtCore.QSize(71, 31))
        self.close_visualizer_pbutton.setMaximumSize(QtCore.QSize(71, 31))
        self.close_visualizer_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_visualizer_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.close_visualizer_pbutton.setObjectName("close_visualizer_pbutton")
        self.bottom_widget_layout.addWidget(self.close_visualizer_pbutton)
        self.horizontalLayout_4.addLayout(self.bottom_widget_layout)
        self.body_layout.addWidget(self.bottom_widget)
        self.central_widget_layout.addLayout(self.body_layout)
        vis_window.setCentralWidget(self.central_widget)

        self.retranslateUi(vis_window)
        self.categories_widget.setCurrentIndex(0)
        self.tab_problem_fields.setCurrentIndex(0)
        self.tab_model_fields.setCurrentIndex(0)
        self.tab_plan_fields.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(vis_window)

    def retranslateUi(self, vis_window):
        _translate = QtCore.QCoreApplication.translate
        vis_window.setWindowTitle(_translate("vis_window", "pyanno4rt"))
        self.open_comp_vals_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_problem_fields.setTabText(self.tab_problem_fields.indexOf(self.comp_vals_widget), _translate("vis_window", "Iterative component values"))
        self.open_outc_vals_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_problem_fields.setTabText(self.tab_problem_fields.indexOf(self.outc_vals_widget), _translate("vis_window", "Iterative outcome values"))
        self.open_feat_vals_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_problem_fields.setTabText(self.tab_problem_fields.indexOf(self.feat_vals_widget), _translate("vis_window", "Iterative feature values"))
        self.categories_widget.setTabText(self.categories_widget.indexOf(self.tab_problem), _translate("vis_window", "Optimization problem analysis"))
        self.open_metrics_graphs_pbutton.setText(_translate("vis_window", "Open static plot (gr.)"))
        self.open_metrics_tables_pbutton.setText(_translate("vis_window", "Open static plot (tab.)"))
        self.tab_model_fields.setTabText(self.tab_model_fields.indexOf(self.metrics_widget), _translate("vis_window", "Evaluation metrics"))
        self.open_perm_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_model_fields.setTabText(self.tab_model_fields.indexOf(self.perm_widget), _translate("vis_window", "Permutation importance"))
        self.categories_widget.setTabText(self.categories_widget.indexOf(self.tab_model), _translate("vis_window", "Data-driven model review"))
        self.open_image_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_plan_fields.setTabText(self.tab_plan_fields.indexOf(self.image_widget), _translate("vis_window", "CT/Dose image"))
        self.open_dvh_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_plan_fields.setTabText(self.tab_plan_fields.indexOf(self.dvh_widget), _translate("vis_window", "Dose-volume histogram"))
        self.open_ind_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_plan_fields.setTabText(self.tab_plan_fields.indexOf(self.ind_widget), _translate("vis_window", "Quality indicators"))
        self.categories_widget.setTabText(self.categories_widget.indexOf(self.tab_plan), _translate("vis_window", "Treatment Plan Evaluation"))
        self.close_visualizer_pbutton.setText(_translate("vis_window", "Close"))
