[tool.poetry]
name = "pyanno4rt"
version = "1.0.0"
description = "A package for Python-based advanced numerical nonlinear optimization in radiotherapy."
license = "LICENSE"
authors = [ "Tim Ortkamp <tim.ortkamp@gmx.de>" ]
readme = "README.md"
repository = "https://github.com/pyanno4rt/pyanno4rt"
documentation = "https://pyanno4rt.readthedocs.io/en/latest/"
keywords = [ "python", "data-science", "machine-learning", "optimization", "outcome-prediction", "radiotherapy-treatment-planning" ]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Topic :: Education",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Libraries"
]

[[tool.poetry.packages]]
include = "pyanno4rt"

[tool.poetry.dependencies]
python = ">=3.11, <4.0"
numpy = ">=2.3.5"
ipyopt = ">=0.12.10"
absl-py = ">=2.3.1"
pydicom = ">=3.0.1"
scikit-image = ">=0.26.0"
h5py = ">=3.15.1"
pandas = ">=3.0.0"
jax = ">=0.9.0.1"
jaxlib = ">=0.9.0.1"
numba = ">=0.63.1"
scikit-learn = ">=1.8.0"
tensorflow = ">=2.20.0"
hyperopt = ">=0.2.7"
pymoo = ">=0.6.1.6"
pyqt5-qt5 = "5.15.2"
pyqt5 = "5.15.10"
pyqtgraph = ">=0.14.0"
matplotlib = ">=3.10.8"
seaborn = ">=0.13.2"
pypop7 = ">=0.0.82"

[tool.poetry.group.dev.dependencies]
pyqtwebengine-qt5 = "5.15.2"
ipython = ">=9.10.0"
spyder = ">=6.1.2"
spyder-kernels = ">=3.1.3"
jupyter = ">=1.1.1"
sphinx = ">=9.0.4"
sphinx-rtd-theme = ">=3.1.0"
sphinx-autoapi = "3.6.0"
myst-nb = ">=1.3.0"
pytest = ">=9.0.2"
pytest-cov = ">=7.0.0"
coveralls = ">=4.0.2"
sphinx-copybutton = ">=0.5.2"
sphinx-last-updated-by-git = ">=0.3.8"
sphinx-favicon = ">=1.0.1"
myst-sphinx-gallery = ">=0.3.0"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/pyanno4rt/pyanno4rt/issues"

[tool.coverage.run]
omit = ['*/assets/*', '*/compilations/*', '*/designs/*']

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
