[tool.poetry]
name = "pyanno4rt"
version = "1.0.0"
description = "A library for Python-based advanced numerical nonlinear optimization in radiotherapy."
license = "GPL-3.0-or-later"
authors = [ "Tim Ortkamp <tim.ortkamp@gmx.de>" ]
readme = "README.md"
repository = "https://github.com/pyanno4rt/pyanno4rt"
documentation = "https://pyanno4rt.readthedocs.io/en/latest/"
keywords = [ "python", "data-science", "machine-learning", "optimization", "outcome-prediction", "radiotherapy-treatment-planning" ]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Topic :: Education",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Libraries"
]

[[tool.poetry.packages]]
include = "pyanno4rt"

[tool.poetry.dependencies]
python = ">=3.11, <4.0"
numpy = ">=2.4.6"
ipyopt = ">=0.12.10"
absl-py = ">=2.5.0"
pydicom = ">=3.0.2"
scikit-image = ">=0.26.0"
pandas = ">=3.0.5"
jax = ">=0.10.2"
jaxlib = ">=0.10.2"
numba = ">=0.66.0"
scikit-learn = ">=1.9.0"
tensorflow = ">=2.21.0"
hyperopt = ">=0.3.0"
pymoo = ">=0.6.2"
pyqt5-qt5 = "5.15.2"
pyqt5 = "5.15.10"
pyqtgraph = ">=0.14.0"
matplotlib = ">=3.11.1"
seaborn = ">=0.13.2"
pypop7 = ">=0.0.82"
setuptools = "<81.0.0"
pymatreader = ">=1.2.2"
seamaze = ">=0.0.10"

[tool.poetry.group.dev.dependencies]
pyqtwebengine-qt5 = "5.15.2"
ipython = ">=9.16.1"
spyder-kernels = ">=3.1.5"
jupyter = ">=1.1.1"
sphinx = ">=9.0.4"
sphinx-rtd-theme = ">=3.1.0"
sphinx-autoapi = "3.6.0"
myst-nb = ">=1.4.0"
pytest = ">=9.1.1"
pytest-cov = ">=7.1.0"
coveralls = ">=4.1.0"
sphinx-copybutton = ">=0.5.2"
sphinx-last-updated-by-git = ">=0.3.8"
sphinx-favicon = ">=1.1.0"
myst-sphinx-gallery = ">=0.3.0"

[tool.poetry.group.dev-local.dependencies]
spyder = ">=6.1.6"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/pyanno4rt/pyanno4rt/issues"

[tool.coverage.run]
omit = ['*/assets/*', '*/compilations/*', '*/designs/*']

[build-system]
requires = [ "setuptools", "poetry-core" ]
build-backend = "poetry.core.masonry.api"
