# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizer.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vis_window(object):
    def setupUi(self, vis_window):
        vis_window.setObjectName("vis_window")
        vis_window.setWindowModality(QtCore.Qt.WindowModal)
        vis_window.resize(920, 680)
        vis_window.setMinimumSize(QtCore.QSize(920, 680))
        vis_window.setMaximumSize(QtCore.QSize(2560, 1440))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/logo_white_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        vis_window.setWindowIcon(icon)
        self.central_widget = QtWidgets.QWidget(vis_window)
        self.central_widget.setStyleSheet("color: rgb(211, 215, 207);\n"
"background-color: rgb(0, 0, 0);")
        self.central_widget.setObjectName("central_widget")
        self.central_widget_layout = QtWidgets.QVBoxLayout(self.central_widget)
        self.central_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.central_widget_layout.setSpacing(0)
        self.central_widget_layout.setObjectName("central_widget_layout")
        self.body_layout = QtWidgets.QVBoxLayout()
        self.body_layout.setObjectName("body_layout")
        self.widget_layout = QtWidgets.QGridLayout()
        self.widget_layout.setSpacing(0)
        self.widget_layout.setObjectName("widget_layout")
        self.meta_settings_right_widget = QtWidgets.QWidget(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_settings_right_widget.sizePolicy().hasHeightForWidth())
        self.meta_settings_right_widget.setSizePolicy(sizePolicy)
        self.meta_settings_right_widget.setMinimumSize(QtCore.QSize(333, 0))
        self.meta_settings_right_widget.setObjectName("meta_settings_right_widget")
        self.widget_layout.addWidget(self.meta_settings_right_widget, 0, 2, 1, 1)
        self.meta_settings_left_widget = QtWidgets.QWidget(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_settings_left_widget.sizePolicy().hasHeightForWidth())
        self.meta_settings_left_widget.setSizePolicy(sizePolicy)
        self.meta_settings_left_widget.setMinimumSize(QtCore.QSize(333, 0))
        self.meta_settings_left_widget.setObjectName("meta_settings_left_widget")
        self.widget_layout.addWidget(self.meta_settings_left_widget, 0, 0, 1, 1)
        self.categories_widget = QtWidgets.QTabWidget(self.central_widget)
        self.categories_widget.setMinimumSize(QtCore.QSize(916, 0))
        self.categories_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.categories_widget.setIconSize(QtCore.QSize(36, 50))
        self.categories_widget.setDocumentMode(True)
        self.categories_widget.setObjectName("categories_widget")
        self.tab_problem = QtWidgets.QWidget()
        self.tab_problem.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.tab_problem.setObjectName("tab_problem")
        self.tab_problem_meta_layout = QtWidgets.QVBoxLayout(self.tab_problem)
        self.tab_problem_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_problem_meta_layout.setSpacing(0)
        self.tab_problem_meta_layout.setObjectName("tab_problem_meta_layout")
        self.tab_problem_layout = QtWidgets.QVBoxLayout()
        self.tab_problem_layout.setObjectName("tab_problem_layout")
        self.tab_problem_fields = QtWidgets.QTabWidget(self.tab_problem)
        self.tab_problem_fields.setDocumentMode(True)
        self.tab_problem_fields.setObjectName("tab_problem_fields")
        self.comp_vals_widget = QtWidgets.QWidget()
        self.comp_vals_widget.setObjectName("comp_vals_widget")
        self.comp_vals_meta_layout = QtWidgets.QVBoxLayout(self.comp_vals_widget)
        self.comp_vals_meta_layout.setObjectName("comp_vals_meta_layout")
        self.comp_vals_layout = QtWidgets.QVBoxLayout()
        self.comp_vals_layout.setObjectName("comp_vals_layout")
        self.comp_vals_top_layout = QtWidgets.QHBoxLayout()
        self.comp_vals_top_layout.setObjectName("comp_vals_top_layout")
        self.comp_vals_top_widget = QtWidgets.QWidget(self.comp_vals_widget)
        self.comp_vals_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.comp_vals_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.comp_vals_top_widget.setObjectName("comp_vals_top_widget")
        self.comp_vals_top_meta_layout = QtWidgets.QVBoxLayout(self.comp_vals_top_widget)
        self.comp_vals_top_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.comp_vals_top_meta_layout.setSpacing(0)
        self.comp_vals_top_meta_layout.setObjectName("comp_vals_top_meta_layout")
        self.comp_vals_top_widget_layout = QtWidgets.QVBoxLayout()
        self.comp_vals_top_widget_layout.setSpacing(0)
        self.comp_vals_top_widget_layout.setObjectName("comp_vals_top_widget_layout")
        self.comp_vals_top_meta_layout.addLayout(self.comp_vals_top_widget_layout)
        self.comp_vals_top_layout.addWidget(self.comp_vals_top_widget)
        self.comp_vals_options_layout = QtWidgets.QVBoxLayout()
        self.comp_vals_options_layout.setContentsMargins(10, -1, 10, -1)
        self.comp_vals_options_layout.setObjectName("comp_vals_options_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.comp_vals_options_layout.addItem(spacerItem)
        self.open_comp_vals_pbutton = QtWidgets.QPushButton(self.comp_vals_widget)
        self.open_comp_vals_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_comp_vals_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_comp_vals_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_comp_vals_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_comp_vals_pbutton.setObjectName("open_comp_vals_pbutton")
        self.comp_vals_options_layout.addWidget(self.open_comp_vals_pbutton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.comp_vals_options_layout.addItem(spacerItem1)
        self.comp_vals_top_layout.addLayout(self.comp_vals_options_layout)
        self.comp_vals_layout.addLayout(self.comp_vals_top_layout)
        self.comp_vals_meta_layout.addLayout(self.comp_vals_layout)
        self.tab_problem_fields.addTab(self.comp_vals_widget, "")
        self.outc_vals_widget = QtWidgets.QWidget()
        self.outc_vals_widget.setObjectName("outc_vals_widget")
        self.outc_vals_meta_layout = QtWidgets.QVBoxLayout(self.outc_vals_widget)
        self.outc_vals_meta_layout.setObjectName("outc_vals_meta_layout")
        self.outc_vals_layout = QtWidgets.QVBoxLayout()
        self.outc_vals_layout.setObjectName("outc_vals_layout")
        self.outc_vals_top_layout = QtWidgets.QHBoxLayout()
        self.outc_vals_top_layout.setObjectName("outc_vals_top_layout")
        self.outc_vals_top_widget = QtWidgets.QWidget(self.outc_vals_widget)
        self.outc_vals_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.outc_vals_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.outc_vals_top_widget.setObjectName("outc_vals_top_widget")
        self.outc_vals_top_meta_layout = QtWidgets.QVBoxLayout(self.outc_vals_top_widget)
        self.outc_vals_top_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.outc_vals_top_meta_layout.setSpacing(0)
        self.outc_vals_top_meta_layout.setObjectName("outc_vals_top_meta_layout")
        self.outc_vals_top_widget_layout = QtWidgets.QVBoxLayout()
        self.outc_vals_top_widget_layout.setSpacing(0)
        self.outc_vals_top_widget_layout.setObjectName("outc_vals_top_widget_layout")
        self.outc_vals_top_meta_layout.addLayout(self.outc_vals_top_widget_layout)
        self.outc_vals_top_layout.addWidget(self.outc_vals_top_widget)
        self.outc_vals_options_layout = QtWidgets.QVBoxLayout()
        self.outc_vals_options_layout.setContentsMargins(10, -1, 10, -1)
        self.outc_vals_options_layout.setObjectName("outc_vals_options_layout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.outc_vals_options_layout.addItem(spacerItem2)
        self.open_outc_vals_pbutton = QtWidgets.QPushButton(self.outc_vals_widget)
        self.open_outc_vals_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_outc_vals_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_outc_vals_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_outc_vals_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_outc_vals_pbutton.setObjectName("open_outc_vals_pbutton")
        self.outc_vals_options_layout.addWidget(self.open_outc_vals_pbutton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.outc_vals_options_layout.addItem(spacerItem3)
        self.outc_vals_top_layout.addLayout(self.outc_vals_options_layout)
        self.outc_vals_layout.addLayout(self.outc_vals_top_layout)
        self.outc_vals_meta_layout.addLayout(self.outc_vals_layout)
        self.tab_problem_fields.addTab(self.outc_vals_widget, "")
        self.feat_vals_widget = QtWidgets.QWidget()
        self.feat_vals_widget.setObjectName("feat_vals_widget")
        self.feat_vals_meta_layout = QtWidgets.QVBoxLayout(self.feat_vals_widget)
        self.feat_vals_meta_layout.setObjectName("feat_vals_meta_layout")
        self.feat_vals_layout = QtWidgets.QVBoxLayout()
        self.feat_vals_layout.setObjectName("feat_vals_layout")
        self.feat_vals_top_layout = QtWidgets.QHBoxLayout()
        self.feat_vals_top_layout.setObjectName("feat_vals_top_layout")
        self.feat_vals_top_widget = QtWidgets.QWidget(self.feat_vals_widget)
        self.feat_vals_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.feat_vals_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.feat_vals_top_widget.setObjectName("feat_vals_top_widget")
        self.feat_vals_top_meta_layout = QtWidgets.QVBoxLayout(self.feat_vals_top_widget)
        self.feat_vals_top_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.feat_vals_top_meta_layout.setSpacing(0)
        self.feat_vals_top_meta_layout.setObjectName("feat_vals_top_meta_layout")
        self.feat_vals_top_widget_layout = QtWidgets.QVBoxLayout()
        self.feat_vals_top_widget_layout.setSpacing(0)
        self.feat_vals_top_widget_layout.setObjectName("feat_vals_top_widget_layout")
        self.feat_vals_top_meta_layout.addLayout(self.feat_vals_top_widget_layout)
        self.feat_vals_top_layout.addWidget(self.feat_vals_top_widget)
        self.feat_vals_options_layout = QtWidgets.QVBoxLayout()
        self.feat_vals_options_layout.setContentsMargins(10, -1, 10, -1)
        self.feat_vals_options_layout.setObjectName("feat_vals_options_layout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.feat_vals_options_layout.addItem(spacerItem4)
        self.open_feat_vals_pbutton = QtWidgets.QPushButton(self.feat_vals_widget)
        self.open_feat_vals_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_feat_vals_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_feat_vals_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_feat_vals_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_feat_vals_pbutton.setObjectName("open_feat_vals_pbutton")
        self.feat_vals_options_layout.addWidget(self.open_feat_vals_pbutton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.feat_vals_options_layout.addItem(spacerItem5)
        self.feat_vals_top_layout.addLayout(self.feat_vals_options_layout)
        self.feat_vals_layout.addLayout(self.feat_vals_top_layout)
        self.feat_vals_meta_layout.addLayout(self.feat_vals_layout)
        self.tab_problem_fields.addTab(self.feat_vals_widget, "")
        self.tab_problem_layout.addWidget(self.tab_problem_fields)
        self.tab_problem_meta_layout.addLayout(self.tab_problem_layout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/red_icons/icons_red/crosshair.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.categories_widget.addTab(self.tab_problem, icon1, "")
        self.tab_model = QtWidgets.QWidget()
        self.tab_model.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.tab_model.setObjectName("tab_model")
        self.tab_model_meta_layout = QtWidgets.QVBoxLayout(self.tab_model)
        self.tab_model_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_model_meta_layout.setSpacing(0)
        self.tab_model_meta_layout.setObjectName("tab_model_meta_layout")
        self.tab_model_layout = QtWidgets.QVBoxLayout()
        self.tab_model_layout.setObjectName("tab_model_layout")
        self.tab_model_fields = QtWidgets.QTabWidget(self.tab_model)
        self.tab_model_fields.setDocumentMode(True)
        self.tab_model_fields.setObjectName("tab_model_fields")
        self.metrics_widget = QtWidgets.QWidget()
        self.metrics_widget.setObjectName("metrics_widget")
        self.metrics_meta_layout = QtWidgets.QVBoxLayout(self.metrics_widget)
        self.metrics_meta_layout.setObjectName("metrics_meta_layout")
        self.metrics_layout = QtWidgets.QVBoxLayout()
        self.metrics_layout.setObjectName("metrics_layout")
        self.metrics_top_layout = QtWidgets.QHBoxLayout()
        self.metrics_top_layout.setObjectName("metrics_top_layout")
        self.metrics_top_widget = QtWidgets.QWidget(self.metrics_widget)
        self.metrics_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.metrics_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.metrics_top_widget.setObjectName("metrics_top_widget")
        self.metrics_top_meta_layout = QtWidgets.QVBoxLayout(self.metrics_top_widget)
        self.metrics_top_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.metrics_top_meta_layout.setSpacing(0)
        self.metrics_top_meta_layout.setObjectName("metrics_top_meta_layout")
        self.metrics_top_widget_layout = QtWidgets.QVBoxLayout()
        self.metrics_top_widget_layout.setSpacing(0)
        self.metrics_top_widget_layout.setObjectName("metrics_top_widget_layout")
        self.metrics_top_meta_layout.addLayout(self.metrics_top_widget_layout)
        self.metrics_top_layout.addWidget(self.metrics_top_widget)
        self.metrics_options_layout = QtWidgets.QVBoxLayout()
        self.metrics_options_layout.setContentsMargins(10, -1, 10, -1)
        self.metrics_options_layout.setObjectName("metrics_options_layout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.metrics_options_layout.addItem(spacerItem6)
        self.open_metrics_graphs_pbutton = QtWidgets.QPushButton(self.metrics_widget)
        self.open_metrics_graphs_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_metrics_graphs_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_metrics_graphs_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_metrics_graphs_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_metrics_graphs_pbutton.setObjectName("open_metrics_graphs_pbutton")
        self.metrics_options_layout.addWidget(self.open_metrics_graphs_pbutton)
        self.open_metrics_tables_pbutton = QtWidgets.QPushButton(self.metrics_widget)
        self.open_metrics_tables_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_metrics_tables_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_metrics_tables_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_metrics_tables_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_metrics_tables_pbutton.setObjectName("open_metrics_tables_pbutton")
        self.metrics_options_layout.addWidget(self.open_metrics_tables_pbutton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.metrics_options_layout.addItem(spacerItem7)
        self.metrics_top_layout.addLayout(self.metrics_options_layout)
        self.metrics_layout.addLayout(self.metrics_top_layout)
        self.metrics_meta_layout.addLayout(self.metrics_layout)
        self.tab_model_fields.addTab(self.metrics_widget, "")
        self.perm_widget = QtWidgets.QWidget()
        self.perm_widget.setObjectName("perm_widget")
        self.perm_meta_layout = QtWidgets.QVBoxLayout(self.perm_widget)
        self.perm_meta_layout.setObjectName("perm_meta_layout")
        self.perm_layout = QtWidgets.QVBoxLayout()
        self.perm_layout.setObjectName("perm_layout")
        self.perm_top_layout = QtWidgets.QHBoxLayout()
        self.perm_top_layout.setObjectName("perm_top_layout")
        self.perm_top_widget = QtWidgets.QWidget(self.perm_widget)
        self.perm_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.perm_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.perm_top_widget.setObjectName("perm_top_widget")
        self.perm_top_meta_layout = QtWidgets.QVBoxLayout(self.perm_top_widget)
        self.perm_top_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.perm_top_meta_layout.setSpacing(0)
        self.perm_top_meta_layout.setObjectName("perm_top_meta_layout")
        self.perm_top_widget_layout = QtWidgets.QVBoxLayout()
        self.perm_top_widget_layout.setSpacing(0)
        self.perm_top_widget_layout.setObjectName("perm_top_widget_layout")
        self.perm_top_meta_layout.addLayout(self.perm_top_widget_layout)
        self.perm_top_layout.addWidget(self.perm_top_widget)
        self.perm_options_layout = QtWidgets.QVBoxLayout()
        self.perm_options_layout.setContentsMargins(10, -1, 10, -1)
        self.perm_options_layout.setObjectName("perm_options_layout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.perm_options_layout.addItem(spacerItem8)
        self.open_perm_pbutton = QtWidgets.QPushButton(self.perm_widget)
        self.open_perm_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_perm_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_perm_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_perm_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_perm_pbutton.setObjectName("open_perm_pbutton")
        self.perm_options_layout.addWidget(self.open_perm_pbutton)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.perm_options_layout.addItem(spacerItem9)
        self.perm_top_layout.addLayout(self.perm_options_layout)
        self.perm_layout.addLayout(self.perm_top_layout)
        self.perm_meta_layout.addLayout(self.perm_layout)
        self.tab_model_fields.addTab(self.perm_widget, "")
        self.tab_model_layout.addWidget(self.tab_model_fields)
        self.tab_model_meta_layout.addLayout(self.tab_model_layout)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/green_icons/icons_green/cpu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.categories_widget.addTab(self.tab_model, icon2, "")
        self.tab_plan = QtWidgets.QWidget()
        self.tab_plan.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.tab_plan.setObjectName("tab_plan")
        self.tab_plan_meta_layout = QtWidgets.QVBoxLayout(self.tab_plan)
        self.tab_plan_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_plan_meta_layout.setSpacing(0)
        self.tab_plan_meta_layout.setObjectName("tab_plan_meta_layout")
        self.tab_plan_layout = QtWidgets.QVBoxLayout()
        self.tab_plan_layout.setObjectName("tab_plan_layout")
        self.tab_plan_fields = QtWidgets.QTabWidget(self.tab_plan)
        self.tab_plan_fields.setDocumentMode(True)
        self.tab_plan_fields.setObjectName("tab_plan_fields")
        self.image_widget = QtWidgets.QWidget()
        self.image_widget.setObjectName("image_widget")
        self.image_meta_layout = QtWidgets.QVBoxLayout(self.image_widget)
        self.image_meta_layout.setObjectName("image_meta_layout")
        self.image_layout = QtWidgets.QGridLayout()
        self.image_layout.setObjectName("image_layout")
        self.image_top_widget = QtWidgets.QWidget(self.image_widget)
        self.image_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.image_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.image_top_widget.setObjectName("image_top_widget")
        self.image_top_meta_layout = QtWidgets.QVBoxLayout(self.image_top_widget)
        self.image_top_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.image_top_meta_layout.setSpacing(0)
        self.image_top_meta_layout.setObjectName("image_top_meta_layout")
        self.image_top_widget_layout = QtWidgets.QVBoxLayout()
        self.image_top_widget_layout.setObjectName("image_top_widget_layout")
        self.image_top_meta_layout.addLayout(self.image_top_widget_layout)
        self.image_layout.addWidget(self.image_top_widget, 0, 0, 1, 1)
        self.slice_options_layout = QtWidgets.QHBoxLayout()
        self.slice_options_layout.setContentsMargins(10, -1, 10, -1)
        self.slice_options_layout.setObjectName("slice_options_layout")
        self.plane_layout = QtWidgets.QVBoxLayout()
        self.plane_layout.setObjectName("plane_layout")
        self.plane_label = QtWidgets.QLabel(self.image_widget)
        self.plane_label.setMinimumSize(QtCore.QSize(0, 25))
        self.plane_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plane_label.setFont(font)
        self.plane_label.setStyleSheet("border: 0px;")
        self.plane_label.setObjectName("plane_label")
        self.plane_layout.addWidget(self.plane_label)
        self.plane_cbox = QtWidgets.QComboBox(self.image_widget)
        self.plane_cbox.setMinimumSize(QtCore.QSize(101, 31))
        self.plane_cbox.setMaximumSize(QtCore.QSize(16777215, 31))
        self.plane_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plane_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.plane_cbox.setObjectName("plane_cbox")
        self.plane_cbox.addItem("")
        self.plane_cbox.addItem("")
        self.plane_cbox.addItem("")
        self.plane_layout.addWidget(self.plane_cbox)
        self.slice_options_layout.addLayout(self.plane_layout)
        self.opacity_layout = QtWidgets.QVBoxLayout()
        self.opacity_layout.setObjectName("opacity_layout")
        self.opacity_label = QtWidgets.QLabel(self.image_widget)
        self.opacity_label.setMinimumSize(QtCore.QSize(0, 25))
        self.opacity_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.opacity_label.setFont(font)
        self.opacity_label.setStyleSheet("border: 0px;")
        self.opacity_label.setObjectName("opacity_label")
        self.opacity_layout.addWidget(self.opacity_label)
        self.opacity_sbox = QtWidgets.QSpinBox(self.image_widget)
        self.opacity_sbox.setMinimumSize(QtCore.QSize(101, 31))
        self.opacity_sbox.setMaximumSize(QtCore.QSize(16777215, 31))
        self.opacity_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.opacity_sbox.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.opacity_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.opacity_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.opacity_sbox.setMaximum(100)
        self.opacity_sbox.setProperty("value", 70)
        self.opacity_sbox.setObjectName("opacity_sbox")
        self.opacity_layout.addWidget(self.opacity_sbox)
        self.slice_options_layout.addLayout(self.opacity_layout)
        self.slice_layout = QtWidgets.QVBoxLayout()
        self.slice_layout.setObjectName("slice_layout")
        self.slice_label_layout = QtWidgets.QHBoxLayout()
        self.slice_label_layout.setObjectName("slice_label_layout")
        self.slice_selection_label = QtWidgets.QLabel(self.image_widget)
        self.slice_selection_label.setMinimumSize(QtCore.QSize(0, 25))
        self.slice_selection_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slice_selection_label.setFont(font)
        self.slice_selection_label.setStyleSheet("border: 0px;")
        self.slice_selection_label.setObjectName("slice_selection_label")
        self.slice_label_layout.addWidget(self.slice_selection_label)
        self.slice_selection_pos = QtWidgets.QLabel(self.image_widget)
        self.slice_selection_pos.setMinimumSize(QtCore.QSize(0, 25))
        self.slice_selection_pos.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slice_selection_pos.setFont(font)
        self.slice_selection_pos.setStyleSheet("border: 0px;")
        self.slice_selection_pos.setText("")
        self.slice_selection_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slice_selection_pos.setObjectName("slice_selection_pos")
        self.slice_label_layout.addWidget(self.slice_selection_pos)
        self.slice_layout.addLayout(self.slice_label_layout)
        self.slice_selection_sbar = QtWidgets.QScrollBar(self.image_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slice_selection_sbar.sizePolicy().hasHeightForWidth())
        self.slice_selection_sbar.setSizePolicy(sizePolicy)
        self.slice_selection_sbar.setMinimumSize(QtCore.QSize(0, 31))
        self.slice_selection_sbar.setMaximumSize(QtCore.QSize(16777215, 31))
        self.slice_selection_sbar.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.slice_selection_sbar.setProperty("value", 49)
        self.slice_selection_sbar.setOrientation(QtCore.Qt.Horizontal)
        self.slice_selection_sbar.setObjectName("slice_selection_sbar")
        self.slice_layout.addWidget(self.slice_selection_sbar)
        self.slice_options_layout.addLayout(self.slice_layout)
        self.image_layout.addLayout(self.slice_options_layout, 1, 0, 1, 1)
        self.image_options_layout = QtWidgets.QVBoxLayout()
        self.image_options_layout.setObjectName("image_options_layout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.image_options_layout.addItem(spacerItem10)
        self.open_image_pbutton = QtWidgets.QPushButton(self.image_widget)
        self.open_image_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_image_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_image_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_image_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_image_pbutton.setObjectName("open_image_pbutton")
        self.image_options_layout.addWidget(self.open_image_pbutton)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.image_options_layout.addItem(spacerItem11)
        self.image_layout.addLayout(self.image_options_layout, 0, 1, 1, 1)
        self.image_meta_layout.addLayout(self.image_layout)
        self.tab_plan_fields.addTab(self.image_widget, "")
        self.dvh_widget = QtWidgets.QWidget()
        self.dvh_widget.setObjectName("dvh_widget")
        self.dvh_meta_layout = QtWidgets.QVBoxLayout(self.dvh_widget)
        self.dvh_meta_layout.setObjectName("dvh_meta_layout")
        self.dvh_layout = QtWidgets.QGridLayout()
        self.dvh_layout.setObjectName("dvh_layout")
        self.dvh_options_layout = QtWidgets.QVBoxLayout()
        self.dvh_options_layout.setObjectName("dvh_options_layout")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.dvh_options_layout.addItem(spacerItem12)
        self.open_dvh_pbutton = QtWidgets.QPushButton(self.dvh_widget)
        self.open_dvh_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_dvh_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_dvh_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_dvh_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_dvh_pbutton.setObjectName("open_dvh_pbutton")
        self.dvh_options_layout.addWidget(self.open_dvh_pbutton)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.dvh_options_layout.addItem(spacerItem13)
        self.dvh_layout.addLayout(self.dvh_options_layout, 0, 1, 1, 1)
        self.dvh_top_widget = QtWidgets.QWidget(self.dvh_widget)
        self.dvh_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.dvh_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.dvh_top_widget.setObjectName("dvh_top_widget")
        self.dvh_top_meta_layout = QtWidgets.QVBoxLayout(self.dvh_top_widget)
        self.dvh_top_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.dvh_top_meta_layout.setSpacing(0)
        self.dvh_top_meta_layout.setObjectName("dvh_top_meta_layout")
        self.dvh_top_widget_layout = QtWidgets.QVBoxLayout()
        self.dvh_top_widget_layout.setSpacing(6)
        self.dvh_top_widget_layout.setObjectName("dvh_top_widget_layout")
        self.dvh_top_meta_layout.addLayout(self.dvh_top_widget_layout)
        self.dvh_layout.addWidget(self.dvh_top_widget, 0, 0, 1, 1)
        self.stats_layout = QtWidgets.QGridLayout()
        self.stats_layout.setContentsMargins(10, -1, 10, -1)
        self.stats_layout.setObjectName("stats_layout")
        self.segment_label = QtWidgets.QLabel(self.dvh_widget)
        self.segment_label.setMinimumSize(QtCore.QSize(212, 25))
        self.segment_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.segment_label.setFont(font)
        self.segment_label.setStyleSheet("border: 0px solid;")
        self.segment_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.segment_label.setObjectName("segment_label")
        self.stats_layout.addWidget(self.segment_label, 0, 0, 1, 1)
        self.maximum_label = QtWidgets.QLabel(self.dvh_widget)
        self.maximum_label.setMinimumSize(QtCore.QSize(0, 25))
        self.maximum_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maximum_label.setFont(font)
        self.maximum_label.setStyleSheet("border: 0px solid;")
        self.maximum_label.setAlignment(QtCore.Qt.AlignCenter)
        self.maximum_label.setObjectName("maximum_label")
        self.stats_layout.addWidget(self.maximum_label, 0, 3, 1, 1)
        self.minimum_label = QtWidgets.QLabel(self.dvh_widget)
        self.minimum_label.setMinimumSize(QtCore.QSize(0, 25))
        self.minimum_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minimum_label.setFont(font)
        self.minimum_label.setStyleSheet("border: 0px solid;")
        self.minimum_label.setAlignment(QtCore.Qt.AlignCenter)
        self.minimum_label.setObjectName("minimum_label")
        self.stats_layout.addWidget(self.minimum_label, 0, 4, 1, 1)
        self.std_label = QtWidgets.QLabel(self.dvh_widget)
        self.std_label.setMinimumSize(QtCore.QSize(0, 25))
        self.std_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.std_label.setFont(font)
        self.std_label.setStyleSheet("border: 0px solid;")
        self.std_label.setAlignment(QtCore.Qt.AlignCenter)
        self.std_label.setObjectName("std_label")
        self.stats_layout.addWidget(self.std_label, 0, 2, 1, 1)
        self.mean_label = QtWidgets.QLabel(self.dvh_widget)
        self.mean_label.setMinimumSize(QtCore.QSize(0, 25))
        self.mean_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mean_label.setFont(font)
        self.mean_label.setStyleSheet("border: 0px solid;")
        self.mean_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mean_label.setObjectName("mean_label")
        self.stats_layout.addWidget(self.mean_label, 0, 1, 1, 1)
        self.segment_ledit = QtWidgets.QLineEdit(self.dvh_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segment_ledit.sizePolicy().hasHeightForWidth())
        self.segment_ledit.setSizePolicy(sizePolicy)
        self.segment_ledit.setMinimumSize(QtCore.QSize(212, 31))
        self.segment_ledit.setMaximumSize(QtCore.QSize(212, 31))
        self.segment_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.segment_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.segment_ledit.setReadOnly(True)
        self.segment_ledit.setObjectName("segment_ledit")
        self.stats_layout.addWidget(self.segment_ledit, 1, 0, 1, 1)
        self.mean_ledit = QtWidgets.QLineEdit(self.dvh_widget)
        self.mean_ledit.setMinimumSize(QtCore.QSize(0, 31))
        self.mean_ledit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.mean_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.mean_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.mean_ledit.setReadOnly(True)
        self.mean_ledit.setObjectName("mean_ledit")
        self.stats_layout.addWidget(self.mean_ledit, 1, 1, 1, 1)
        self.std_ledit = QtWidgets.QLineEdit(self.dvh_widget)
        self.std_ledit.setMinimumSize(QtCore.QSize(0, 31))
        self.std_ledit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.std_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.std_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.std_ledit.setReadOnly(True)
        self.std_ledit.setObjectName("std_ledit")
        self.stats_layout.addWidget(self.std_ledit, 1, 2, 1, 1)
        self.maximum_ledit = QtWidgets.QLineEdit(self.dvh_widget)
        self.maximum_ledit.setMinimumSize(QtCore.QSize(0, 31))
        self.maximum_ledit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.maximum_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.maximum_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.maximum_ledit.setReadOnly(True)
        self.maximum_ledit.setObjectName("maximum_ledit")
        self.stats_layout.addWidget(self.maximum_ledit, 1, 3, 1, 1)
        self.minimum_ledit = QtWidgets.QLineEdit(self.dvh_widget)
        self.minimum_ledit.setMinimumSize(QtCore.QSize(0, 31))
        self.minimum_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.minimum_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.minimum_ledit.setReadOnly(True)
        self.minimum_ledit.setObjectName("minimum_ledit")
        self.stats_layout.addWidget(self.minimum_ledit, 1, 4, 1, 1)
        self.dvh_layout.addLayout(self.stats_layout, 1, 0, 1, 1)
        self.dvh_meta_layout.addLayout(self.dvh_layout)
        self.tab_plan_fields.addTab(self.dvh_widget, "")
        self.ind_widget = QtWidgets.QWidget()
        self.ind_widget.setObjectName("ind_widget")
        self.ind_meta_layout = QtWidgets.QVBoxLayout(self.ind_widget)
        self.ind_meta_layout.setObjectName("ind_meta_layout")
        self.ind_layout = QtWidgets.QVBoxLayout()
        self.ind_layout.setObjectName("ind_layout")
        self.ind_top_layout = QtWidgets.QHBoxLayout()
        self.ind_top_layout.setObjectName("ind_top_layout")
        self.ind_top_widget = QtWidgets.QWidget(self.ind_widget)
        self.ind_top_widget.setMinimumSize(QtCore.QSize(0, 187))
        self.ind_top_widget.setStyleSheet("border: 1px solid;\n"
"border-color: rgb(211, 215, 207);")
        self.ind_top_widget.setObjectName("ind_top_widget")
        self.dvh_top_meta_layout_2 = QtWidgets.QVBoxLayout(self.ind_top_widget)
        self.dvh_top_meta_layout_2.setContentsMargins(0, 0, 0, 0)
        self.dvh_top_meta_layout_2.setSpacing(0)
        self.dvh_top_meta_layout_2.setObjectName("dvh_top_meta_layout_2")
        self.ind_top_widget_layout = QtWidgets.QVBoxLayout()
        self.ind_top_widget_layout.setSpacing(6)
        self.ind_top_widget_layout.setObjectName("ind_top_widget_layout")
        self.ind_table_widget = QtWidgets.QTableWidget(self.ind_top_widget)
        self.ind_table_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.ind_table_widget.setAlternatingRowColors(True)
        self.ind_table_widget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.ind_table_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ind_table_widget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ind_table_widget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ind_table_widget.setObjectName("ind_table_widget")
        self.ind_table_widget.setColumnCount(0)
        self.ind_table_widget.setRowCount(0)
        self.ind_table_widget.horizontalHeader().setMinimumSectionSize(75)
        self.ind_table_widget.verticalHeader().setMinimumSectionSize(30)
        self.ind_top_widget_layout.addWidget(self.ind_table_widget)
        self.dvh_top_meta_layout_2.addLayout(self.ind_top_widget_layout)
        self.ind_top_layout.addWidget(self.ind_top_widget)
        self.ind_options_layout = QtWidgets.QVBoxLayout()
        self.ind_options_layout.setContentsMargins(10, -1, 10, -1)
        self.ind_options_layout.setObjectName("ind_options_layout")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ind_options_layout.addItem(spacerItem14)
        self.open_ind_pbutton = QtWidgets.QPushButton(self.ind_widget)
        self.open_ind_pbutton.setMinimumSize(QtCore.QSize(161, 31))
        self.open_ind_pbutton.setMaximumSize(QtCore.QSize(161, 31))
        self.open_ind_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_ind_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.open_ind_pbutton.setObjectName("open_ind_pbutton")
        self.ind_options_layout.addWidget(self.open_ind_pbutton)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.ind_options_layout.addItem(spacerItem15)
        self.ind_top_layout.addLayout(self.ind_options_layout)
        self.ind_layout.addLayout(self.ind_top_layout)
        self.ind_meta_layout.addLayout(self.ind_layout)
        self.tab_plan_fields.addTab(self.ind_widget, "")
        self.tab_plan_layout.addWidget(self.tab_plan_fields)
        self.tab_plan_meta_layout.addLayout(self.tab_plan_layout)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/goldIcons/icons_gold/box.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.categories_widget.addTab(self.tab_plan, icon3, "")
        self.widget_layout.addWidget(self.categories_widget, 4, 0, 1, 3)
        self.logo_widget = QtWidgets.QWidget(self.central_widget)
        self.logo_widget.setMinimumSize(QtCore.QSize(250, 210))
        self.logo_widget.setMaximumSize(QtCore.QSize(250, 210))
        self.logo_widget.setObjectName("logo_widget")
        self.logo_widget_layout = QtWidgets.QHBoxLayout(self.logo_widget)
        self.logo_widget_layout.setContentsMargins(0, 0, 0, 0)
        self.logo_widget_layout.setObjectName("logo_widget_layout")
        self.logo_pixmap = QtWidgets.QLabel(self.logo_widget)
        self.logo_pixmap.setMaximumSize(QtCore.QSize(210, 210))
        self.logo_pixmap.setPixmap(QtGui.QPixmap(":/Logo/logo_white_square.png"))
        self.logo_pixmap.setScaledContents(True)
        self.logo_pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_pixmap.setObjectName("logo_pixmap")
        self.logo_widget_layout.addWidget(self.logo_pixmap)
        self.widget_layout.addWidget(self.logo_widget, 0, 1, 1, 1)
        self.widget_layout.setColumnStretch(0, 1)
        self.body_layout.addLayout(self.widget_layout)
        self.bottom_widget = QtWidgets.QWidget(self.central_widget)
        self.bottom_widget.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.bottom_widget.setObjectName("bottom_widget")
        self.bottom_widget_meta_layout = QtWidgets.QHBoxLayout(self.bottom_widget)
        self.bottom_widget_meta_layout.setContentsMargins(0, 0, 0, 0)
        self.bottom_widget_meta_layout.setObjectName("bottom_widget_meta_layout")
        self.bottom_widget_layout = QtWidgets.QHBoxLayout()
        self.bottom_widget_layout.setContentsMargins(10, 10, 10, 10)
        self.bottom_widget_layout.setObjectName("bottom_widget_layout")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_widget_layout.addItem(spacerItem16)
        self.close_visualizer_pbutton = QtWidgets.QPushButton(self.bottom_widget)
        self.close_visualizer_pbutton.setMinimumSize(QtCore.QSize(71, 31))
        self.close_visualizer_pbutton.setMaximumSize(QtCore.QSize(71, 31))
        self.close_visualizer_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_visualizer_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.close_visualizer_pbutton.setObjectName("close_visualizer_pbutton")
        self.bottom_widget_layout.addWidget(self.close_visualizer_pbutton)
        self.bottom_widget_meta_layout.addLayout(self.bottom_widget_layout)
        self.body_layout.addWidget(self.bottom_widget)
        self.central_widget_layout.addLayout(self.body_layout)
        vis_window.setCentralWidget(self.central_widget)

        self.retranslateUi(vis_window)
        self.categories_widget.setCurrentIndex(0)
        self.tab_problem_fields.setCurrentIndex(0)
        self.tab_model_fields.setCurrentIndex(0)
        self.tab_plan_fields.setCurrentIndex(0)
        self.plane_cbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(vis_window)

    def retranslateUi(self, vis_window):
        _translate = QtCore.QCoreApplication.translate
        vis_window.setWindowTitle(_translate("vis_window", "Visualizer"))
        self.open_comp_vals_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_problem_fields.setTabText(self.tab_problem_fields.indexOf(self.comp_vals_widget), _translate("vis_window", "Iterative component values"))
        self.open_outc_vals_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_problem_fields.setTabText(self.tab_problem_fields.indexOf(self.outc_vals_widget), _translate("vis_window", "Iterative outcome values"))
        self.open_feat_vals_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_problem_fields.setTabText(self.tab_problem_fields.indexOf(self.feat_vals_widget), _translate("vis_window", "Iterative feature values"))
        self.categories_widget.setTabText(self.categories_widget.indexOf(self.tab_problem), _translate("vis_window", "Optimization problem analysis"))
        self.open_metrics_graphs_pbutton.setText(_translate("vis_window", "Open static plot (gr.)"))
        self.open_metrics_tables_pbutton.setText(_translate("vis_window", "Open static plot (tab.)"))
        self.tab_model_fields.setTabText(self.tab_model_fields.indexOf(self.metrics_widget), _translate("vis_window", "Evaluation metrics"))
        self.open_perm_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_model_fields.setTabText(self.tab_model_fields.indexOf(self.perm_widget), _translate("vis_window", "Permutation importance"))
        self.categories_widget.setTabText(self.categories_widget.indexOf(self.tab_model), _translate("vis_window", "Data-driven model review"))
        self.plane_label.setText(_translate("vis_window", "Plane"))
        self.plane_cbox.setCurrentText(_translate("vis_window", "axial"))
        self.plane_cbox.setItemText(0, _translate("vis_window", "axial"))
        self.plane_cbox.setItemText(1, _translate("vis_window", "coronal"))
        self.plane_cbox.setItemText(2, _translate("vis_window", "sagittal"))
        self.opacity_label.setText(_translate("vis_window", "Dose opacity"))
        self.slice_selection_label.setText(_translate("vis_window", "Slice"))
        self.open_image_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_plan_fields.setTabText(self.tab_plan_fields.indexOf(self.image_widget), _translate("vis_window", "CT/Dose image"))
        self.open_dvh_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.segment_label.setText(_translate("vis_window", "Segment"))
        self.maximum_label.setText(_translate("vis_window", "Max"))
        self.minimum_label.setText(_translate("vis_window", "Min"))
        self.std_label.setText(_translate("vis_window", "Std"))
        self.mean_label.setText(_translate("vis_window", "Mean"))
        self.tab_plan_fields.setTabText(self.tab_plan_fields.indexOf(self.dvh_widget), _translate("vis_window", "Dose-volume histogram"))
        self.open_ind_pbutton.setText(_translate("vis_window", "Open static plot"))
        self.tab_plan_fields.setTabText(self.tab_plan_fields.indexOf(self.ind_widget), _translate("vis_window", "Quality indicators"))
        self.categories_widget.setTabText(self.categories_widget.indexOf(self.tab_plan), _translate("vis_window", "Treatment plan evaluation"))
        self.close_visualizer_pbutton.setText(_translate("vis_window", "Close"))
