# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decision_tree_ntcp_window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_decision_tree_ntcp_window(object):
    def setupUi(self, decision_tree_ntcp_window):
        decision_tree_ntcp_window.setObjectName("decision_tree_ntcp_window")
        decision_tree_ntcp_window.setWindowModality(QtCore.Qt.ApplicationModal)
        decision_tree_ntcp_window.resize(720, 431)
        decision_tree_ntcp_window.setMinimumSize(QtCore.QSize(720, 431))
        decision_tree_ntcp_window.setMaximumSize(QtCore.QSize(720, 431))
        decision_tree_ntcp_window.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.body_widget = QtWidgets.QWidget(decision_tree_ntcp_window)
        self.body_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.body_widget.setObjectName("body_widget")
        self.scroll_area = QtWidgets.QScrollArea(self.body_widget)
        self.scroll_area.setGeometry(QtCore.QRect(10, 0, 711, 431))
        self.scroll_area.setStyleSheet("border-color: transparent;")
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_contents = QtWidgets.QWidget()
        self.scroll_contents.setGeometry(QtCore.QRect(0, -950, 690, 1589))
        self.scroll_contents.setObjectName("scroll_contents")
        self.embedding_cbox = QtWidgets.QComboBox(self.scroll_contents)
        self.embedding_cbox.setGeometry(QtCore.QRect(574, 90, 111, 31))
        self.embedding_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.embedding_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.embedding_cbox.setObjectName("embedding_cbox")
        self.embedding_cbox.addItem("")
        self.embedding_cbox.addItem("")
        self.segment_label = QtWidgets.QLabel(self.scroll_contents)
        self.segment_label.setGeometry(QtCore.QRect(0, 60, 421, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.segment_label.setFont(font)
        self.segment_label.setStyleSheet("border: 0px solid;")
        self.segment_label.setObjectName("segment_label")
        self.embedding_label = QtWidgets.QLabel(self.scroll_contents)
        self.embedding_label.setGeometry(QtCore.QRect(575, 60, 109, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.embedding_label.setFont(font)
        self.embedding_label.setStyleSheet("border: 0px solid;")
        self.embedding_label.setObjectName("embedding_label")
        self.base_label = QtWidgets.QLabel(self.scroll_contents)
        self.base_label.setGeometry(QtCore.QRect(0, 10, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.base_label.setFont(font)
        self.base_label.setStyleSheet("border: 0px solid;")
        self.base_label.setObjectName("base_label")
        self.type_cbox = QtWidgets.QComboBox(self.scroll_contents)
        self.type_cbox.setGeometry(QtCore.QRect(445, 90, 111, 31))
        self.type_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.type_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.type_cbox.setObjectName("type_cbox")
        self.type_cbox.addItem("")
        self.type_cbox.addItem("")
        self.base_line = QtWidgets.QFrame(self.scroll_contents)
        self.base_line.setGeometry(QtCore.QRect(0, 50, 684, 2))
        self.base_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.base_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.base_line.setObjectName("base_line")
        self.type_label = QtWidgets.QLabel(self.scroll_contents)
        self.type_label.setGeometry(QtCore.QRect(445, 60, 111, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.type_label.setFont(font)
        self.type_label.setStyleSheet("border: 0px solid;")
        self.type_label.setObjectName("type_label")
        self.close_pbutton = QtWidgets.QPushButton(self.scroll_contents)
        self.close_pbutton.setGeometry(QtCore.QRect(614, 1550, 71, 31))
        self.close_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.close_pbutton.setObjectName("close_pbutton")
        self.identifier_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.identifier_ledit.setGeometry(QtCore.QRect(0, 1460, 381, 31))
        self.identifier_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.identifier_ledit.setObjectName("identifier_ledit")
        self.rank_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.rank_sbox.setGeometry(QtCore.QRect(190, 370, 111, 31))
        self.rank_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.rank_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.rank_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.rank_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.rank_sbox.setMinimum(1)
        self.rank_sbox.setMaximum(1000)
        self.rank_sbox.setProperty("value", 1)
        self.rank_sbox.setObjectName("rank_sbox")
        self.identifier_label = QtWidgets.QLabel(self.scroll_contents)
        self.identifier_label.setGeometry(QtCore.QRect(0, 1430, 381, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.identifier_label.setFont(font)
        self.identifier_label.setStyleSheet("border: 0px solid;")
        self.identifier_label.setObjectName("identifier_label")
        self.link_label = QtWidgets.QLabel(self.scroll_contents)
        self.link_label.setGeometry(QtCore.QRect(0, 200, 431, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.link_label.setFont(font)
        self.link_label.setStyleSheet("border: none;")
        self.link_label.setObjectName("link_label")
        self.function_label = QtWidgets.QLabel(self.scroll_contents)
        self.function_label.setGeometry(QtCore.QRect(0, 150, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.function_label.setFont(font)
        self.function_label.setStyleSheet("border: 0px solid;")
        self.function_label.setObjectName("function_label")
        self.bounds_label = QtWidgets.QLabel(self.scroll_contents)
        self.bounds_label.setGeometry(QtCore.QRect(323, 340, 364, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bounds_label.setFont(font)
        self.bounds_label.setStyleSheet("border: 0px solid;")
        self.bounds_label.setObjectName("bounds_label")
        self.handling_viz_label = QtWidgets.QLabel(self.scroll_contents)
        self.handling_viz_label.setGeometry(QtCore.QRect(0, 1380, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.handling_viz_label.setFont(font)
        self.handling_viz_label.setStyleSheet("border: 0px solid;")
        self.handling_viz_label.setObjectName("handling_viz_label")
        self.weight_label = QtWidgets.QLabel(self.scroll_contents)
        self.weight_label.setGeometry(QtCore.QRect(0, 340, 171, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.weight_label.setFont(font)
        self.weight_label.setStyleSheet("border: 0px solid;")
        self.weight_label.setObjectName("weight_label")
        self.save_pbutton = QtWidgets.QPushButton(self.scroll_contents)
        self.save_pbutton.setGeometry(QtCore.QRect(534, 1550, 71, 31))
        self.save_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.save_pbutton.setObjectName("save_pbutton")
        self.function_line = QtWidgets.QFrame(self.scroll_contents)
        self.function_line.setGeometry(QtCore.QRect(0, 190, 684, 2))
        self.function_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.function_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.function_line.setObjectName("function_line")
        self.opt_bounds_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.opt_bounds_conjunction.setGeometry(QtCore.QRect(494, 376, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.opt_bounds_conjunction.setFont(font)
        self.opt_bounds_conjunction.setStyleSheet("border: none;")
        self.opt_bounds_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_bounds_conjunction.setObjectName("opt_bounds_conjunction")
        self.optimization_label = QtWidgets.QLabel(self.scroll_contents)
        self.optimization_label.setGeometry(QtCore.QRect(0, 290, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.optimization_label.setFont(font)
        self.optimization_label.setStyleSheet("border: 0px solid;")
        self.optimization_label.setObjectName("optimization_label")
        self.rank_label = QtWidgets.QLabel(self.scroll_contents)
        self.rank_label.setGeometry(QtCore.QRect(190, 340, 111, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rank_label.setFont(font)
        self.rank_label.setStyleSheet("border: 0px solid;")
        self.rank_label.setObjectName("rank_label")
        self.upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.upper_bound_ledit.setGeometry(QtCore.QRect(515, 370, 170, 31))
        self.upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.upper_bound_ledit.setObjectName("upper_bound_ledit")
        self.weight_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.weight_ledit.setGeometry(QtCore.QRect(0, 370, 171, 31))
        self.weight_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.weight_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.weight_ledit.setObjectName("weight_ledit")
        self.disp_component_check = QtWidgets.QCheckBox(self.scroll_contents)
        self.disp_component_check.setGeometry(QtCore.QRect(0, 1510, 231, 23))
        self.disp_component_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.disp_component_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.disp_component_check.setChecked(True)
        self.disp_component_check.setObjectName("disp_component_check")
        self.handling_viz_line = QtWidgets.QFrame(self.scroll_contents)
        self.handling_viz_line.setGeometry(QtCore.QRect(0, 1420, 684, 2))
        self.handling_viz_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.handling_viz_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.handling_viz_line.setObjectName("handling_viz_line")
        self.optimization_line = QtWidgets.QFrame(self.scroll_contents)
        self.optimization_line.setGeometry(QtCore.QRect(0, 330, 684, 2))
        self.optimization_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.optimization_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.optimization_line.setObjectName("optimization_line")
        self.lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.lower_bound_ledit.setGeometry(QtCore.QRect(320, 370, 170, 31))
        self.lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.lower_bound_ledit.setObjectName("lower_bound_ledit")
        self.outcome_model_line = QtWidgets.QFrame(self.scroll_contents)
        self.outcome_model_line.setGeometry(QtCore.QRect(0, 470, 684, 2))
        self.outcome_model_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.outcome_model_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outcome_model_line.setObjectName("outcome_model_line")
        self.outcome_model_label = QtWidgets.QLabel(self.scroll_contents)
        self.outcome_model_label.setGeometry(QtCore.QRect(0, 430, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outcome_model_label.setFont(font)
        self.outcome_model_label.setStyleSheet("border: 0px solid;")
        self.outcome_model_label.setObjectName("outcome_model_label")
        self.model_label_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.model_label_ledit.setGeometry(QtCore.QRect(0, 510, 381, 31))
        self.model_label_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.model_label_ledit.setObjectName("model_label_ledit")
        self.model_label_label = QtWidgets.QLabel(self.scroll_contents)
        self.model_label_label.setGeometry(QtCore.QRect(0, 480, 381, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.model_label_label.setFont(font)
        self.model_label_label.setStyleSheet("border: 0px solid;")
        self.model_label_label.setObjectName("model_label_label")
        self.model_path_label = QtWidgets.QLabel(self.scroll_contents)
        self.model_path_label.setGeometry(QtCore.QRect(400, 480, 281, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.model_path_label.setFont(font)
        self.model_path_label.setStyleSheet("border: 0px solid;")
        self.model_path_label.setObjectName("model_path_label")
        self.model_path_tbutton = QtWidgets.QToolButton(self.scroll_contents)
        self.model_path_tbutton.setGeometry(QtCore.QRect(650, 510, 31, 31))
        self.model_path_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.model_path_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/black_icons/icons_black/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_path_tbutton.setIcon(icon)
        self.model_path_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.model_path_tbutton.setObjectName("model_path_tbutton")
        self.model_path_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.model_path_ledit.setGeometry(QtCore.QRect(400, 510, 241, 31))
        self.model_path_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.model_path_ledit.setObjectName("model_path_ledit")
        self.data_path_tbutton = QtWidgets.QToolButton(self.scroll_contents)
        self.data_path_tbutton.setGeometry(QtCore.QRect(650, 580, 31, 31))
        self.data_path_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.data_path_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.data_path_tbutton.setIcon(icon)
        self.data_path_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.data_path_tbutton.setObjectName("data_path_tbutton")
        self.data_path_label = QtWidgets.QLabel(self.scroll_contents)
        self.data_path_label.setGeometry(QtCore.QRect(0, 550, 681, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.data_path_label.setFont(font)
        self.data_path_label.setStyleSheet("border: 0px solid;")
        self.data_path_label.setObjectName("data_path_label")
        self.data_path_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.data_path_ledit.setGeometry(QtCore.QRect(0, 580, 641, 31))
        self.data_path_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.data_path_ledit.setObjectName("data_path_ledit")
        self.data_handling_label = QtWidgets.QLabel(self.scroll_contents)
        self.data_handling_label.setGeometry(QtCore.QRect(0, 630, 681, 31))
        self.data_handling_label.setStyleSheet("border: 0px solid;\n"
"color: rgb(85, 87, 83);")
        self.data_handling_label.setObjectName("data_handling_label")
        self.modeling_label = QtWidgets.QLabel(self.scroll_contents)
        self.modeling_label.setGeometry(QtCore.QRect(0, 750, 681, 31))
        self.modeling_label.setStyleSheet("border: 0px solid;\n"
"color: rgb(85, 87, 83);")
        self.modeling_label.setObjectName("modeling_label")
        self.prep_steps_label = QtWidgets.QLabel(self.scroll_contents)
        self.prep_steps_label.setGeometry(QtCore.QRect(0, 790, 681, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prep_steps_label.setFont(font)
        self.prep_steps_label.setStyleSheet("border: 0px solid;")
        self.prep_steps_label.setObjectName("prep_steps_label")
        self.prep_steps_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.prep_steps_ledit.setGeometry(QtCore.QRect(0, 820, 681, 31))
        self.prep_steps_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.prep_steps_ledit.setObjectName("prep_steps_ledit")
        self.tune_eval_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.tune_eval_sbox.setGeometry(QtCore.QRect(0, 1170, 121, 31))
        self.tune_eval_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tune_eval_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.tune_eval_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.tune_eval_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.tune_eval_sbox.setMinimum(1)
        self.tune_eval_sbox.setMaximum(100000)
        self.tune_eval_sbox.setProperty("value", 50)
        self.tune_eval_sbox.setObjectName("tune_eval_sbox")
        self.tune_eval_label = QtWidgets.QLabel(self.scroll_contents)
        self.tune_eval_label.setGeometry(QtCore.QRect(0, 1140, 131, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tune_eval_label.setFont(font)
        self.tune_eval_label.setStyleSheet("border: 0px solid;")
        self.tune_eval_label.setObjectName("tune_eval_label")
        self.tune_score_cbox = QtWidgets.QComboBox(self.scroll_contents)
        self.tune_score_cbox.setGeometry(QtCore.QRect(140, 1170, 121, 31))
        self.tune_score_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tune_score_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.tune_score_cbox.setObjectName("tune_score_cbox")
        self.tune_score_label = QtWidgets.QLabel(self.scroll_contents)
        self.tune_score_label.setGeometry(QtCore.QRect(140, 1140, 141, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tune_score_label.setFont(font)
        self.tune_score_label.setStyleSheet("border: 0px solid;")
        self.tune_score_label.setObjectName("tune_score_label")
        self.tune_splits_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.tune_splits_sbox.setGeometry(QtCore.QRect(280, 1170, 81, 31))
        self.tune_splits_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tune_splits_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.tune_splits_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.tune_splits_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.tune_splits_sbox.setMinimum(1)
        self.tune_splits_sbox.setMaximum(100)
        self.tune_splits_sbox.setProperty("value", 5)
        self.tune_splits_sbox.setObjectName("tune_splits_sbox")
        self.tune_splits_label = QtWidgets.QLabel(self.scroll_contents)
        self.tune_splits_label.setGeometry(QtCore.QRect(280, 1140, 91, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tune_splits_label.setFont(font)
        self.tune_splits_label.setStyleSheet("border: 0px solid;")
        self.tune_splits_label.setObjectName("tune_splits_label")
        self.visualization_label = QtWidgets.QLabel(self.scroll_contents)
        self.visualization_label.setGeometry(QtCore.QRect(0, 1250, 681, 31))
        self.visualization_label.setStyleSheet("border: 0px solid;\n"
"color: rgb(85, 87, 83);")
        self.visualization_label.setObjectName("visualization_label")
        self.oof_splits_label = QtWidgets.QLabel(self.scroll_contents)
        self.oof_splits_label.setGeometry(QtCore.QRect(490, 1140, 91, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.oof_splits_label.setFont(font)
        self.oof_splits_label.setStyleSheet("border: 0px solid;")
        self.oof_splits_label.setObjectName("oof_splits_label")
        self.oof_splits_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.oof_splits_sbox.setGeometry(QtCore.QRect(490, 1170, 81, 31))
        self.oof_splits_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.oof_splits_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.oof_splits_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.oof_splits_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.oof_splits_sbox.setMinimum(1)
        self.oof_splits_sbox.setMaximum(100)
        self.oof_splits_sbox.setProperty("value", 5)
        self.oof_splits_sbox.setObjectName("oof_splits_sbox")
        self.write_features_check = QtWidgets.QCheckBox(self.scroll_contents)
        self.write_features_check.setGeometry(QtCore.QRect(0, 1210, 141, 23))
        self.write_features_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.write_features_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.write_features_check.setObjectName("write_features_check")
        self.graphs_label = QtWidgets.QLabel(self.scroll_contents)
        self.graphs_label.setGeometry(QtCore.QRect(0, 1290, 241, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.graphs_label.setFont(font)
        self.graphs_label.setStyleSheet("border: 0px solid;")
        self.graphs_label.setObjectName("graphs_label")
        self.kpi_label = QtWidgets.QLabel(self.scroll_contents)
        self.kpi_label.setGeometry(QtCore.QRect(280, 1290, 401, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.kpi_label.setFont(font)
        self.kpi_label.setStyleSheet("border: 0px solid;")
        self.kpi_label.setObjectName("kpi_label")
        self.inspect_model_check = QtWidgets.QCheckBox(self.scroll_contents)
        self.inspect_model_check.setGeometry(QtCore.QRect(150, 1210, 141, 23))
        self.inspect_model_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inspect_model_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.inspect_model_check.setObjectName("inspect_model_check")
        self.evaluate_model_check = QtWidgets.QCheckBox(self.scroll_contents)
        self.evaluate_model_check.setGeometry(QtCore.QRect(300, 1210, 141, 23))
        self.evaluate_model_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.evaluate_model_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.evaluate_model_check.setObjectName("evaluate_model_check")
        self.segment_cbox = QtWidgets.QComboBox(self.scroll_contents)
        self.segment_cbox.setGeometry(QtCore.QRect(0, 90, 426, 31))
        self.segment_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.segment_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.segment_cbox.setObjectName("segment_cbox")
        self.data_columns_tbutton = QtWidgets.QToolButton(self.scroll_contents)
        self.data_columns_tbutton.setGeometry(QtCore.QRect(10, 670, 51, 51))
        self.data_columns_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.data_columns_tbutton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 1px solid;\n"
"border-color: rgb(46, 52, 54);\n"
"color: rgb(238, 238, 236);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/special_icons/icons_special/data-spreadsheet-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.data_columns_tbutton.setIcon(icon1)
        self.data_columns_tbutton.setIconSize(QtCore.QSize(31, 31))
        self.data_columns_tbutton.setObjectName("data_columns_tbutton")
        self.data_columns_label = QtWidgets.QLabel(self.scroll_contents)
        self.data_columns_label.setGeometry(QtCore.QRect(0, 720, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.data_columns_label.setFont(font)
        self.data_columns_label.setStyleSheet("border: 0px solid;\n"
"background: transparent;\n"
"color: rgb(0, 0, 0);")
        self.data_columns_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_columns_label.setObjectName("data_columns_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.scroll_contents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 229, 431, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.segment_link_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.segment_link_layout.setContentsMargins(0, 0, 0, 0)
        self.segment_link_layout.setObjectName("segment_link_layout")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.scroll_contents)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 1320, 261, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.graphs_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.graphs_layout.setContentsMargins(0, 0, 0, 0)
        self.graphs_layout.setObjectName("graphs_layout")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.scroll_contents)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(280, 1320, 401, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.kpi_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.kpi_layout.setContentsMargins(0, 0, 0, 0)
        self.kpi_layout.setObjectName("kpi_layout")
        self.min_weight_frac_leaf_upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.min_weight_frac_leaf_upper_bound_ledit.setGeometry(QtCore.QRect(600, 1000, 81, 31))
        self.min_weight_frac_leaf_upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.min_weight_frac_leaf_upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.min_weight_frac_leaf_upper_bound_ledit.setObjectName("min_weight_frac_leaf_upper_bound_ledit")
        self.max_features_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.max_features_conjunction.setGeometry(QtCore.QRect(232, 1056, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.max_features_conjunction.setFont(font)
        self.max_features_conjunction.setStyleSheet("border: none;")
        self.max_features_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.max_features_conjunction.setObjectName("max_features_conjunction")
        self.splitter_label = QtWidgets.QLabel(self.scroll_contents)
        self.splitter_label.setGeometry(QtCore.QRect(80, 950, 71, 31))
        self.splitter_label.setStyleSheet("border: 0px solid;")
        self.splitter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.splitter_label.setObjectName("splitter_label")
        self.max_depth_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.max_depth_conjunction.setGeometry(QtCore.QRect(582, 906, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.max_depth_conjunction.setFont(font)
        self.max_depth_conjunction.setStyleSheet("border: none;")
        self.max_depth_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.max_depth_conjunction.setObjectName("max_depth_conjunction")
        self.ccp_alpha_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.ccp_alpha_conjunction.setGeometry(QtCore.QRect(232, 1106, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ccp_alpha_conjunction.setFont(font)
        self.ccp_alpha_conjunction.setStyleSheet("border: none;")
        self.ccp_alpha_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.ccp_alpha_conjunction.setObjectName("ccp_alpha_conjunction")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.scroll_contents)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(500, 1050, 181, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.class_weight_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.class_weight_layout.setContentsMargins(0, 0, 0, 0)
        self.class_weight_layout.setObjectName("class_weight_layout")
        self.ccp_alpha_label = QtWidgets.QLabel(self.scroll_contents)
        self.ccp_alpha_label.setGeometry(QtCore.QRect(57, 1100, 91, 31))
        self.ccp_alpha_label.setStyleSheet("border: 0px solid;")
        self.ccp_alpha_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ccp_alpha_label.setObjectName("ccp_alpha_label")
        self.ccp_alpha_upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.ccp_alpha_upper_bound_ledit.setGeometry(QtCore.QRect(250, 1100, 81, 31))
        self.ccp_alpha_upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.ccp_alpha_upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.ccp_alpha_upper_bound_ledit.setObjectName("ccp_alpha_upper_bound_ledit")
        self.min_samples_split_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.min_samples_split_conjunction.setGeometry(QtCore.QRect(582, 956, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.min_samples_split_conjunction.setFont(font)
        self.min_samples_split_conjunction.setStyleSheet("border: none;")
        self.min_samples_split_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.min_samples_split_conjunction.setObjectName("min_samples_split_conjunction")
        self.max_depth_lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.max_depth_lower_bound_ledit.setGeometry(QtCore.QRect(500, 900, 81, 31))
        self.max_depth_lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.max_depth_lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.max_depth_lower_bound_ledit.setObjectName("max_depth_lower_bound_ledit")
        self.max_features_lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.max_features_lower_bound_ledit.setGeometry(QtCore.QRect(150, 1050, 81, 31))
        self.max_features_lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.max_features_lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.max_features_lower_bound_ledit.setObjectName("max_features_lower_bound_ledit")
        self.max_depth_label = QtWidgets.QLabel(self.scroll_contents)
        self.max_depth_label.setGeometry(QtCore.QRect(407, 900, 91, 31))
        self.max_depth_label.setStyleSheet("border: 0px solid;")
        self.max_depth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.max_depth_label.setObjectName("max_depth_label")
        self.min_weight_frac_leaf_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.min_weight_frac_leaf_conjunction.setGeometry(QtCore.QRect(582, 1006, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.min_weight_frac_leaf_conjunction.setFont(font)
        self.min_weight_frac_leaf_conjunction.setStyleSheet("border: none;")
        self.min_weight_frac_leaf_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.min_weight_frac_leaf_conjunction.setObjectName("min_weight_frac_leaf_conjunction")
        self.ccp_alpha_lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.ccp_alpha_lower_bound_ledit.setGeometry(QtCore.QRect(150, 1100, 81, 31))
        self.ccp_alpha_lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.ccp_alpha_lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.ccp_alpha_lower_bound_ledit.setObjectName("ccp_alpha_lower_bound_ledit")
        self.min_samples_split_lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.min_samples_split_lower_bound_ledit.setGeometry(QtCore.QRect(500, 950, 81, 31))
        self.min_samples_split_lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.min_samples_split_lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.min_samples_split_lower_bound_ledit.setObjectName("min_samples_split_lower_bound_ledit")
        self.max_depth_upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.max_depth_upper_bound_ledit.setGeometry(QtCore.QRect(600, 900, 81, 31))
        self.max_depth_upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.max_depth_upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.max_depth_upper_bound_ledit.setObjectName("max_depth_upper_bound_ledit")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.scroll_contents)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(150, 950, 181, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.splitter_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.splitter_layout.setContentsMargins(0, 0, 0, 0)
        self.splitter_layout.setObjectName("splitter_layout")
        self.min_weight_frac_leaf_label = QtWidgets.QLabel(self.scroll_contents)
        self.min_weight_frac_leaf_label.setGeometry(QtCore.QRect(351, 1000, 141, 31))
        self.min_weight_frac_leaf_label.setStyleSheet("border: 0px solid;")
        self.min_weight_frac_leaf_label.setAlignment(QtCore.Qt.AlignCenter)
        self.min_weight_frac_leaf_label.setObjectName("min_weight_frac_leaf_label")
        self.min_samples_leaf_label = QtWidgets.QLabel(self.scroll_contents)
        self.min_samples_leaf_label.setGeometry(QtCore.QRect(17, 1000, 131, 31))
        self.min_samples_leaf_label.setStyleSheet("border: 0px solid;")
        self.min_samples_leaf_label.setAlignment(QtCore.Qt.AlignCenter)
        self.min_samples_leaf_label.setObjectName("min_samples_leaf_label")
        self.min_weight_frac_leaf_lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.min_weight_frac_leaf_lower_bound_ledit.setGeometry(QtCore.QRect(500, 1000, 81, 31))
        self.min_weight_frac_leaf_lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.min_weight_frac_leaf_lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.min_weight_frac_leaf_lower_bound_ledit.setObjectName("min_weight_frac_leaf_lower_bound_ledit")
        self.criterion_label = QtWidgets.QLabel(self.scroll_contents)
        self.criterion_label.setGeometry(QtCore.QRect(75, 900, 71, 31))
        self.criterion_label.setStyleSheet("border: 0px solid;")
        self.criterion_label.setAlignment(QtCore.Qt.AlignCenter)
        self.criterion_label.setObjectName("criterion_label")
        self.min_samples_split_upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.min_samples_split_upper_bound_ledit.setGeometry(QtCore.QRect(600, 950, 81, 31))
        self.min_samples_split_upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.min_samples_split_upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.min_samples_split_upper_bound_ledit.setObjectName("min_samples_split_upper_bound_ledit")
        self.max_features_upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.max_features_upper_bound_ledit.setGeometry(QtCore.QRect(250, 1050, 81, 31))
        self.max_features_upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.max_features_upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.max_features_upper_bound_ledit.setObjectName("max_features_upper_bound_ledit")
        self.tune_space_label = QtWidgets.QLabel(self.scroll_contents)
        self.tune_space_label.setGeometry(QtCore.QRect(0, 860, 681, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tune_space_label.setFont(font)
        self.tune_space_label.setStyleSheet("border: 0px solid;")
        self.tune_space_label.setObjectName("tune_space_label")
        self.class_weight_label = QtWidgets.QLabel(self.scroll_contents)
        self.class_weight_label.setGeometry(QtCore.QRect(401, 1050, 91, 31))
        self.class_weight_label.setStyleSheet("border: 0px solid;")
        self.class_weight_label.setAlignment(QtCore.Qt.AlignCenter)
        self.class_weight_label.setObjectName("class_weight_label")
        self.min_samples_leaf_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.min_samples_leaf_conjunction.setGeometry(QtCore.QRect(232, 1006, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.min_samples_leaf_conjunction.setFont(font)
        self.min_samples_leaf_conjunction.setStyleSheet("border: none;")
        self.min_samples_leaf_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.min_samples_leaf_conjunction.setObjectName("min_samples_leaf_conjunction")
        self.max_features_label = QtWidgets.QLabel(self.scroll_contents)
        self.max_features_label.setGeometry(QtCore.QRect(37, 1050, 111, 31))
        self.max_features_label.setStyleSheet("border: 0px solid;")
        self.max_features_label.setAlignment(QtCore.Qt.AlignCenter)
        self.max_features_label.setObjectName("max_features_label")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.scroll_contents)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(150, 900, 181, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.criterion_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.criterion_layout.setContentsMargins(0, 0, 0, 0)
        self.criterion_layout.setObjectName("criterion_layout")
        self.min_samples_leaf_upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.min_samples_leaf_upper_bound_ledit.setGeometry(QtCore.QRect(250, 1000, 81, 31))
        self.min_samples_leaf_upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.min_samples_leaf_upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.min_samples_leaf_upper_bound_ledit.setObjectName("min_samples_leaf_upper_bound_ledit")
        self.min_samples_split_label = QtWidgets.QLabel(self.scroll_contents)
        self.min_samples_split_label.setGeometry(QtCore.QRect(365, 950, 131, 31))
        self.min_samples_split_label.setStyleSheet("border: 0px solid;")
        self.min_samples_split_label.setAlignment(QtCore.Qt.AlignCenter)
        self.min_samples_split_label.setObjectName("min_samples_split_label")
        self.min_samples_leaf_lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.min_samples_leaf_lower_bound_ledit.setGeometry(QtCore.QRect(150, 1000, 81, 31))
        self.min_samples_leaf_lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.min_samples_leaf_lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.min_samples_leaf_lower_bound_ledit.setObjectName("min_samples_leaf_lower_bound_ledit")
        self.oof_repeats_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.oof_repeats_sbox.setGeometry(QtCore.QRect(590, 1170, 91, 31))
        self.oof_repeats_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.oof_repeats_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.oof_repeats_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.oof_repeats_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.oof_repeats_sbox.setMinimum(1)
        self.oof_repeats_sbox.setMaximum(100)
        self.oof_repeats_sbox.setProperty("value", 1)
        self.oof_repeats_sbox.setObjectName("oof_repeats_sbox")
        self.tune_repeats_label = QtWidgets.QLabel(self.scroll_contents)
        self.tune_repeats_label.setGeometry(QtCore.QRect(380, 1140, 101, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tune_repeats_label.setFont(font)
        self.tune_repeats_label.setStyleSheet("border: 0px solid;")
        self.tune_repeats_label.setObjectName("tune_repeats_label")
        self.oof_repeats_label = QtWidgets.QLabel(self.scroll_contents)
        self.oof_repeats_label.setGeometry(QtCore.QRect(590, 1140, 101, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.oof_repeats_label.setFont(font)
        self.oof_repeats_label.setStyleSheet("border: 0px solid;")
        self.oof_repeats_label.setObjectName("oof_repeats_label")
        self.tune_repeats_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.tune_repeats_sbox.setGeometry(QtCore.QRect(380, 1170, 91, 31))
        self.tune_repeats_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tune_repeats_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.tune_repeats_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.tune_repeats_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.tune_repeats_sbox.setMinimum(1)
        self.tune_repeats_sbox.setMaximum(100)
        self.tune_repeats_sbox.setProperty("value", 1)
        self.tune_repeats_sbox.setObjectName("tune_repeats_sbox")
        self.scroll_area.setWidget(self.scroll_contents)
        decision_tree_ntcp_window.setCentralWidget(self.body_widget)

        self.retranslateUi(decision_tree_ntcp_window)
        self.embedding_cbox.setCurrentIndex(0)
        self.type_cbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(decision_tree_ntcp_window)

    def retranslateUi(self, decision_tree_ntcp_window):
        _translate = QtCore.QCoreApplication.translate
        decision_tree_ntcp_window.setWindowTitle(_translate("decision_tree_ntcp_window", "Decision Tree NTCP Editor"))
        self.embedding_cbox.setItemText(0, _translate("decision_tree_ntcp_window", "active"))
        self.embedding_cbox.setItemText(1, _translate("decision_tree_ntcp_window", "passive"))
        self.segment_label.setText(_translate("decision_tree_ntcp_window", "Segment"))
        self.embedding_label.setText(_translate("decision_tree_ntcp_window", "Embedding"))
        self.base_label.setText(_translate("decision_tree_ntcp_window", "Base"))
        self.type_cbox.setItemText(0, _translate("decision_tree_ntcp_window", "objective"))
        self.type_cbox.setItemText(1, _translate("decision_tree_ntcp_window", "constraint"))
        self.type_label.setText(_translate("decision_tree_ntcp_window", "Type"))
        self.close_pbutton.setText(_translate("decision_tree_ntcp_window", "Close"))
        self.identifier_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "None"))
        self.identifier_label.setText(_translate("decision_tree_ntcp_window", "Identifier"))
        self.link_label.setText(_translate("decision_tree_ntcp_window", "Link"))
        self.function_label.setText(_translate("decision_tree_ntcp_window", "Function"))
        self.bounds_label.setText(_translate("decision_tree_ntcp_window", "Bounds"))
        self.handling_viz_label.setText(_translate("decision_tree_ntcp_window", "Handling & Visualization"))
        self.weight_label.setText(_translate("decision_tree_ntcp_window", "Weight"))
        self.save_pbutton.setText(_translate("decision_tree_ntcp_window", "Save"))
        self.opt_bounds_conjunction.setText(_translate("decision_tree_ntcp_window", "-"))
        self.optimization_label.setText(_translate("decision_tree_ntcp_window", "Optimization"))
        self.rank_label.setText(_translate("decision_tree_ntcp_window", "Rank"))
        self.upper_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "1.0"))
        self.weight_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "1.0"))
        self.disp_component_check.setText(_translate("decision_tree_ntcp_window", "Display component"))
        self.lower_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "0.0"))
        self.outcome_model_label.setText(_translate("decision_tree_ntcp_window", "Outcome model"))
        self.model_label_label.setText(_translate("decision_tree_ntcp_window", "Model label"))
        self.model_path_label.setText(_translate("decision_tree_ntcp_window", "Model path"))
        self.model_path_tbutton.setToolTip(_translate("decision_tree_ntcp_window", "Add the model data from a folder"))
        self.model_path_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "None"))
        self.data_path_tbutton.setToolTip(_translate("decision_tree_ntcp_window", "Add the outcome data from a folder"))
        self.data_path_label.setText(_translate("decision_tree_ntcp_window", "Data path"))
        self.data_handling_label.setText(_translate("decision_tree_ntcp_window", "DATA HANDLING"))
        self.modeling_label.setText(_translate("decision_tree_ntcp_window", "MODEL FITTING, INSPECTION & EVALUATION"))
        self.prep_steps_label.setText(_translate("decision_tree_ntcp_window", "Preprocessing steps"))
        self.prep_steps_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "[Identity]"))
        self.tune_eval_label.setText(_translate("decision_tree_ntcp_window", "Tune evaluations"))
        self.tune_score_label.setText(_translate("decision_tree_ntcp_window", "Tune score"))
        self.tune_splits_label.setText(_translate("decision_tree_ntcp_window", "Tune splits"))
        self.visualization_label.setText(_translate("decision_tree_ntcp_window", "VISUALIZATION"))
        self.oof_splits_label.setText(_translate("decision_tree_ntcp_window", "OOF splits"))
        self.write_features_check.setText(_translate("decision_tree_ntcp_window", "Write features"))
        self.graphs_label.setText(_translate("decision_tree_ntcp_window", "Graphs"))
        self.kpi_label.setText(_translate("decision_tree_ntcp_window", "KPIs"))
        self.inspect_model_check.setText(_translate("decision_tree_ntcp_window", "Inspect model"))
        self.evaluate_model_check.setText(_translate("decision_tree_ntcp_window", "Evaluate model"))
        self.data_columns_tbutton.setToolTip(_translate("decision_tree_ntcp_window", "Open the data columns window"))
        self.data_columns_label.setText(_translate("decision_tree_ntcp_window", "Data columns"))
        self.min_weight_frac_leaf_upper_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "0.5"))
        self.max_features_conjunction.setText(_translate("decision_tree_ntcp_window", "-"))
        self.splitter_label.setText(_translate("decision_tree_ntcp_window", "splitter"))
        self.max_depth_conjunction.setText(_translate("decision_tree_ntcp_window", "-"))
        self.ccp_alpha_conjunction.setText(_translate("decision_tree_ntcp_window", "-"))
        self.ccp_alpha_label.setText(_translate("decision_tree_ntcp_window", "ccp_alpha"))
        self.ccp_alpha_upper_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "1.0"))
        self.min_samples_split_conjunction.setText(_translate("decision_tree_ntcp_window", "-"))
        self.max_depth_lower_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "5"))
        self.max_features_lower_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "|features|"))
        self.max_depth_label.setText(_translate("decision_tree_ntcp_window", "max depth"))
        self.min_weight_frac_leaf_conjunction.setText(_translate("decision_tree_ntcp_window", "-"))
        self.ccp_alpha_lower_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "0.0"))
        self.min_samples_split_lower_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "0.0"))
        self.max_depth_upper_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "5"))
        self.min_weight_frac_leaf_label.setText(_translate("decision_tree_ntcp_window", "min weight frac leaf"))
        self.min_samples_leaf_label.setText(_translate("decision_tree_ntcp_window", "min samples leaf"))
        self.min_weight_frac_leaf_lower_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "0.0"))
        self.criterion_label.setText(_translate("decision_tree_ntcp_window", "criterion"))
        self.min_samples_split_upper_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "1.0"))
        self.max_features_upper_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "|features|"))
        self.tune_space_label.setText(_translate("decision_tree_ntcp_window", "Tune space"))
        self.class_weight_label.setText(_translate("decision_tree_ntcp_window", "class weight"))
        self.min_samples_leaf_conjunction.setText(_translate("decision_tree_ntcp_window", "-"))
        self.max_features_label.setText(_translate("decision_tree_ntcp_window", "max features"))
        self.min_samples_leaf_upper_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "0.5"))
        self.min_samples_split_label.setText(_translate("decision_tree_ntcp_window", "min samples split"))
        self.min_samples_leaf_lower_bound_ledit.setPlaceholderText(_translate("decision_tree_ntcp_window", "0.0"))
        self.tune_repeats_label.setText(_translate("decision_tree_ntcp_window", "Tune repeats"))
        self.oof_repeats_label.setText(_translate("decision_tree_ntcp_window", "OOF repeats"))
