# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'k_nearest_neighbors_ntcp_window.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_k_nearest_neighbors_ntcp_window(object):
    def setupUi(self, k_nearest_neighbors_ntcp_window):
        k_nearest_neighbors_ntcp_window.setObjectName("k_nearest_neighbors_ntcp_window")
        k_nearest_neighbors_ntcp_window.setWindowModality(QtCore.Qt.ApplicationModal)
        k_nearest_neighbors_ntcp_window.resize(720, 431)
        k_nearest_neighbors_ntcp_window.setMinimumSize(QtCore.QSize(720, 431))
        k_nearest_neighbors_ntcp_window.setMaximumSize(QtCore.QSize(720, 431))
        k_nearest_neighbors_ntcp_window.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);")
        self.body_widget = QtWidgets.QWidget(k_nearest_neighbors_ntcp_window)
        self.body_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(211, 215, 207);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.body_widget.setObjectName("body_widget")
        self.scroll_area = QtWidgets.QScrollArea(self.body_widget)
        self.scroll_area.setGeometry(QtCore.QRect(10, 0, 711, 431))
        self.scroll_area.setStyleSheet("border-color: transparent;")
        self.scroll_area.setWidgetResizable(False)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_contents = QtWidgets.QWidget()
        self.scroll_contents.setGeometry(QtCore.QRect(0, -1200, 690, 1861))
        self.scroll_contents.setObjectName("scroll_contents")
        self.embedding_cbox = QtWidgets.QComboBox(self.scroll_contents)
        self.embedding_cbox.setGeometry(QtCore.QRect(574, 100, 111, 31))
        self.embedding_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.embedding_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.embedding_cbox.setObjectName("embedding_cbox")
        self.embedding_cbox.addItem("")
        self.embedding_cbox.addItem("")
        self.segment_label = QtWidgets.QLabel(self.scroll_contents)
        self.segment_label.setGeometry(QtCore.QRect(0, 60, 431, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.segment_label.setFont(font)
        self.segment_label.setStyleSheet("border: 0px solid;")
        self.segment_label.setObjectName("segment_label")
        self.embedding_label = QtWidgets.QLabel(self.scroll_contents)
        self.embedding_label.setGeometry(QtCore.QRect(575, 60, 109, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.embedding_label.setFont(font)
        self.embedding_label.setStyleSheet("border: 0px solid;")
        self.embedding_label.setObjectName("embedding_label")
        self.base_label = QtWidgets.QLabel(self.scroll_contents)
        self.base_label.setGeometry(QtCore.QRect(0, 10, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.base_label.setFont(font)
        self.base_label.setStyleSheet("border: 0px solid;")
        self.base_label.setObjectName("base_label")
        self.type_cbox = QtWidgets.QComboBox(self.scroll_contents)
        self.type_cbox.setGeometry(QtCore.QRect(445, 100, 111, 31))
        self.type_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.type_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.type_cbox.setObjectName("type_cbox")
        self.type_cbox.addItem("")
        self.type_cbox.addItem("")
        self.base_line = QtWidgets.QFrame(self.scroll_contents)
        self.base_line.setGeometry(QtCore.QRect(0, 50, 684, 2))
        self.base_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.base_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.base_line.setObjectName("base_line")
        self.segment_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.segment_ledit.setGeometry(QtCore.QRect(0, 100, 426, 31))
        self.segment_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.segment_ledit.setObjectName("segment_ledit")
        self.type_label = QtWidgets.QLabel(self.scroll_contents)
        self.type_label.setGeometry(QtCore.QRect(445, 60, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.type_label.setFont(font)
        self.type_label.setStyleSheet("border: 0px solid;")
        self.type_label.setObjectName("type_label")
        self.close_component_pbutton = QtWidgets.QPushButton(self.scroll_contents)
        self.close_component_pbutton.setGeometry(QtCore.QRect(614, 1820, 71, 31))
        self.close_component_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_component_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.close_component_pbutton.setObjectName("close_component_pbutton")
        self.identifier_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.identifier_ledit.setGeometry(QtCore.QRect(0, 1730, 381, 31))
        self.identifier_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.identifier_ledit.setObjectName("identifier_ledit")
        self.rank_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.rank_sbox.setGeometry(QtCore.QRect(190, 400, 111, 31))
        self.rank_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.rank_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.rank_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.rank_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.rank_sbox.setMinimum(1)
        self.rank_sbox.setMaximum(1000)
        self.rank_sbox.setProperty("value", 1)
        self.rank_sbox.setObjectName("rank_sbox")
        self.identifier_label = QtWidgets.QLabel(self.scroll_contents)
        self.identifier_label.setGeometry(QtCore.QRect(0, 1690, 381, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.identifier_label.setFont(font)
        self.identifier_label.setStyleSheet("border: 0px solid;")
        self.identifier_label.setObjectName("identifier_label")
        self.link_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.link_ledit.setGeometry(QtCore.QRect(0, 250, 494, 31))
        self.link_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.link_ledit.setObjectName("link_ledit")
        self.link_label = QtWidgets.QLabel(self.scroll_contents)
        self.link_label.setGeometry(QtCore.QRect(0, 210, 494, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.link_label.setFont(font)
        self.link_label.setStyleSheet("border: none;")
        self.link_label.setObjectName("link_label")
        self.function_label = QtWidgets.QLabel(self.scroll_contents)
        self.function_label.setGeometry(QtCore.QRect(0, 160, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.function_label.setFont(font)
        self.function_label.setStyleSheet("border: 0px solid;")
        self.function_label.setObjectName("function_label")
        self.bounds_label = QtWidgets.QLabel(self.scroll_contents)
        self.bounds_label.setGeometry(QtCore.QRect(323, 360, 364, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bounds_label.setFont(font)
        self.bounds_label.setStyleSheet("border: 0px solid;")
        self.bounds_label.setObjectName("bounds_label")
        self.handling_viz_label = QtWidgets.QLabel(self.scroll_contents)
        self.handling_viz_label.setGeometry(QtCore.QRect(0, 1640, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.handling_viz_label.setFont(font)
        self.handling_viz_label.setStyleSheet("border: 0px solid;")
        self.handling_viz_label.setObjectName("handling_viz_label")
        self.weight_label = QtWidgets.QLabel(self.scroll_contents)
        self.weight_label.setGeometry(QtCore.QRect(0, 360, 171, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.weight_label.setFont(font)
        self.weight_label.setStyleSheet("border: 0px solid;")
        self.weight_label.setObjectName("weight_label")
        self.save_component_pbutton = QtWidgets.QPushButton(self.scroll_contents)
        self.save_component_pbutton.setGeometry(QtCore.QRect(534, 1820, 71, 31))
        self.save_component_pbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_component_pbutton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.save_component_pbutton.setObjectName("save_component_pbutton")
        self.function_line = QtWidgets.QFrame(self.scroll_contents)
        self.function_line.setGeometry(QtCore.QRect(0, 200, 684, 2))
        self.function_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.function_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.function_line.setObjectName("function_line")
        self.opt_bounds_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.opt_bounds_conjunction.setGeometry(QtCore.QRect(494, 405, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.opt_bounds_conjunction.setFont(font)
        self.opt_bounds_conjunction.setStyleSheet("border: none;")
        self.opt_bounds_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.opt_bounds_conjunction.setObjectName("opt_bounds_conjunction")
        self.optimization_label = QtWidgets.QLabel(self.scroll_contents)
        self.optimization_label.setGeometry(QtCore.QRect(0, 310, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.optimization_label.setFont(font)
        self.optimization_label.setStyleSheet("border: 0px solid;")
        self.optimization_label.setObjectName("optimization_label")
        self.rank_label = QtWidgets.QLabel(self.scroll_contents)
        self.rank_label.setGeometry(QtCore.QRect(190, 360, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rank_label.setFont(font)
        self.rank_label.setStyleSheet("border: 0px solid;")
        self.rank_label.setObjectName("rank_label")
        self.upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.upper_bound_ledit.setGeometry(QtCore.QRect(515, 400, 170, 31))
        self.upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.upper_bound_ledit.setObjectName("upper_bound_ledit")
        self.weight_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.weight_ledit.setGeometry(QtCore.QRect(0, 400, 171, 31))
        self.weight_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.weight_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.weight_ledit.setObjectName("weight_ledit")
        self.disp_component_check = QtWidgets.QCheckBox(self.scroll_contents)
        self.disp_component_check.setGeometry(QtCore.QRect(0, 1780, 231, 23))
        self.disp_component_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.disp_component_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.disp_component_check.setChecked(True)
        self.disp_component_check.setObjectName("disp_component_check")
        self.handling_viz_line = QtWidgets.QFrame(self.scroll_contents)
        self.handling_viz_line.setGeometry(QtCore.QRect(0, 1680, 684, 2))
        self.handling_viz_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.handling_viz_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.handling_viz_line.setObjectName("handling_viz_line")
        self.optimization_line = QtWidgets.QFrame(self.scroll_contents)
        self.optimization_line.setGeometry(QtCore.QRect(0, 350, 684, 2))
        self.optimization_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.optimization_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.optimization_line.setObjectName("optimization_line")
        self.lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.lower_bound_ledit.setGeometry(QtCore.QRect(320, 400, 170, 31))
        self.lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.lower_bound_ledit.setObjectName("lower_bound_ledit")
        self.outcome_model_line = QtWidgets.QFrame(self.scroll_contents)
        self.outcome_model_line.setGeometry(QtCore.QRect(0, 500, 684, 2))
        self.outcome_model_line.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.outcome_model_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outcome_model_line.setObjectName("outcome_model_line")
        self.outcome_model_label = QtWidgets.QLabel(self.scroll_contents)
        self.outcome_model_label.setGeometry(QtCore.QRect(0, 460, 684, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outcome_model_label.setFont(font)
        self.outcome_model_label.setStyleSheet("border: 0px solid;")
        self.outcome_model_label.setObjectName("outcome_model_label")
        self.model_label_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.model_label_ledit.setGeometry(QtCore.QRect(0, 550, 381, 31))
        self.model_label_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.model_label_ledit.setObjectName("model_label_ledit")
        self.model_label_label = QtWidgets.QLabel(self.scroll_contents)
        self.model_label_label.setGeometry(QtCore.QRect(0, 510, 381, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.model_label_label.setFont(font)
        self.model_label_label.setStyleSheet("border: 0px solid;")
        self.model_label_label.setObjectName("model_label_label")
        self.model_path_label = QtWidgets.QLabel(self.scroll_contents)
        self.model_path_label.setGeometry(QtCore.QRect(400, 510, 281, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.model_path_label.setFont(font)
        self.model_path_label.setStyleSheet("border: 0px solid;")
        self.model_path_label.setObjectName("model_path_label")
        self.model_path_tbutton = QtWidgets.QToolButton(self.scroll_contents)
        self.model_path_tbutton.setGeometry(QtCore.QRect(650, 550, 30, 30))
        self.model_path_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.model_path_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/black_icons/icons_black/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_path_tbutton.setIcon(icon)
        self.model_path_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.model_path_tbutton.setObjectName("model_path_tbutton")
        self.model_path_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.model_path_ledit.setGeometry(QtCore.QRect(400, 550, 241, 30))
        self.model_path_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.model_path_ledit.setObjectName("model_path_ledit")
        self.data_path_tbutton = QtWidgets.QToolButton(self.scroll_contents)
        self.data_path_tbutton.setGeometry(QtCore.QRect(650, 630, 30, 30))
        self.data_path_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.data_path_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.data_path_tbutton.setIcon(icon)
        self.data_path_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.data_path_tbutton.setObjectName("data_path_tbutton")
        self.data_path_label = QtWidgets.QLabel(self.scroll_contents)
        self.data_path_label.setGeometry(QtCore.QRect(0, 590, 681, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.data_path_label.setFont(font)
        self.data_path_label.setStyleSheet("border: 0px solid;")
        self.data_path_label.setObjectName("data_path_label")
        self.data_path_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.data_path_ledit.setGeometry(QtCore.QRect(0, 630, 641, 30))
        self.data_path_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.data_path_ledit.setObjectName("data_path_ledit")
        self.features_label = QtWidgets.QLabel(self.scroll_contents)
        self.features_label.setGeometry(QtCore.QRect(0, 720, 551, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.features_label.setFont(font)
        self.features_label.setStyleSheet("border: 0px solid;")
        self.features_label.setObjectName("features_label")
        self.data_filter_label = QtWidgets.QLabel(self.scroll_contents)
        self.data_filter_label.setGeometry(QtCore.QRect(0, 680, 681, 31))
        self.data_filter_label.setStyleSheet("border: 0px solid;\n"
"color: rgb(85, 87, 83);")
        self.data_filter_label.setObjectName("data_filter_label")
        self.filter_mode_cbox = QtWidgets.QComboBox(self.scroll_contents)
        self.filter_mode_cbox.setGeometry(QtCore.QRect(570, 760, 111, 31))
        self.filter_mode_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.filter_mode_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.filter_mode_cbox.setObjectName("filter_mode_cbox")
        self.filter_mode_cbox.addItem("")
        self.filter_mode_cbox.addItem("")
        self.filter_mode_label = QtWidgets.QLabel(self.scroll_contents)
        self.filter_mode_label.setGeometry(QtCore.QRect(570, 720, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.filter_mode_label.setFont(font)
        self.filter_mode_label.setStyleSheet("border: 0px solid;")
        self.filter_mode_label.setObjectName("filter_mode_label")
        self.label_name_label = QtWidgets.QLabel(self.scroll_contents)
        self.label_name_label.setGeometry(QtCore.QRect(0, 840, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_name_label.setFont(font)
        self.label_name_label.setStyleSheet("border: 0px solid;")
        self.label_name_label.setObjectName("label_name_label")
        self.label_name_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.label_name_ledit.setGeometry(QtCore.QRect(0, 880, 301, 31))
        self.label_name_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.label_name_ledit.setObjectName("label_name_ledit")
        self.label_lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.label_lower_bound_ledit.setGeometry(QtCore.QRect(315, 880, 170, 31))
        self.label_lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.label_lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lower_bound_ledit.setObjectName("label_lower_bound_ledit")
        self.label_bounds_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.label_bounds_conjunction.setGeometry(QtCore.QRect(489, 885, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_bounds_conjunction.setFont(font)
        self.label_bounds_conjunction.setStyleSheet("border: none;")
        self.label_bounds_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bounds_conjunction.setObjectName("label_bounds_conjunction")
        self.label_bounds_label = QtWidgets.QLabel(self.scroll_contents)
        self.label_bounds_label.setGeometry(QtCore.QRect(318, 840, 364, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_bounds_label.setFont(font)
        self.label_bounds_label.setStyleSheet("border: 0px solid;")
        self.label_bounds_label.setObjectName("label_bounds_label")
        self.label_upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.label_upper_bound_ledit.setGeometry(QtCore.QRect(510, 880, 170, 31))
        self.label_upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.label_upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_upper_bound_ledit.setObjectName("label_upper_bound_ledit")
        self.time_variable_label = QtWidgets.QLabel(self.scroll_contents)
        self.time_variable_label.setGeometry(QtCore.QRect(0, 920, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.time_variable_label.setFont(font)
        self.time_variable_label.setStyleSheet("border: 0px solid;")
        self.time_variable_label.setObjectName("time_variable_label")
        self.time_variable_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.time_variable_ledit.setGeometry(QtCore.QRect(0, 960, 301, 31))
        self.time_variable_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.time_variable_ledit.setObjectName("time_variable_ledit")
        self.label_viewpoint_cbox = QtWidgets.QComboBox(self.scroll_contents)
        self.label_viewpoint_cbox.setGeometry(QtCore.QRect(320, 960, 131, 31))
        self.label_viewpoint_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_viewpoint_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.label_viewpoint_cbox.setObjectName("label_viewpoint_cbox")
        self.label_viewpoint_cbox.addItem("")
        self.label_viewpoint_cbox.addItem("")
        self.label_viewpoint_cbox.addItem("")
        self.label_viewpoint_cbox.addItem("")
        self.label_viewpoint_cbox.addItem("")
        self.label_viewpoint_label = QtWidgets.QLabel(self.scroll_contents)
        self.label_viewpoint_label.setGeometry(QtCore.QRect(320, 920, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_viewpoint_label.setFont(font)
        self.label_viewpoint_label.setStyleSheet("border: 0px solid;")
        self.label_viewpoint_label.setObjectName("label_viewpoint_label")
        self.fuzzy_matching_check = QtWidgets.QCheckBox(self.scroll_contents)
        self.fuzzy_matching_check.setGeometry(QtCore.QRect(0, 1050, 231, 23))
        self.fuzzy_matching_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fuzzy_matching_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.fuzzy_matching_check.setChecked(True)
        self.fuzzy_matching_check.setObjectName("fuzzy_matching_check")
        self.feature_map_label = QtWidgets.QLabel(self.scroll_contents)
        self.feature_map_label.setGeometry(QtCore.QRect(0, 1010, 681, 31))
        self.feature_map_label.setStyleSheet("border: 0px solid;\n"
"color: rgb(85, 87, 83);")
        self.feature_map_label.setObjectName("feature_map_label")
        self.modeling_label = QtWidgets.QLabel(self.scroll_contents)
        self.modeling_label.setGeometry(QtCore.QRect(0, 1090, 681, 31))
        self.modeling_label.setStyleSheet("border: 0px solid;\n"
"color: rgb(85, 87, 83);")
        self.modeling_label.setObjectName("modeling_label")
        self.prep_steps_label = QtWidgets.QLabel(self.scroll_contents)
        self.prep_steps_label.setGeometry(QtCore.QRect(0, 1130, 681, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prep_steps_label.setFont(font)
        self.prep_steps_label.setStyleSheet("border: 0px solid;")
        self.prep_steps_label.setObjectName("prep_steps_label")
        self.prep_steps_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.prep_steps_ledit.setGeometry(QtCore.QRect(0, 1170, 681, 31))
        self.prep_steps_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.prep_steps_ledit.setObjectName("prep_steps_ledit")
        self.tune_space_label = QtWidgets.QLabel(self.scroll_contents)
        self.tune_space_label.setGeometry(QtCore.QRect(0, 1210, 681, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tune_space_label.setFont(font)
        self.tune_space_label.setStyleSheet("border: 0px solid;")
        self.tune_space_label.setObjectName("tune_space_label")
        self.tune_eval_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.tune_eval_sbox.setGeometry(QtCore.QRect(0, 1380, 131, 31))
        self.tune_eval_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tune_eval_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.tune_eval_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.tune_eval_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.tune_eval_sbox.setMinimum(1)
        self.tune_eval_sbox.setMaximum(100000)
        self.tune_eval_sbox.setProperty("value", 50)
        self.tune_eval_sbox.setObjectName("tune_eval_sbox")
        self.tune_eval_label = QtWidgets.QLabel(self.scroll_contents)
        self.tune_eval_label.setGeometry(QtCore.QRect(0, 1340, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tune_eval_label.setFont(font)
        self.tune_eval_label.setStyleSheet("border: 0px solid;")
        self.tune_eval_label.setObjectName("tune_eval_label")
        self.tune_score_cbox = QtWidgets.QComboBox(self.scroll_contents)
        self.tune_score_cbox.setGeometry(QtCore.QRect(150, 1380, 141, 31))
        self.tune_score_cbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tune_score_cbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.tune_score_cbox.setObjectName("tune_score_cbox")
        self.tune_score_cbox.addItem("")
        self.tune_score_cbox.addItem("")
        self.tune_score_cbox.addItem("")
        self.tune_score_label = QtWidgets.QLabel(self.scroll_contents)
        self.tune_score_label.setGeometry(QtCore.QRect(150, 1340, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tune_score_label.setFont(font)
        self.tune_score_label.setStyleSheet("border: 0px solid;")
        self.tune_score_label.setObjectName("tune_score_label")
        self.tune_splits_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.tune_splits_sbox.setGeometry(QtCore.QRect(310, 1380, 91, 31))
        self.tune_splits_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tune_splits_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.tune_splits_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.tune_splits_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.tune_splits_sbox.setMinimum(1)
        self.tune_splits_sbox.setMaximum(100)
        self.tune_splits_sbox.setProperty("value", 5)
        self.tune_splits_sbox.setObjectName("tune_splits_sbox")
        self.tune_splits_label = QtWidgets.QLabel(self.scroll_contents)
        self.tune_splits_label.setGeometry(QtCore.QRect(310, 1340, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tune_splits_label.setFont(font)
        self.tune_splits_label.setStyleSheet("border: 0px solid;")
        self.tune_splits_label.setObjectName("tune_splits_label")
        self.neighbors_lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.neighbors_lower_bound_ledit.setGeometry(QtCore.QRect(100, 1250, 111, 31))
        self.neighbors_lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.neighbors_lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.neighbors_lower_bound_ledit.setObjectName("neighbors_lower_bound_ledit")
        self.neighbors_upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.neighbors_upper_bound_ledit.setGeometry(QtCore.QRect(230, 1250, 111, 31))
        self.neighbors_upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.neighbors_upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.neighbors_upper_bound_ledit.setObjectName("neighbors_upper_bound_ledit")
        self.neighbors_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.neighbors_conjunction.setGeometry(QtCore.QRect(213, 1255, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.neighbors_conjunction.setFont(font)
        self.neighbors_conjunction.setStyleSheet("border: none;")
        self.neighbors_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.neighbors_conjunction.setObjectName("neighbors_conjunction")
        self.neighbors_label = QtWidgets.QLabel(self.scroll_contents)
        self.neighbors_label.setGeometry(QtCore.QRect(15, 1250, 81, 31))
        self.neighbors_label.setStyleSheet("border: 0px solid;")
        self.neighbors_label.setAlignment(QtCore.Qt.AlignCenter)
        self.neighbors_label.setObjectName("neighbors_label")
        self.weights_label = QtWidgets.QLabel(self.scroll_contents)
        self.weights_label.setGeometry(QtCore.QRect(390, 1250, 71, 31))
        self.weights_label.setStyleSheet("border: 0px solid;")
        self.weights_label.setAlignment(QtCore.Qt.AlignCenter)
        self.weights_label.setObjectName("weights_label")
        self.p_label = QtWidgets.QLabel(self.scroll_contents)
        self.p_label.setGeometry(QtCore.QRect(430, 1300, 31, 31))
        self.p_label.setStyleSheet("border: 0px solid;")
        self.p_label.setAlignment(QtCore.Qt.AlignCenter)
        self.p_label.setObjectName("p_label")
        self.p_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.p_ledit.setGeometry(QtCore.QRect(460, 1300, 221, 31))
        self.p_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.p_ledit.setObjectName("p_ledit")
        self.visualization_label = QtWidgets.QLabel(self.scroll_contents)
        self.visualization_label.setGeometry(QtCore.QRect(0, 1460, 681, 31))
        self.visualization_label.setStyleSheet("border: 0px solid;\n"
"color: rgb(85, 87, 83);")
        self.visualization_label.setObjectName("visualization_label")
        self.oof_splits_label = QtWidgets.QLabel(self.scroll_contents)
        self.oof_splits_label.setGeometry(QtCore.QRect(420, 1340, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.oof_splits_label.setFont(font)
        self.oof_splits_label.setStyleSheet("border: 0px solid;")
        self.oof_splits_label.setObjectName("oof_splits_label")
        self.oof_splits_sbox = QtWidgets.QSpinBox(self.scroll_contents)
        self.oof_splits_sbox.setGeometry(QtCore.QRect(420, 1380, 91, 31))
        self.oof_splits_sbox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.oof_splits_sbox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.oof_splits_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.oof_splits_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.oof_splits_sbox.setMinimum(1)
        self.oof_splits_sbox.setMaximum(100)
        self.oof_splits_sbox.setProperty("value", 5)
        self.oof_splits_sbox.setObjectName("oof_splits_sbox")
        self.write_features_check = QtWidgets.QCheckBox(self.scroll_contents)
        self.write_features_check.setGeometry(QtCore.QRect(0, 1420, 141, 23))
        self.write_features_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.write_features_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.write_features_check.setChecked(True)
        self.write_features_check.setObjectName("write_features_check")
        self.graphs_lwidget = QtWidgets.QListWidget(self.scroll_contents)
        self.graphs_lwidget.setGeometry(QtCore.QRect(0, 1540, 261, 31))
        self.graphs_lwidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graphs_lwidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.graphs_lwidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.graphs_lwidget.setObjectName("graphs_lwidget")
        self.graphs_label = QtWidgets.QLabel(self.scroll_contents)
        self.graphs_label.setGeometry(QtCore.QRect(0, 1500, 241, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.graphs_label.setFont(font)
        self.graphs_label.setStyleSheet("border: 0px solid;")
        self.graphs_label.setObjectName("graphs_label")
        self.kpi_label = QtWidgets.QLabel(self.scroll_contents)
        self.kpi_label.setGeometry(QtCore.QRect(280, 1500, 401, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.kpi_label.setFont(font)
        self.kpi_label.setStyleSheet("border: 0px solid;")
        self.kpi_label.setObjectName("kpi_label")
        self.kpi_lwidget = QtWidgets.QListWidget(self.scroll_contents)
        self.kpi_lwidget.setGeometry(QtCore.QRect(280, 1540, 401, 71))
        self.kpi_lwidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.kpi_lwidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.kpi_lwidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.kpi_lwidget.setViewMode(QtWidgets.QListView.IconMode)
        self.kpi_lwidget.setItemAlignment(QtCore.Qt.AlignCenter)
        self.kpi_lwidget.setObjectName("kpi_lwidget")
        self.weights_lwidget = QtWidgets.QListWidget(self.scroll_contents)
        self.weights_lwidget.setGeometry(QtCore.QRect(460, 1250, 221, 31))
        self.weights_lwidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.weights_lwidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.weights_lwidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.weights_lwidget.setObjectName("weights_lwidget")
        self.inspect_model_check = QtWidgets.QCheckBox(self.scroll_contents)
        self.inspect_model_check.setGeometry(QtCore.QRect(150, 1420, 141, 23))
        self.inspect_model_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inspect_model_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.inspect_model_check.setChecked(True)
        self.inspect_model_check.setObjectName("inspect_model_check")
        self.evaluate_model_check = QtWidgets.QCheckBox(self.scroll_contents)
        self.evaluate_model_check.setGeometry(QtCore.QRect(300, 1420, 141, 23))
        self.evaluate_model_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.evaluate_model_check.setStyleSheet("border: 0px;\n"
"color: rgb(0, 0, 0);")
        self.evaluate_model_check.setChecked(True)
        self.evaluate_model_check.setObjectName("evaluate_model_check")
        self.features_lwidget = QtWidgets.QListWidget(self.scroll_contents)
        self.features_lwidget.setGeometry(QtCore.QRect(0, 760, 561, 71))
        self.features_lwidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.features_lwidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.features_lwidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.features_lwidget.setViewMode(QtWidgets.QListView.IconMode)
        self.features_lwidget.setItemAlignment(QtCore.Qt.AlignCenter)
        self.features_lwidget.setObjectName("features_lwidget")
        self.features_plus_tbutton = QtWidgets.QToolButton(self.scroll_contents)
        self.features_plus_tbutton.setGeometry(QtCore.QRect(570, 800, 30, 30))
        self.features_plus_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.features_plus_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/black_icons/icons_black/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.features_plus_tbutton.setIcon(icon1)
        self.features_plus_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.features_plus_tbutton.setObjectName("features_plus_tbutton")
        self.features_minus_tbutton = QtWidgets.QToolButton(self.scroll_contents)
        self.features_minus_tbutton.setGeometry(QtCore.QRect(610, 800, 30, 30))
        self.features_minus_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.features_minus_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/black_icons/icons_black/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.features_minus_tbutton.setIcon(icon2)
        self.features_minus_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.features_minus_tbutton.setObjectName("features_minus_tbutton")
        self.features_load_tbutton = QtWidgets.QToolButton(self.scroll_contents)
        self.features_load_tbutton.setGeometry(QtCore.QRect(650, 800, 30, 30))
        self.features_load_tbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.features_load_tbutton.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/black_icons/icons_black/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.features_load_tbutton.setIcon(icon3)
        self.features_load_tbutton.setIconSize(QtCore.QSize(18, 18))
        self.features_load_tbutton.setObjectName("features_load_tbutton")
        self.leaf_size_conjunction = QtWidgets.QLabel(self.scroll_contents)
        self.leaf_size_conjunction.setGeometry(QtCore.QRect(213, 1305, 16, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.leaf_size_conjunction.setFont(font)
        self.leaf_size_conjunction.setStyleSheet("border: none;")
        self.leaf_size_conjunction.setAlignment(QtCore.Qt.AlignCenter)
        self.leaf_size_conjunction.setObjectName("leaf_size_conjunction")
        self.leaf_size_upper_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.leaf_size_upper_bound_ledit.setGeometry(QtCore.QRect(230, 1300, 111, 31))
        self.leaf_size_upper_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.leaf_size_upper_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.leaf_size_upper_bound_ledit.setObjectName("leaf_size_upper_bound_ledit")
        self.leaf_size_label = QtWidgets.QLabel(self.scroll_contents)
        self.leaf_size_label.setGeometry(QtCore.QRect(20, 1300, 81, 31))
        self.leaf_size_label.setStyleSheet("border: 0px solid;")
        self.leaf_size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.leaf_size_label.setObjectName("leaf_size_label")
        self.leaf_size_lower_bound_ledit = QtWidgets.QLineEdit(self.scroll_contents)
        self.leaf_size_lower_bound_ledit.setGeometry(QtCore.QRect(100, 1300, 111, 31))
        self.leaf_size_lower_bound_ledit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);\n"
"border: 1px solid;\n"
"border-color: rgb(186, 189, 182);")
        self.leaf_size_lower_bound_ledit.setAlignment(QtCore.Qt.AlignCenter)
        self.leaf_size_lower_bound_ledit.setObjectName("leaf_size_lower_bound_ledit")
        self.scroll_area.setWidget(self.scroll_contents)
        k_nearest_neighbors_ntcp_window.setCentralWidget(self.body_widget)

        self.retranslateUi(k_nearest_neighbors_ntcp_window)
        self.embedding_cbox.setCurrentIndex(0)
        self.type_cbox.setCurrentIndex(0)
        self.filter_mode_cbox.setCurrentIndex(0)
        self.label_viewpoint_cbox.setCurrentIndex(3)
        self.tune_score_cbox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(k_nearest_neighbors_ntcp_window)

    def retranslateUi(self, k_nearest_neighbors_ntcp_window):
        _translate = QtCore.QCoreApplication.translate
        k_nearest_neighbors_ntcp_window.setWindowTitle(_translate("k_nearest_neighbors_ntcp_window", "K-Nearest Neighbors NTCP Editor"))
        self.embedding_cbox.setItemText(0, _translate("k_nearest_neighbors_ntcp_window", "active"))
        self.embedding_cbox.setItemText(1, _translate("k_nearest_neighbors_ntcp_window", "passive"))
        self.segment_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Segment"))
        self.embedding_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Embedding"))
        self.base_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Base"))
        self.type_cbox.setItemText(0, _translate("k_nearest_neighbors_ntcp_window", "objective"))
        self.type_cbox.setItemText(1, _translate("k_nearest_neighbors_ntcp_window", "constraint"))
        self.type_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Type"))
        self.close_component_pbutton.setText(_translate("k_nearest_neighbors_ntcp_window", "Close"))
        self.identifier_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "None"))
        self.identifier_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Identifier"))
        self.link_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "None"))
        self.link_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Link"))
        self.function_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Function"))
        self.bounds_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Bounds"))
        self.handling_viz_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Handling & Visualization"))
        self.weight_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Weight"))
        self.save_component_pbutton.setText(_translate("k_nearest_neighbors_ntcp_window", "Save"))
        self.opt_bounds_conjunction.setText(_translate("k_nearest_neighbors_ntcp_window", "-"))
        self.optimization_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Optimization"))
        self.rank_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Rank"))
        self.upper_bound_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "1.0"))
        self.weight_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "1.0"))
        self.disp_component_check.setText(_translate("k_nearest_neighbors_ntcp_window", "Display component"))
        self.lower_bound_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "0.0"))
        self.outcome_model_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Outcome model"))
        self.model_label_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Model label"))
        self.model_path_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Model path"))
        self.model_path_tbutton.setToolTip(_translate("k_nearest_neighbors_ntcp_window", "Add the model data from a folder"))
        self.model_path_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "None"))
        self.data_path_tbutton.setToolTip(_translate("k_nearest_neighbors_ntcp_window", "Add the outcome data from a folder"))
        self.data_path_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Data path"))
        self.features_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Features"))
        self.data_filter_label.setText(_translate("k_nearest_neighbors_ntcp_window", "DATA FILTER"))
        self.filter_mode_cbox.setItemText(0, _translate("k_nearest_neighbors_ntcp_window", "remove"))
        self.filter_mode_cbox.setItemText(1, _translate("k_nearest_neighbors_ntcp_window", "retain"))
        self.filter_mode_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Filter mode"))
        self.label_name_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Label name"))
        self.label_lower_bound_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "1.0"))
        self.label_bounds_conjunction.setText(_translate("k_nearest_neighbors_ntcp_window", "-"))
        self.label_bounds_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Label bounds"))
        self.label_upper_bound_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "1.0"))
        self.time_variable_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Time variable name"))
        self.time_variable_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "None"))
        self.label_viewpoint_cbox.setItemText(0, _translate("k_nearest_neighbors_ntcp_window", "early"))
        self.label_viewpoint_cbox.setItemText(1, _translate("k_nearest_neighbors_ntcp_window", "late"))
        self.label_viewpoint_cbox.setItemText(2, _translate("k_nearest_neighbors_ntcp_window", "long-term"))
        self.label_viewpoint_cbox.setItemText(3, _translate("k_nearest_neighbors_ntcp_window", "longitudinal"))
        self.label_viewpoint_cbox.setItemText(4, _translate("k_nearest_neighbors_ntcp_window", "profile"))
        self.label_viewpoint_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Label viewpoint"))
        self.fuzzy_matching_check.setText(_translate("k_nearest_neighbors_ntcp_window", "Fuzzy string matching"))
        self.feature_map_label.setText(_translate("k_nearest_neighbors_ntcp_window", "FEATURE MAP"))
        self.modeling_label.setText(_translate("k_nearest_neighbors_ntcp_window", "MODEL FITTING, INSPECTION & EVALUATION"))
        self.prep_steps_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Preprocessing steps"))
        self.prep_steps_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "[Identity]"))
        self.tune_space_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Tune space"))
        self.tune_eval_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Tune evaluations"))
        self.tune_score_cbox.setItemText(0, _translate("k_nearest_neighbors_ntcp_window", "AUC"))
        self.tune_score_cbox.setItemText(1, _translate("k_nearest_neighbors_ntcp_window", "Brier score"))
        self.tune_score_cbox.setItemText(2, _translate("k_nearest_neighbors_ntcp_window", "Logloss"))
        self.tune_score_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Tune score"))
        self.tune_splits_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Tune splits"))
        self.neighbors_lower_bound_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "1"))
        self.neighbors_upper_bound_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "⌊0.5*|samples|⌉"))
        self.neighbors_conjunction.setText(_translate("k_nearest_neighbors_ntcp_window", "-"))
        self.neighbors_label.setText(_translate("k_nearest_neighbors_ntcp_window", "neighbors"))
        self.weights_label.setText(_translate("k_nearest_neighbors_ntcp_window", "weights"))
        self.p_label.setText(_translate("k_nearest_neighbors_ntcp_window", "p"))
        self.p_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "[1, 2, 3]"))
        self.visualization_label.setText(_translate("k_nearest_neighbors_ntcp_window", "VISUALIZATION"))
        self.oof_splits_label.setText(_translate("k_nearest_neighbors_ntcp_window", "OOF splits"))
        self.write_features_check.setText(_translate("k_nearest_neighbors_ntcp_window", "Write features"))
        self.graphs_label.setText(_translate("k_nearest_neighbors_ntcp_window", "Graphs"))
        self.kpi_label.setText(_translate("k_nearest_neighbors_ntcp_window", "KPIs"))
        self.inspect_model_check.setText(_translate("k_nearest_neighbors_ntcp_window", "Inspect model"))
        self.evaluate_model_check.setText(_translate("k_nearest_neighbors_ntcp_window", "Evaluate model"))
        self.features_plus_tbutton.setToolTip(_translate("k_nearest_neighbors_ntcp_window", "Add feature"))
        self.features_minus_tbutton.setToolTip(_translate("k_nearest_neighbors_ntcp_window", "Remove feature"))
        self.features_load_tbutton.setToolTip(_translate("k_nearest_neighbors_ntcp_window", "Load features from data"))
        self.leaf_size_conjunction.setText(_translate("k_nearest_neighbors_ntcp_window", "-"))
        self.leaf_size_upper_bound_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "500"))
        self.leaf_size_label.setText(_translate("k_nearest_neighbors_ntcp_window", "leaf size"))
        self.leaf_size_lower_bound_ledit.setPlaceholderText(_translate("k_nearest_neighbors_ntcp_window", "1"))
